package main

import (
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"github.com/sahil87/fab-kit/src/go/fab/internal/config"
	"github.com/sahil87/fab-kit/src/go/fab/internal/configref"
	"github.com/sahil87/fab-kit/src/go/fab/internal/configscope"
	"github.com/sahil87/fab-kit/src/go/fab/internal/configupgrade"
	"github.com/sahil87/fab-kit/src/go/fab/internal/resolve"
	"github.com/spf13/cobra"
	"gopkg.in/yaml.v3"
)

// configCmd is the six-verb `fab config` command group: show/explain inspect,
// set/unset surgically modify, and init/upgrade own whole-file lifecycle.
func configCmd() *cobra.Command {
	cmd := &cobra.Command{
		Use:   "config",
		Short: "Inspect, modify, and maintain fab configuration",
		Long: "Inspect effective config with `show` and schema documentation with " +
			"`explain`; apply comment-preserving overrides with `set` and `unset`; " +
			"bootstrap files with `init`; and reconcile the project file with `upgrade`.",
	}
	cmd.AddGroup(
		&cobra.Group{ID: "inspect", Title: "Inspect Commands:"},
		&cobra.Group{ID: "modify", Title: "Modify Commands:"},
		&cobra.Group{ID: "lifecycle", Title: "Lifecycle Commands:"},
	)
	show := configShowCmd()
	show.GroupID = "inspect"
	explain := configReferenceCmd()
	explain.GroupID = "inspect"
	set := configSetCmd()
	set.GroupID = "modify"
	unset := configUnsetCmd()
	unset.GroupID = "modify"
	init := configInitCmd()
	init.GroupID = "lifecycle"
	upgrade := configUpgradeCmd()
	upgrade.GroupID = "lifecycle"
	cmd.AddCommand(show, explain, set, unset, init, upgrade)
	return cmd
}

// configUpgradeCmd implements whole-file reconciliation for
// fab/project/config.yaml. It reconciles the file against the
// registry: live (A) fields kept verbatim, the managed fence of commented C fields
// regenerated byte-stable, unknown live keys parked below the fence (never
// deleted), and renamed_from renames carried mechanically. The write is atomic and
// idempotent (running twice is byte-identical). It stamps the fence with this
// binary's version. `fab upgrade-repo` auto-runs it after sync. With --check it is
// the drift probe instead: the same computation, zero writes, non-zero exit when a
// run would change the file.
func configUpgradeCmd() *cobra.Command {
	var check bool
	cmd := &cobra.Command{
		Use:   "upgrade",
		Short: "Reconcile fab/project/config.yaml against the current field registry",
		Long: "Rewrites fab/project/config.yaml mechanically against the binary's field " +
			"registry through the shared comment-aware writer. Live (overridden) " +
			"fields are kept verbatim, including your own comments; the managed fence of " +
			"commented reference fields is regenerated (byte-stable, idempotent); a field " +
			"no longer in the registry is PARKED in a comment block below the fence (never " +
			"silently deleted); a renamed field is carried to its new key. Running it twice " +
			"is byte-identical. Requires a fab repo (walks up for fab/).\n\n" +
			"With --check, computes exactly the same reconciliation but writes NOTHING: it " +
			"prints what a run would change and exits non-zero when the file has drifted " +
			"(a stale fence kit-version stamp, unparked removed keys, a missing fence, or " +
			"any rendered-content delta — including a missing config.yaml, which a real run " +
			"would create), and exits 0 when the file is clean. This is the CI/human probe " +
			"for \"is this repo's config clean?\".",
		Args: cobra.NoArgs,
		RunE: func(cmd *cobra.Command, _ []string) error {
			fabRoot, err := resolve.FabRoot()
			if err != nil {
				return err
			}
			path := filepath.Join(fabRoot, "project", "config.yaml")
			if check {
				res, err := configupgrade.Check(path, version)
				if err != nil {
					return err
				}
				if !res.Changed {
					fmt.Fprintf(cmd.OutOrStdout(), "%s already up to date (kit %s)\n", path, version)
					return nil
				}
				fmt.Fprintf(cmd.OutOrStdout(), "%s has drifted — `fab config upgrade` would change it (kit %s):\n", path, version)
				for _, line := range res.Report {
					fmt.Fprintf(cmd.OutOrStdout(), "  - %s\n", line)
				}
				return fmt.Errorf("%s has drifted from the field registry — run `fab config upgrade` to reconcile", path)
			}
			res, err := configupgrade.Upgrade(path, version)
			if err != nil {
				return err
			}
			if res.Changed {
				fmt.Fprintf(cmd.OutOrStdout(), "Upgraded %s (kit %s)\n", path, version)
			} else {
				fmt.Fprintf(cmd.OutOrStdout(), "%s already up to date (kit %s)\n", path, version)
			}
			for _, line := range res.Report {
				fmt.Fprintf(cmd.OutOrStdout(), "  - %s\n", line)
			}
			return nil
		},
	}
	cmd.Flags().BoolVar(&check, "check", false, "Report what an upgrade would change without writing; exit non-zero when the file has drifted")
	return cmd
}

// configReferenceCmd implements visible `fab config explain` and retains
// `reference` as an invisible Cobra alias for historical pointers. It is a pure
// query (no effects, no file writes) in the same family as `fab resolve` / `fab
// resolve-agent`. It prints the fully-commented reference config.yaml to
// stdout and exits 0 on success. More than one positional arg is a usage error;
// an unknown keyed lookup or render failure exits non-zero. The output is
// GENERATED from a per-field metadata table (see
// internal/configref) whose defaults are sourced from the binary's own canonical
// symbols (the dispatch ones are vars internal/agent fills from the embedded
// defaults.yaml), and is byte-stable for a given binary version. The `--json` flag
// emits that same table as a machine-readable JSON array instead of commented
// YAML — the tooling surface the config-upgrade cascade/upgrade commands consume.
func configReferenceCmd() *cobra.Command {
	var asJSON bool
	cmd := &cobra.Command{
		Use:     "explain [key]",
		Aliases: []string{"reference"},
		Short:   "Explain available config keys",
		Long: "Prints a fully-commented reference fab/project/config.yaml to " +
			"stdout, documenting every available option (both binary-consumed " +
			"and skill-consumed keys). Baseline keys appear live with example " +
			"values; optional override blocks (agent.profiles, stage_hooks, " +
			"branch_prefix) appear commented-out with fab-kit's built-in " +
			"defaults. The output is generated from a per-field metadata table " +
			"(never hand-written; defaults sourced from the binary's own " +
			"canonical symbols) and is byte-stable for a given version. Pass one known dotted " +
			"key to print only its owning segment; pass --json for the matching field " +
			"row(s). `reference` remains a compatibility alias. Pure query — writes no file.",
		Example: `  fab config explain
  fab config explain agent.workers
  fab config explain providers.codex.interactive_command --json`,
		Args: cobra.MaximumNArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			key := ""
			if len(args) == 1 {
				key = args[0]
			}
			out, err := renderReference(asJSON, key)
			if err != nil {
				return err
			}
			fmt.Fprint(cmd.OutOrStdout(), out)
			return nil
		},
	}
	cmd.Flags().BoolVar(&asJSON, "json", false, "Emit the field metadata table as a JSON array (instead of commented YAML)")
	return cmd
}

// renderReference selects the reference rendering: the machine-readable JSON
// field table when asJSON is set, otherwise the commented YAML. Both are pure,
// byte-stable renderings of the same per-field metadata table.
func renderReference(asJSON bool, key ...string) (string, error) {
	selected := ""
	if len(key) > 0 {
		selected = key[0]
	}
	if asJSON && selected != "" {
		return configref.RenderJSONKey(selected)
	}
	if asJSON {
		return configref.RenderJSON()
	}
	if selected != "" {
		return configref.RenderKey(selected)
	}
	return configref.Render()
}

// configShowCmd implements `fab config show [key] [--origin]` — a pure query (no
// file writes) in the same family as `fab config explain`. It resolves the
// effective (post-cascade) config for the current repo and prints it. Without a
// flag it prints the fully composed config as YAML — the built-in defaults tier
// merged beneath the environment and file layers, so unset fields surface at
// their built-in values. With --origin it prints, per
// registry field, the effective value alongside its provenance (the git config
// --show-origin precedent): environment variable, `system` file path, `project`
// file path, or `default` — with per-key drill-down for map-valued fields
// (agent.profiles, providers), since maps merge per-key. --origin surfaces a
// typo'd override: the field the user meant to set shows `default` when their file
// was expected to win. KEYED --origin goes further and lists the key's whole
// stack, so a shadowed override is visible rather than having to be inferred.
func configShowCmd() *cobra.Command {
	var withOrigin bool
	cmd := &cobra.Command{
		Use:   "show [key]",
		Short: "Print the effective (post-cascade) config, optionally with per-field provenance",
		Long: "Resolves the effective fab config across the cascade — " +
			"environment > system (~/.fab-kit/config.yaml) > project " +
			"(fab/project/config.yaml) > built-in " +
			"defaults — and prints it. Each leaf takes the value of the highest tier " +
			"that defines it NON-EMPTY: a null, empty string, empty list, or empty map " +
			"falls through to the tier below instead of shadowing it. Without a flag, " +
			"prints the FULLY COMPOSED config as YAML — the built-in defaults merged " +
			"beneath the environment and two files, so unset fields appear at their " +
			"built-in values. With --origin, prints each " +
			"field's effective value and its provenance (environment variable / system " +
			"path / project path / default), composing the built-in defaults into the " +
			"listing and drilling down per-key for map-valued fields (agent.profiles, " +
			"providers). With a KEY and --origin, prints the key's full stack instead — " +
			"one line per tier that defines it, the winner marked (effective) and the " +
			"rest (shadowed). Pure query — writes no file.",
		Example: `  # Print the effective (post-cascade) config
  fab config show

  # Annotate each field with its provenance (environment / system / project / default)
  fab config show --origin

  # Inspect one effective value
  fab config show agent.workers

  # List every tier that defines one key, winner first
  fab config show agent.workers --origin`,
		Args: cobra.MaximumNArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			fabRoot, err := resolve.FabRoot()
			if err != nil {
				return err
			}
			projectPath := filepath.Join(fabRoot, "project", "config.yaml")
			layers, err := config.LoadLayers(projectPath)
			if err != nil {
				return err
			}
			// Bare `show` prints the FULLY composed config — the defaults projection
			// merged beneath the file+environment layers — so every surface pays for
			// the same projection and no form under-reports unset fields.
			defaults, err := readModelDefaults(layers)
			if err != nil {
				return err
			}
			if len(args) == 1 {
				out, err := renderShowKey(layers, defaults, args[0], withOrigin)
				if err != nil {
					return err
				}
				fmt.Fprint(cmd.OutOrStdout(), out)
				return nil
			}
			out, err := renderShow(layers, defaults, withOrigin)
			if err != nil {
				return err
			}
			fmt.Fprint(cmd.OutOrStdout(), out)
			return nil
		},
	}
	cmd.Flags().BoolVar(&withOrigin, "origin", false, "Annotate each field with its provenance; with a key, list every tier that defines it")
	return cmd
}

// readModelDefaults projects the registry's built-in defaults into the bottom
// tier of the read model, composed against the LIVE config so the derived
// agent.profiles rows report the provider a depth knob actually selects (they are
// resolved from the knob + the provider's fills, not stored anywhere). It takes
// the ALREADY-LOADED layers rather than re-running the cascade: a second load
// would re-read the system file and re-emit every fail-open `fab: warning:`. A
// merged tree that will not unmarshal leaves the projection knob-blind rather
// than failing the query.
func readModelDefaults(layers *config.Layers) (map[string]any, error) {
	cfg, err := config.FromMap(layers.Effective)
	if err != nil {
		return configref.DefaultsMap()
	}
	return configref.DefaultsMapFor(cfg)
}

// renderShowKey resolves exactly one known dotted key across the read model —
// default < project < system < env, per-leaf with empty-skip — and prints it.
// Scalars/lists print as the raw value; mappings print their YAML subtree. With
// --origin the key's FULL STACK is listed instead: one line per tier that defines
// it, highest precedence first, the winner marked (effective) and the rest
// (shadowed). A map-valued key drills down per leaf, each leaf listing its own
// defining tiers.
func renderShowKey(layers *config.Layers, defaults map[string]any, key string, withOrigin bool) (string, error) {
	if _, ok, err := configref.ResolveKey(key); err != nil {
		return "", err
	} else if !ok {
		return "", fmt.Errorf("unknown config key %q", key)
	}
	parts := strings.Split(key, ".")
	top := parts[0]

	if withOrigin {
		lines := keyedOriginLines(key, cascadeTiers(defaults, layers, top), layers.EnvOrigins)
		return renderOriginLines(lines), nil
	}

	effective := config.MergeLayers(subtreeLayer(defaults, top), subtreeLayer(layers.Project, top),
		subtreeLayer(layers.System, top), subtreeLayer(layers.Env, top))
	value, present := valueAtPath(effective[top], parts[1:])
	if !present {
		value = nil
	}
	if _, isMap := asGenericMap(value); isMap {
		data, err := yaml.Marshal(value)
		if err != nil {
			return "", err
		}
		return string(data), nil
	}
	return renderCompactValue(value) + "\n", nil
}

// subtreeLayer isolates one top-level key of a layer map so the four tiers can be
// merged through the shared MergeLayers rule without carrying every other key.
func subtreeLayer(m map[string]any, top string) map[string]any {
	v, ok := m[top]
	if !ok {
		return nil
	}
	return map[string]any{top: v}
}

func valueAtPath(value any, parts []string) (any, bool) {
	current := value
	for _, part := range parts {
		mapping, ok := asGenericMap(current)
		if !ok {
			return nil, false
		}
		current, ok = mapping[part]
		if !ok {
			return nil, false
		}
	}
	return current, true
}

func renderOriginLines(lines []originLine) string {
	width := 0
	for _, line := range lines {
		if n := len(line.left()); n > width {
			width = n
		}
	}
	var b strings.Builder
	for _, line := range lines {
		fmt.Fprintf(&b, "%-*s  # %s\n", width, line.left(), line.origin)
	}
	return b.String()
}

func renderCompactValue(value any) string {
	if value == nil {
		return "null"
	}
	switch value.(type) {
	case []any, map[string]any, map[any]any:
		var node yaml.Node
		data, err := yaml.Marshal(value)
		if err == nil && yaml.Unmarshal(data, &node) == nil && len(node.Content) == 1 {
			flowStyle(node.Content[0])
			if compact, marshalErr := yaml.Marshal(node.Content[0]); marshalErr == nil {
				return strings.TrimSpace(string(compact))
			}
		}
	}
	return fmt.Sprintf("%v", value)
}

func flowStyle(node *yaml.Node) {
	if node.Kind == yaml.SequenceNode || node.Kind == yaml.MappingNode {
		node.Style |= yaml.FlowStyle
	}
	for _, child := range node.Content {
		flowStyle(child)
	}
}

// renderShow renders the effective config, plain (fully composed YAML — the
// built-in defaults tier merged beneath the file and environment layers) or
// with per-field provenance. It is factored out of the cobra RunE so it is
// unit-testable.
func renderShow(layers *config.Layers, defaults map[string]any, withOrigin bool) (string, error) {
	if !withOrigin {
		effective := config.MergeLayers(defaults, layers.Effective)
		if len(effective) == 0 {
			return "# (no effective config — no project or system config.yaml found)\n", nil
		}
		data, err := yaml.Marshal(effective)
		if err != nil {
			return "", err
		}
		return string(data), nil
	}
	return renderShowOrigin(layers, defaults)
}

// renderShowOrigin walks the field registry and prints each field's effective
// leaf values with provenance — one line per leaf, the WINNER only. For every
// registry field it resolves the field's subtree across the four tiers
// (environment > system > project > built-in defaults) and flattens to leaves,
// printing `dotted.key = value  # origin` where origin is the highest tier that
// DEFINES the leaf. The keyed form (renderShowKey) lists the whole stack instead.
func renderShowOrigin(layers *config.Layers, defaults map[string]any) (string, error) {
	fields, err := configref.Fields()
	if err != nil {
		return "", err
	}
	var lines []originLine
	seenKeyTop := map[string]bool{} // avoid re-walking a top-level key documented by multiple registry rows (project.name/description/…)
	for _, f := range fields {
		top := topLevelKey(f.Key)
		// Registry rows like project.name / project.description / project.linear_workspace
		// all map to the top-level `project` subtree; walk each top-level subtree once.
		if seenKeyTop[top] {
			continue
		}
		seenKeyTop[top] = true
		lines = append(lines, flattenOrigin(top, cascadeTiers(defaults, layers, top), layers.EnvOrigins)...)
	}

	if len(lines) == 0 {
		return "# (no fields resolved)\n", nil
	}
	// Deterministic output: registry order already governs the top-level walk;
	// within a subtree flattenOrigin sorts leaf keys, so the whole thing is stable.
	return renderOriginLines(lines), nil
}

// originLine is one flattened leaf: its dotted key, rendered value, and origin.
type originLine struct {
	key    string
	value  string
	origin string
}

func (o originLine) left() string { return o.key + " = " + o.value }

// topLevelKey collapses a dotted registry key to its top-level YAML key
// ("agent.profiles" → "agent", "project.name" → "project", "source_paths" →
// "source_paths").
func topLevelKey(key string) string {
	if i := strings.IndexByte(key, '.'); i >= 0 {
		return key[:i]
	}
	return key
}

// Tier kinds, highest precedence first. They are the words the keyed --origin
// stack listing prints; the winner-only listing prints the tier's LABEL instead
// (the git config --show-origin precedent).
const (
	tierEnv     = "env"
	tierSystem  = "system"
	tierProject = "project"
	tierDefault = "default"
)

// cascadeTier is one tier of the config read model at one node of the tree: the
// value that tier supplies there, plus how to name it. A tier DEFINES the node
// when its value is non-empty (config.IsEmptyValue) — the same test the merge
// applies, so provenance can never disagree with resolution.
type cascadeTier struct {
	kind  string
	label string // file path; empty for env (named per leaf) and for default
	value any
}

func (t cascadeTier) defines() bool { return !config.IsEmptyValue(t.value) }

// origin is the winner-only label: the exact environment variable, the project or
// system file path, or `default`.
func (t cascadeTier) origin(key string, envOrigins map[string]string) string {
	switch t.kind {
	case tierEnv:
		if variable := envOrigin(key, envOrigins); variable != "" {
			return variable
		}
		return tierEnv // no recorded variable: the tier word is the only honest label
	case tierDefault:
		return tierDefault
	default:
		return t.label
	}
}

// stackOrigin is the keyed full-stack label: the tier word plus its label, so a
// listing of several tiers reads as a stack rather than as two bare file paths. A
// tier whose label IS its own word (`default`, and an environment leaf with no
// recorded variable) prints that word once rather than twice.
func (t cascadeTier) stackOrigin(key string, envOrigins map[string]string) string {
	origin := t.origin(key, envOrigins)
	if origin == t.kind {
		return t.kind
	}
	return t.kind + " " + origin
}

// cascadeTiers returns the four tiers for one top-level key, highest precedence
// first: environment > system > project > built-in defaults. The system path may
// be "" (HOME unresolvable); it never defines a leaf in that case, so the label is
// only ever printed for a genuine system-layer leaf.
func cascadeTiers(defaults map[string]any, layers *config.Layers, top string) []cascadeTier {
	return []cascadeTier{
		{kind: tierEnv, value: pruneEmpty(layers.Env[top])},
		{kind: tierSystem, label: layers.SystemPath, value: pruneEmpty(layers.System[top])},
		{kind: tierProject, label: layers.ProjectPath, value: pruneEmpty(layers.Project[top])},
		{kind: tierDefault, value: pruneEmpty(defaults[top])},
	}
}

// pruneEmptyKey is the throwaway wrapper key pruneEmpty merges under; the merge
// rule is defined over layer MAPS, and one synthetic key is what borrows it for a
// single value without a second implementation.
const pruneEmptyKey = "v"

// pruneEmpty drops a tier value's empty leaves RECURSIVELY, exactly as the merge
// does, returning nil when nothing survives. Without it a tier's `defines()` test
// would be shallow while the merge is deep, so a map whose every leaf is empty
// (`agent: {workers: null}`) would be reported as the defining tier for a value it
// cannot actually supply — provenance contradicting resolution.
func pruneEmpty(v any) any {
	if config.IsEmptyValue(v) {
		return nil
	}
	if _, isMap := asGenericMap(v); !isMap {
		return v // lists and scalars are leaves: non-empty is all there is to test
	}
	return config.MergeLayers(map[string]any{pruneEmptyKey: v})[pruneEmptyKey]
}

// definingTiers keeps only the tiers that define the node, order preserved. The
// first is the winner; the rest are shadowed.
func definingTiers(tiers []cascadeTier) []cascadeTier {
	var out []cascadeTier
	for _, t := range tiers {
		if t.defines() {
			out = append(out, t)
		}
	}
	return out
}

// mergeableTiers returns the tiers that survive to the merge AT THIS NODE, in
// precedence order. Walking high→low: a tier that defines nothing neither wins nor
// shadows (empty-skip), and the first tier that defines a NON-map replaces the
// whole subtree — every lower tier is shadowed and must not leak in as phantom
// children.
func mergeableTiers(tiers []cascadeTier) []cascadeTier {
	var out []cascadeTier
	for _, t := range tiers {
		if !t.defines() {
			continue
		}
		m, isMap := asGenericMap(t.value)
		if !isMap {
			break
		}
		out = append(out, cascadeTier{kind: t.kind, label: t.label, value: m})
	}
	return out
}

// childTiers descends every tier one key deeper. A tier that does not carry the
// key contributes nil, which is empty and therefore defines nothing.
func childTiers(tiers []cascadeTier, key string) []cascadeTier {
	out := make([]cascadeTier, 0, len(tiers))
	for _, t := range tiers {
		m, _ := asGenericMap(t.value)
		out = append(out, cascadeTier{kind: t.kind, label: t.label, value: m[key]})
	}
	return out
}

// childKeys is the sorted union of the keys the mergeable tiers carry.
func childKeys(tiers []cascadeTier) []string {
	maps := make([]map[string]any, 0, len(tiers))
	for _, t := range tiers {
		m, _ := asGenericMap(t.value)
		maps = append(maps, m)
	}
	keys := unionKeys(maps...)
	sort.Strings(keys)
	return keys
}

// flattenOrigin flattens the node at prefix into WINNER-ONLY originLines: each
// leaf's value and the highest tier that defines it. Map nodes recurse per-key
// (the honest granularity where maps merge per-key); a scalar or list is a single
// leaf. A node no tier defines emits nothing.
func flattenOrigin(prefix string, tiers []cascadeTier, envOrigins map[string]string) []originLine {
	defining := definingTiers(tiers)
	if len(defining) == 0 {
		return nil
	}
	winner := defining[0]
	if _, isMap := asGenericMap(winner.value); !isMap {
		return []originLine{{key: prefix, value: renderScalar(winner.value), origin: winner.origin(prefix, envOrigins)}}
	}
	mergeable := mergeableTiers(tiers)
	var out []originLine
	for _, k := range childKeys(mergeable) {
		out = append(out, flattenOrigin(prefix+"."+k, childTiers(mergeable, k), envOrigins)...)
	}
	return out
}

// pathDescent is the outcome of walking a dotted key down the tier stack — the
// one descent both provenance surfaces share (the keyed --origin listing and the
// set/unset shadow notices ask the same question of the same stack).
type pathDescent struct {
	// tiers is the stack AT the requested node, valid only when found is true and
	// ancestor is nil.
	tiers []cascadeTier
	// ancestor is the tier whose NON-MAP value replaces the requested node's whole
	// subtree (`FAB_PROVIDERS=oops` over a project providers block), with
	// ancestorKey its dotted path — the granularity its env origin is recorded at.
	ancestor    *cascadeTier
	ancestorKey string
	// found is false when some node along the path is defined by no tier at all,
	// so nothing beneath it can be defined either.
	found bool
}

// descendPath walks key's dotted path down the tier stack, one level per segment.
// tiers must be the stack for key's TOP-LEVEL segment (cascadeTiers).
func descendPath(tiers []cascadeTier, key string) pathDescent {
	parts := strings.Split(key, ".")
	prefix := parts[0]
	for _, part := range parts[1:] {
		defining := definingTiers(tiers)
		if len(defining) == 0 {
			return pathDescent{}
		}
		if _, isMap := asGenericMap(defining[0].value); !isMap {
			ancestor := defining[0]
			return pathDescent{ancestor: &ancestor, ancestorKey: prefix, found: true}
		}
		tiers = childTiers(mergeableTiers(tiers), part)
		prefix += "." + part
	}
	return pathDescent{tiers: tiers, found: true}
}

// keyedOriginLines is the FULL-STACK listing for one dotted key: one line per tier
// that defines it, highest precedence first, the winner marked (effective) and the
// rest (shadowed). It descends the path through the tier stack first, so an
// ancestor replaced by a higher tier reports that replacing tier rather than
// inventing a descendant. A map-valued key drills down per leaf, each leaf listing
// its own stack.
func keyedOriginLines(key string, tiers []cascadeTier, envOrigins map[string]string) []originLine {
	undefined := []originLine{{key: key, value: "null", origin: "(no tier defines this key)"}}
	descent := descendPath(tiers, key)
	switch {
	case !descent.found:
		return undefined
	case descent.ancestor != nil:
		// The requested descendant resolves to null; the replacing ancestor's tier
		// is the provenance to report.
		return []originLine{{key: key, value: "null",
			origin: descent.ancestor.stackOrigin(descent.ancestorKey, envOrigins) + "  (effective)"}}
	}
	lines := stackLines(key, descent.tiers, envOrigins)
	if len(lines) == 0 {
		return undefined
	}
	return lines
}

// stackLines emits the per-tier listing for a node: one line per defining tier at
// a leaf, or the per-leaf drill-down when the winning tier is a map.
func stackLines(prefix string, tiers []cascadeTier, envOrigins map[string]string) []originLine {
	defining := definingTiers(tiers)
	if len(defining) == 0 {
		return nil
	}
	if _, isMap := asGenericMap(defining[0].value); !isMap {
		out := make([]originLine, 0, len(defining))
		for i, t := range defining {
			marker := "  (shadowed)"
			if i == 0 {
				marker = "  (effective)"
			}
			out = append(out, originLine{
				key: prefix,
				// The keyed listing renders a list/map leaf in compact FLOW style
				// ([a, b]) — one stack line per tier stays readable only if the value
				// is one token-ish run, which the winner-only listing does not need.
				value:  renderCompactValue(t.value),
				origin: t.stackOrigin(prefix, envOrigins) + marker,
			})
		}
		return out
	}
	mergeable := mergeableTiers(tiers)
	var out []originLine
	for _, k := range childKeys(mergeable) {
		out = append(out, stackLines(prefix+"."+k, childTiers(mergeable, k), envOrigins)...)
	}
	return out
}

// envOrigin returns the `$VARIABLE` that supplied an environment leaf, or "" when
// no variable is recorded for it (unreachable in practice — the overlay and the
// origin map are written together). Origins are stored at registry-row
// granularity, so leaves beneath a map-valued row use the longest matching
// dotted-key prefix (agent.profiles.review.provider → $FAB_AGENT_PROFILES).
func envOrigin(key string, origins map[string]string) string {
	bestKey, bestVar := "", ""
	for registryKey, variable := range origins {
		if key == registryKey || strings.HasPrefix(key, registryKey+".") {
			if len(registryKey) > len(bestKey) {
				bestKey, bestVar = registryKey, variable
			}
		}
	}
	if bestVar == "" {
		return ""
	}
	return "$" + bestVar
}

// asGenericMap coerces a decoded YAML value to map[string]any when it is a
// mapping (handling both map[string]any and map[any]any).
func asGenericMap(v any) (map[string]any, bool) {
	switch m := v.(type) {
	case map[string]any:
		return m, true
	case map[any]any:
		out := make(map[string]any, len(m))
		for k, val := range m {
			ks, ok := k.(string)
			if !ok {
				return nil, false
			}
			out[ks] = val
		}
		return out, true
	default:
		return nil, false
	}
}

func unionKeys(maps ...map[string]any) []string {
	seen := map[string]bool{}
	var keys []string
	for _, m := range maps {
		for k := range m {
			if !seen[k] {
				seen[k] = true
				keys = append(keys, k)
			}
		}
	}
	return keys
}

// renderScalar renders a leaf value (scalar or list) compactly for the origin
// listing. Lists render as YAML flow ([a, b]); scalars via fmt.
func renderScalar(v any) string {
	if v == nil {
		return "null"
	}
	switch v.(type) {
	case []any, map[string]any, map[any]any:
		data, err := yaml.Marshal(v)
		if err == nil {
			return strings.TrimSpace(strings.ReplaceAll(string(data), "\n", " "))
		}
	}
	return fmt.Sprintf("%v", v)
}

func configSetCmd() *cobra.Command {
	var system bool
	cmd := &cobra.Command{
		Use:   "set <key> <value>",
		Short: "Set one config override without rewriting comments",
		Long: "Accepts only known scalar leaf keys and single-line, comment-free YAML scalar values " +
			"(string, bool, int, or float), then surgically writes only that path through the " +
			"comment-preserving config engine. Collection-valued keys and values require a manual " +
			"config-file edit. An EMPTY value is refused: an empty leaf falls through to the next " +
			"tier and can never be effective — `fab config unset` is the verb for removing an " +
			"override. When a higher-precedence tier already defines the key, the write succeeds " +
			"(exit 0) with a warning naming the tier that wins. Use --system for " +
			"~/.fab-kit/config.yaml; project-scoped keys are refused there.",
		Example: `  fab config set agent.workers codex
  fab config set dispatch.column_width 42
  fab config set agent.session codex --system`,
		Args: cobra.ExactArgs(2),
		RunE: func(cmd *cobra.Command, args []string) error {
			key, rawValue := args[0], args[1]
			if isEmptySetValue(rawValue) {
				return fmt.Errorf("refusing to set %q to an empty value: an empty leaf (null, \"\", [], {}) "+
					"falls through to the next config tier and can never be effective — "+
					"run `fab config unset %s` to remove the override instead", key, key)
			}
			path, err := configMutationPath(system)
			if err != nil {
				return err
			}
			var result configupgrade.Result
			if system {
				result, err = configupgrade.SetSystem(path, key, rawValue)
			} else {
				result, err = configupgrade.Set(path, key, rawValue, version)
			}
			if err != nil {
				return err
			}
			if result.Changed {
				fmt.Fprintf(cmd.OutOrStdout(), "Set %s in %s\n", key, path)
			} else {
				fmt.Fprintf(cmd.OutOrStdout(), "%s already has that value in %s\n", key, path)
			}
			for _, line := range result.Report {
				fmt.Fprintf(cmd.OutOrStdout(), "  - %s\n", line)
			}
			warnIfShadowed(cmd, key, mutationTier(system))
			return nil
		},
	}
	cmd.Flags().BoolVar(&system, "system", false, "Write ~/.fab-kit/config.yaml instead of the project config")
	return cmd
}

// isEmptySetValue reports whether a `set` value is EMPTY under the read model's
// one emptiness rule. The test is on the PARSED value, not on the argv string: a
// quoted-empty YAML form (an empty double- or single-quoted scalar) and an explicit
// null reach the file as a leaf empty-skip can never honor, like a blank one — a raw
// string test would accept them and write an inert override. A value that does not
// parse is NOT judged here; the writer's own parse error is the better message.
func isEmptySetValue(raw string) bool {
	if strings.TrimSpace(raw) == "" {
		return true // not every blank argv string reaches the parser as a value
	}
	value, err := config.ParseYAMLValue(raw)
	if err != nil {
		return false
	}
	return config.IsEmptyValue(value)
}

// mutationTier names the cascade tier a mutation targets.
func mutationTier(system bool) string {
	if system {
		return tierSystem
	}
	return tierProject
}

// warnIfShadowed prints a `fab: warning:` on stderr when a tier ABOVE the write
// target already defines the key, so a write that cannot take effect says so
// instead of succeeding silently. The write itself is valid, so the exit code
// stays 0. Fail-open: an unresolvable read model simply prints nothing.
func warnIfShadowed(cmd *cobra.Command, key, target string) {
	winner, envOrigins, ok := effectiveTierFor(key)
	if !ok || tierRank(winner.kind) >= tierRank(target) {
		return
	}
	fmt.Fprintf(cmd.ErrOrStderr(), "fab: warning: %s is shadowed by %s — the written value is not in effect\n",
		key, winner.stackOrigin(key, envOrigins))
}

// liveTierNotice reports where a key IS live when an unset found nothing to
// remove in its own target, with the command that would remove it. It returns ""
// when nothing above the built-in default defines the key, or when the target
// tier is the one that does (which unset already handled).
func liveTierNotice(key, target string) string {
	winner, envOrigins, ok := effectiveTierFor(key)
	if !ok || winner.kind == tierDefault || winner.kind == target {
		return ""
	}
	origin := winner.stackOrigin(key, envOrigins)
	if winner.kind == tierEnv {
		return fmt.Sprintf("  live in %s — an environment variable, which unset cannot remove; unset it in your shell", origin)
	}
	remedy := "fab config unset " + key
	if winner.kind == tierSystem {
		remedy += " --system"
	}
	return fmt.Sprintf("  live in %s — use: %s", origin, remedy)
}

// tierRank orders the tiers by precedence, highest first (env 0 … default 3), so
// "is some tier higher than the one I wrote?" is a comparison.
func tierRank(kind string) int {
	switch kind {
	case tierEnv:
		return 0
	case tierSystem:
		return 1
	case tierProject:
		return 2
	default:
		return 3
	}
}

// effectiveTierFor resolves which tier supplies a dotted key's effective value,
// descending the path exactly as the merge does (a replacing ancestor supplies its
// descendants) through the same shared descent the keyed --origin listing uses.
// Fail-open in every direction — an unresolvable repo, an unreadable layer, or a
// key no tier defines all report ok=false, because these notices must never fail a
// mutation that already succeeded.
func effectiveTierFor(key string) (cascadeTier, map[string]string, bool) {
	fabRoot, err := resolve.FabRoot()
	if err != nil {
		return cascadeTier{}, nil, false
	}
	projectPath := filepath.Join(fabRoot, "project", "config.yaml")
	layers, err := config.LoadLayers(projectPath)
	if err != nil {
		return cascadeTier{}, nil, false
	}
	defaults, err := readModelDefaults(layers)
	if err != nil {
		return cascadeTier{}, nil, false
	}
	descent := descendPath(cascadeTiers(defaults, layers, topLevelKey(key)), key)
	switch {
	case !descent.found:
		return cascadeTier{}, nil, false
	case descent.ancestor != nil:
		return *descent.ancestor, layers.EnvOrigins, true // a replacing ancestor supplies the value
	}
	defining := definingTiers(descent.tiers)
	if len(defining) == 0 {
		return cascadeTier{}, nil, false
	}
	return defining[0], layers.EnvOrigins, true
}

func configUnsetCmd() *cobra.Command {
	var system bool
	cmd := &cobra.Command{
		Use:   "unset <key>",
		Short: "Remove one override and restore inheritance",
		Long: "Removes one known live override through the comment-preserving config engine, " +
			"restoring the value the tier below supplies. An absent key is an exit-zero " +
			"no-op whose notice names the tier where the key IS live — another file, or the " +
			"environment variable unset cannot remove. Use --system to target " +
			"~/.fab-kit/config.yaml.",
		Example: `  fab config unset agent.workers
  fab config unset agent.session --system`,
		Args: cobra.ExactArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			key := args[0]
			path, err := configMutationPath(system)
			if err != nil {
				return err
			}
			var result configupgrade.Result
			if system {
				result, err = configupgrade.UnsetSystem(path, key)
			} else {
				result, err = configupgrade.Unset(path, key, version)
			}
			if err != nil {
				return err
			}
			if result.Changed {
				fmt.Fprintf(cmd.OutOrStdout(), "Unset %s in %s\n", key, path)
			} else {
				if len(result.Report) == 0 {
					fmt.Fprintf(cmd.OutOrStdout(), "%s is not set; nothing to unset\n", key)
				}
			}
			for _, line := range result.Report {
				if result.Changed {
					fmt.Fprintf(cmd.OutOrStdout(), "  - %s\n", line)
				} else {
					fmt.Fprintln(cmd.OutOrStdout(), line)
				}
			}
			if !result.Changed {
				if notice := liveTierNotice(key, mutationTier(system)); notice != "" {
					fmt.Fprintln(cmd.OutOrStdout(), notice)
				}
			}
			return nil
		},
	}
	cmd.Flags().BoolVar(&system, "system", false, "Write ~/.fab-kit/config.yaml instead of the project config")
	return cmd
}

func configMutationPath(system bool) (string, error) {
	if system {
		home, err := os.UserHomeDir()
		if err != nil {
			return "", fmt.Errorf("cannot resolve home directory for the system config: %w", err)
		}
		return filepath.Join(home, ".fab-kit", "config.yaml"), nil
	}
	fabRoot, err := resolve.FabRoot()
	if err != nil {
		return "", err
	}
	return filepath.Join(fabRoot, "project", "config.yaml"), nil
}

// configInitCmd implements `fab config init` in two mutually-exclusive modes:
//   - --system: writes a ~/.fab-kit/config.yaml scaffold of the system-overridable
//     fields (all commented).
//   - --project: generates a fresh fab/project/config.yaml from the registry — the
//     A-class identity fields (--name/--description/--source-path/--test-path)
//     written live above the managed fence. This is the shell-out target `fab init`
//     (fab-kit) calls to bootstrap a project config; the scaffold config.yaml is
//     retired.
//
// Bare `fab config init` selects project mode. Passing both explicit modes is an
// error. Both modes refuse to overwrite an existing target file unless --force is
// given; --print renders the exact file to stdout without writing anything and is
// never blocked by an existing file.
func configInitCmd() *cobra.Command {
	var system, project, printOnly, force bool
	var name, description string
	var sourcePaths, testPaths []string
	cmd := &cobra.Command{
		Use:   "init [--system]",
		Short: "Generate a project config, or a system scaffold with --system",
		Long: "With --system, writes a ~/.fab-kit/config.yaml scaffold containing ONLY " +
			"the fields overridable at the system layer (scope system/both — today " +
			"the agent: block and providers), all commented, generated from the same " +
			"per-field metadata table as `fab config explain` so it cannot drift. " +
			"With --project, generates a fresh fab/project/config.yaml from the registry: " +
			"the A-class identity fields (--name, --description, --source-path, --test-path) " +
			"written live, followed by the managed reference fence — no agent: key is " +
			"pinned (presence=intent). Both modes refuse to overwrite an existing file " +
			"unless --force is given. --print renders the exact file init would write " +
			"to stdout without writing anything — it is never blocked by an existing " +
			"file, and --print + --force is a pure preview (zero writes). " +
			"Bare `fab config init` selects project mode; --project remains " +
			"available for compatibility.",
		Example: `  # Write the ~/.fab-kit/config.yaml system-layer scaffold
  fab config init --system

  # Generate fab/project/config.yaml from the field registry
  fab config init --project --name my-app --description "My application"

  # Seed source/test paths (repeatable flags)
  fab config init --project --name my-app --source-path src/ --test-path '**/*_test.go'`,
		Args: cobra.NoArgs,
		RunE: func(cmd *cobra.Command, _ []string) error {
			switch {
			case system && project:
				return fmt.Errorf("`fab config init` takes --system OR --project, not both")
			case system:
				return runConfigInitSystem(cmd, printOnly, force)
			default:
				return runConfigInitProject(cmd, configupgrade.InitSeed{
					Name:        name,
					Description: description,
					SourcePaths: sourcePaths,
					TestPaths:   testPaths,
				}, printOnly, force)
			}
		},
	}
	cmd.Flags().BoolVar(&system, "system", false, "Write the ~/.fab-kit/config.yaml system-layer scaffold")
	cmd.Flags().BoolVar(&project, "project", false, "Generate fab/project/config.yaml from the registry (identity fields + fence)")
	cmd.Flags().StringVar(&name, "name", "", "Project name (--project seed)")
	cmd.Flags().StringVar(&description, "description", "", "Project description (--project seed)")
	cmd.Flags().StringArrayVar(&sourcePaths, "source-path", nil, "Source path (--project seed; repeatable)")
	cmd.Flags().StringArrayVar(&testPaths, "test-path", nil, "Test path pattern (--project seed; repeatable)")
	cmd.Flags().BoolVar(&printOnly, "print", false, "Print the exact file init would write to stdout without writing anything (never blocked by an existing file)")
	cmd.Flags().BoolVar(&force, "force", false, "Overwrite an existing target file (refused by default)")
	return cmd
}

// runConfigInitProject generates a fresh fab/project/config.yaml from the registry,
// refusing to overwrite an existing one unless force is set. With printOnly it
// writes the rendered content to stdout and touches nothing on disk (the existence
// check is skipped — a preview, not a write). Extracted so the
// generation/overwrite logic is testable.
func runConfigInitProject(cmd *cobra.Command, seed configupgrade.InitSeed, printOnly, force bool) error {
	fabRoot, err := resolve.FabRoot()
	if err != nil {
		return err
	}
	path := filepath.Join(fabRoot, "project", "config.yaml")
	if !printOnly && !force {
		if _, err := os.Stat(path); err == nil {
			return fmt.Errorf("refusing to overwrite existing project config %s "+
				"(the file is user-owned once created; edit it directly or run `fab config upgrade`)", path)
		} else if !os.IsNotExist(err) {
			return fmt.Errorf("checking for an existing project config %s: %w", path, err)
		}
	}

	content, err := configupgrade.RenderInitProject(seed, version)
	if err != nil {
		return err
	}
	if printOnly {
		fmt.Fprint(cmd.OutOrStdout(), content)
		return nil
	}
	dir := filepath.Dir(path)
	if err := os.MkdirAll(dir, 0o755); err != nil {
		return fmt.Errorf("creating %s: %w", dir, err)
	}
	if err := os.WriteFile(path, []byte(content), 0o644); err != nil {
		return fmt.Errorf("writing %s: %w", path, err)
	}
	fmt.Fprintf(cmd.OutOrStdout(), "Wrote project config to %s\n", path)
	return nil
}

// runConfigInitSystem writes the system-layer scaffold, refusing to overwrite an
// existing file unless force is set. With printOnly it writes the rendered
// scaffold to stdout and touches nothing on disk. Extracted so the
// overwrite/write logic is testable.
func runConfigInitSystem(cmd *cobra.Command, printOnly, force bool) error {
	home, err := os.UserHomeDir()
	if err != nil {
		return fmt.Errorf("cannot resolve home directory for the system config: %w", err)
	}
	dir := filepath.Join(home, ".fab-kit")
	path := filepath.Join(dir, "config.yaml")

	if !printOnly && !force {
		if _, err := os.Stat(path); err == nil {
			return fmt.Errorf("refusing to overwrite existing system config %s (it is user-owned once created; edit it directly or remove it first)", path)
		} else if !os.IsNotExist(err) {
			return fmt.Errorf("checking for an existing system config %s: %w", path, err)
		}
	}

	scaffold, err := renderSystemScaffold()
	if err != nil {
		return err
	}
	if printOnly {
		fmt.Fprint(cmd.OutOrStdout(), scaffold)
		return nil
	}
	if err := os.MkdirAll(dir, 0o755); err != nil {
		return fmt.Errorf("creating %s: %w", dir, err)
	}
	if err := os.WriteFile(path, []byte(scaffold), 0o644); err != nil {
		return fmt.Errorf("writing %s: %w", path, err)
	}
	fmt.Fprintf(cmd.OutOrStdout(), "Wrote system config scaffold to %s\n", path)
	return nil
}

// renderSystemScaffold generates the system-layer scaffold by walking the field
// registry and emitting the commented ShortSegment of each system-overridable
// field (scope system/both — the agent: block, providers, and dispatch). The
// ShortSegments are the file-bound short form of the segments `fab config
// explain` prints (260809-wll4 R6/R7: short description + scope tag +
// machine-wide/explain pointers), so the scaffold cannot drift from the schema
// and carries the prose diet, not the essays. A live (uncommented) ShortSegment
// line (e.g. providers' live claude interactive_command line) is
// comment-normalized so the whole scaffold ships inert — nothing takes effect
// until the user uncomments it.
func renderSystemScaffold() (string, error) {
	fields, err := configref.Fields()
	if err != nil {
		return "", err
	}
	var b strings.Builder
	b.WriteString(configupgrade.SystemScaffoldHeader)
	for _, f := range fields {
		if f.Segment == "" {
			continue // a field rendered inside another's block carries no segment
		}
		if f.Scope != configscope.ScopeSystem && f.Scope != configscope.ScopeBoth {
			continue // scope: project — never system-overridable
		}
		b.WriteString("\n\n")
		b.WriteString(configupgrade.CommentOutSegment(f.ShortSegment))
	}
	b.WriteString("\n")
	return b.String(), nil
}
