package main

import (
	"errors"
	"io"
	"testing"
)

// errWriter is an io.Writer whose every write fails, used to force an
// operational (I/O) error from a command's RunE.
type errWriter struct{}

func (errWriter) Write([]byte) (int, error) { return 0, errors.New("write failed") }

// TestRunExitCode pins the binary-wide exit-code convention (toolkit principle
// №4): 0 = success, 1 = operational failure, 2 = usage error. Usage errors are
// caught at parse/validation time before any RunE begins; operational errors
// originate from inside a RunE. Classification rides on execution phase, not on
// message-string matching — this table drives run() end-to-end through the live
// cobra tree so the flag-parse, arg-count, unknown-subcommand, and
// flags-group seams are all exercised. Mirrors pane_exitcode_test.go's shape.
func TestRunExitCode(t *testing.T) {
	cases := []struct {
		name string
		args []string
		want int
	}{
		// Usage errors → 2 (each of the four classes previously exited 1).
		{"unknown flag", []string{"score", "--nope"}, 2},
		{"arg-count violation", []string{"score"}, 2},
		{"unknown subcommand", []string{"nonsense"}, 2},
		{"flags-group conflict", []string{"resolve", "--status", "--folder"}, 2},

		// Operational failure → 1: valid syntax, the error surfaces from inside
		// RunE (a change that cannot exist by name).
		{"operational nonexistent change", []string{"resolve", "definitely-not-a-real-change-xyz"}, 1},

		// Success → 0.
		{"success (version)", []string{"--version"}, 0},
	}
	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			if got := run(tc.args, io.Discard, io.Discard); got != tc.want {
				t.Errorf("run(%v) = %d, want %d", tc.args, got, tc.want)
			}
		})
	}
}

// TestRunExitCodeAutoGeneratedRunE guards the auto-generated-command seam: cobra
// injects the `completion` subcommands (which use RunE) during Execute(), after
// the run-phase wrapper is installed. If those RunE handlers are not wrapped, an
// operational error they return (here, a stdout write failure) would leave the
// reached-run-phase flag false and be misclassified as a usage error (exit 2).
// It must be exit 1 — `completion bash` is a valid invocation whose error
// originates inside its RunE, so the run phase was genuinely reached.
func TestRunExitCodeAutoGeneratedRunE(t *testing.T) {
	if got := run([]string{"completion", "bash"}, errWriter{}, io.Discard); got != 1 {
		t.Errorf("run(completion bash) with failing stdout = %d, want 1 (operational)", got)
	}
}
