// Package configref generates the fully-commented reference config.yaml that
// `fab config reference` prints to stdout, and exposes the same schema as a
// machine-readable field table (`--json`). The reference is the single
// discoverability surface for the config.yaml schema — it documents BOTH the
// binary-consumed keys (modeled on internal/config.Config) and the
// skill-consumed keys (read by markdown skills, invisible to Go reflection).
//
// METADATA TABLE, NOT A PROSE TEMPLATE. The schema is modeled as an ordered
// per-field metadata table (the Fields registry): each entry carries the field's
// canonical default, one-line description, scope (project/system/both), advertise
// flag, renamed_from carry-forward, AND the rendered YAML segment (the commented
// block that documents the field in the reference). Both renderings — the
// commented YAML and the JSON dump — are generated by walking that one table:
// Render() concatenates each row's Segment in table order, RenderJSON() marshals
// each row's metadata. There is no second copy of the schema and no monolithic
// template to drift against the table. This is Change 1 of the config-upgrade
// effort; the scope/advertise/renamed_from metadata is consumed by the downstream
// cascade resolver, `fab config init --system`, and `fab config upgrade`
// (Changes 2-3). See docs/specs/config.md.
//
// GENERATED, NOT HAND-WRITTEN. Every default value that has a canonical Go
// constant is sourced from that constant, never copied — the three built-in
// providers' command grammars (agent.DefaultSessionCommand and the
// agent.DefaultCodex*/DefaultGemini* constants), the per-tier default profiles
// via agent.DefaultTier over agent.TierNames, and the pipeline stage names via
// agent.StageNames. The dynamic segments (providers, agent.tiers, stage_hooks)
// interpolate those same constants when the row is built, so the reference text
// carries no literal copy of any value.
//
// Canonical default vs. rendering example: a field's Default holds the CANONICAL
// built-in default (what the downstream cascade falls back to), not the value the
// reference happens to show as an example. source_paths/test_paths render an
// example (`- src/`, `- "**/*_test.go"`) but their binary default is empty, so
// their Default is nil — the example lives in the rendered Segment, not in the
// metadata.
//
// Empty-default convention: a field with no meaningful built-in default carries a
// nil Default (JSON `null`), NOT a typed empty (`[]`, `{}`, `""`). The nil is the
// uniform "no built-in default — the cascade falls back to absent" signal the
// downstream resolver (Change 2) consumes; distinguishing []string{} from nil
// would leak an implementation detail with no cascade meaning. A non-nil Default
// therefore always denotes a real built-in value (the three built-in providers'
// command grammars, the six tier profiles, dispatch.watchable's false) — which is
// why no provider's Default carries a model/effort fill: fab-kit ships none.
// dispatch.watchable is the convention's boundary case: for a BOOL there is no
// "absent" distinguishable from false, so false is a real built-in value rather
// than the typed-empty placeholder the convention forbids. See
// docs/specs/config.md § Default semantics.
//
// Render() output is BYTE-STABLE for a given binary version: the field table is
// fixed and ordered, the interpolated tier/stage lists come from the
// already-sorted agent.TierNames/agent.StageNames accessors, and no map is
// range-iterated during rendering. RenderJSON() is byte-stable for the same
// reasons (ordered table, deterministic marshalling).
package configref

import (
	"bytes"
	"encoding/json"
	"fmt"
	"strings"

	"github.com/sahil87/fab-kit/src/go/fab/internal/agent"
	"github.com/sahil87/fab-kit/src/go/fab/internal/configscope"
)

// Scope is a field's override visibility across the config cascade layers. The
// type and its three values are SINGLE-SOURCED in the leaf package
// internal/configscope (the config loader consumes the same source cycle-free);
// they are aliased here so the registry and the cascade share one definition. As
// of Change 2 (lpb5) the cascade resolver PRUNES a project-scoped field found in
// the system file (with a warning) and `fab config init --system` renders only
// system/both fields. See docs/specs/config.md § Scope taxonomy.
type Scope = configscope.Scope

const (
	// ScopeProject: overridable only in the project file (fab/project/config.yaml).
	// Semantics-class fields stay repo-reproducible for teammates/CI.
	ScopeProject = configscope.ScopeProject
	// ScopeSystem: overridable only in the system file (~/.fab-kit/config.yaml).
	// (No field is system-only today; the value exists for completeness.)
	ScopeSystem = configscope.ScopeSystem
	// ScopeBoth: overridable in either layer (preference-class fields).
	ScopeBoth = configscope.ScopeBoth
)

// validScope reports whether s is one of the three known scope values. Used by
// the registry lint (a scope outside this set is a fail-loud construction error).
// Delegates to the single-source leaf package.
func validScope(s Scope) bool {
	return configscope.Valid(s)
}

// scopeFor returns the scope for a registry row's dotted Key by collapsing it to
// its top-level YAML key (e.g. "project.name" → "project") and consulting the
// single-source leaf table. Every registry Key's top-level segment is a known
// scope key; an unknown one is a construction bug and is caught by the lint
// (scopeFor returns "" for unknown, which validScope rejects).
func scopeFor(key string) Scope {
	top := key
	if i := strings.IndexByte(key, '.'); i >= 0 {
		top = key[:i]
	}
	s, ok := configscope.ScopeFor(top)
	if !ok {
		return "" // lint rejects the empty scope, surfacing the missing taxonomy entry
	}
	return s
}

// Field is one row of the per-field metadata table — the single source the two
// renderings (commented YAML, JSON) are both generated from. It models the
// override UNIT (a meaningful override surface), which is coarser than a leaf
// key: map-valued fields (providers, agent.tiers, stage_hooks) are single rows
// with structured defaults, matching the downstream per-field deep-merge (maps
// merge per-key, lists replace, scalars replace).
type Field struct {
	// Key is the dotted path of the override surface (e.g. "agent.tiers",
	// "project.name", "true_impact_exclude"). It is the identity used by the
	// JSON dump and the JSON/YAML key-parity check.
	Key string
	// Default is the CANONICAL built-in default (typed), NOT a rendering example.
	// nil means "no built-in default" (the cascade falls back to empty/absent) —
	// e.g. source_paths/test_paths, whose shown values are examples only. A typed
	// empty is never used for "no default"; see the package-doc empty-default
	// convention.
	Default any
	// Description is the one-line summary of the field. Required (non-empty) —
	// the registry lint rejects an empty description. It feeds the JSON dump and
	// the future generated comment scaffold (Change 3). This is the short summary;
	// the long-form documentation prose lives in Segment (the rendered YAML block).
	Description string
	// Scope is the field's override visibility (project/system/both). Data-only
	// here; enforced in Change 2.
	Scope Scope
	// Advertise is the "C flag": whether Change 3's managed fence scaffolds this
	// field as a commented reference when it is not overridden. NO behavioral
	// consumer in this change — data + JSON exposure only.
	Advertise bool
	// RenamedFrom is the previous key path for mechanical rename carry-forward.
	// "" for every row today; the field serves FUTURE renames so they stop needing
	// hand-written migrations. Omitted from the JSON dump when empty.
	RenamedFrom string
	// InitSeed marks an A-class IDENTITY field written LIVE at `fab config init
	// --project` time from a seed value (the project's name/description/source/test
	// paths). These are the only fields the generator writes above the managed
	// fence on a fresh repo; every other field is fence territory from day one
	// (presence=intent — an init-pinned tier would be an accidental override that
	// stops tracking fab-kit's defaults). Consumed by the init generator; not part
	// of the JSON schema dump.
	InitSeed bool
	// Segment is the rendered commented-YAML block that documents this field in
	// the reference — the field's own lines (leading comment prose + the live or
	// commented key), WITHOUT a trailing newline or the inter-field blank line.
	// Render() concatenates the segments in table order (blank line between). For
	// the constant-backed fields (providers, agent.tiers, stage_hooks) the segment
	// is built by interpolating the same Go constants Default reads, so the
	// rendered text carries no literal copy of any value. Not exposed in the JSON
	// dump (it is the human-readable rendering of the same metadata).
	Segment string
}

// jsonField is the JSON projection of a Field: stable snake_case keys and
// renamed_from,omitempty (empty on every row today, so it is absent from the
// current dump). Segment is intentionally excluded — it is the YAML rendering of
// the same metadata, not part of the machine-readable schema. Kept separate from
// Field so the Go struct-field names stay idiomatic while the wire shape stays
// snake_case and stable for Changes 2-3.
type jsonField struct {
	Key         string `json:"key"`
	Default     any    `json:"default"`
	Description string `json:"description"`
	Scope       Scope  `json:"scope"`
	Advertise   bool   `json:"advertise"`
	RenamedFrom string `json:"renamed_from,omitempty"`
}

// tierStages is the human-readable referent grouping shown next to each tier in
// the reference comment. It restates the FIXED stage→tier mapping owned by
// internal/agent plus the non-stage referents (the /fab-proceed dispatches):
// default={intake advisory, create-intake dispatch}, operator={fab operator},
// doing={apply,review-pr}, review={review}, hydrate={hydrate},
// fast={ship, /fab-proceed prefix steps} — reference prose only, not a behavioral
// second source.
var tierStages = map[string]string{
	agent.TierDefault:  "intake (advisory), fab batch, fab agent, /fab-proceed create-intake",
	agent.TierOperator: "fab operator (coordinator session)",
	agent.TierDoing:    "apply, review-pr",
	agent.TierReview:   "review",
	agent.TierHydrate:  "hydrate",
	agent.TierFast:     "ship, /fab-proceed prefix steps",
}

// tierProfileDefault is the structured canonical default for one agent tier —
// what lands in the agent.tiers row's Default (and the JSON dump). Sourced from
// agent.DefaultTier; never a literal copy.
type tierProfileDefault struct {
	Provider string `json:"provider"`
	Model    string `json:"model"`
	Effort   string `json:"effort"`
}

// providerDefault is the structured canonical default for ONE built-in provider.
// Both command fields are `omitempty` because a built-in may legitimately carry
// only one (claude ships no dispatch_command — absent = native Agent-tool
// dispatch). There are deliberately NO model/effort keys: fab-kit's built-ins are
// GRAMMAR ONLY, and the registry's empty-default convention says a non-nil Default
// always denotes a real built-in value — emitting an empty model would assert a
// built-in fill that does not exist. Sourced from the agent command constants.
type providerDefault struct {
	SessionCommand  string `json:"session_command,omitempty"`
	DispatchCommand string `json:"dispatch_command,omitempty"`
}

// providerDefaults is the structured canonical default for the providers row: all
// three of fab-kit's built-in providers, sourced from the agent constants (never a
// literal copy). It mirrors internal/agent.defaultProviders — claude with a
// session command only, codex/gemini with both — so the JSON dump advertises
// exactly the set `agent.ResolveProvider` resolves with no config.
func providerDefaults() map[string]providerDefault {
	return map[string]providerDefault{
		agent.DefaultProviderName: {SessionCommand: agent.DefaultSessionCommand},
		"codex": {
			SessionCommand:  agent.DefaultCodexSessionCommand,
			DispatchCommand: agent.DefaultCodexDispatchCommand,
		},
		"gemini": {
			SessionCommand:  agent.DefaultGeminiSessionCommand,
			DispatchCommand: agent.DefaultGeminiDispatchCommand,
		},
	}
}

// tierRow is one resolved tier: its name, its fixed stage grouping (reference
// prose from tierStages), and its default {provider, model, effort} profile
// (from agent.DefaultTier). It is the single per-tier view both the agent.tiers
// Default (as tierProfileDefault) and the agent.tiers Segment are built from —
// one walk of agent.TierNames(), no duplicated loop.
type tierRow struct {
	Name    string
	Stages  string
	Profile tierProfileDefault
}

// tierRows returns the ordered per-tier view, one row per agent.TierNames()
// entry (sorted, so deterministic). It is the SINGLE source that both the
// agent.tiers Default and the agent.tiers rendered Segment consume — there is no
// second TierNames/DefaultTier loop. It fails loud on either tier-map drift: a
// tier agent.TierNames reports must have an agent.DefaultTier profile AND a
// tierStages grouping (the reference comment relies on both).
func tierRows() ([]tierRow, error) {
	names := agent.TierNames()
	rows := make([]tierRow, 0, len(names))
	for _, name := range names {
		p, ok := agent.DefaultTier(name)
		if !ok {
			return nil, fmt.Errorf("configref: tier %q from agent.TierNames has no agent.DefaultTier profile", name)
		}
		stages, ok := tierStages[name]
		if !ok {
			return nil, fmt.Errorf("configref: tier %q has no tierStages grouping (add one when adding a tier)", name)
		}
		rows = append(rows, tierRow{
			Name:    name,
			Stages:  stages,
			Profile: tierProfileDefault{Provider: p.Provider, Model: p.Model, Effort: p.Effort},
		})
	}
	return rows, nil
}

// tierProfileDefaults projects tierRows into the map keyed by tier name that the
// agent.tiers Field.Default carries (and the JSON dump emits).
func tierProfileDefaults(rows []tierRow) map[string]tierProfileDefault {
	out := make(map[string]tierProfileDefault, len(rows))
	for _, r := range rows {
		out[r.Name] = r.Profile
	}
	return out
}

// Fields returns the ordered per-field metadata table — the single source for
// both renderings. Slice order is the rendering order (deterministic, byte-stable).
// Each row carries its rendered YAML Segment; Render() walks the slice and
// concatenates the segments, RenderJSON() marshals each row's metadata.
//
// It fails loudly on a broken invariant rather than silently emitting a degraded
// reference:
//   - agent.DefaultTier must know every tier agent.TierNames reports, and every
//     such tier must have a tierStages grouping (via tierRows) — the constant-
//     sourced default set and the reference comment must both be complete.
//   - the registry lint (below) rejects any row with an empty Description or an
//     invalid Scope.
//
// Defaults are sourced from canonical Go constants where they exist
// (agent.DefaultSessionCommand, agent.DefaultTier). No literal here duplicates a
// Go constant; source_paths/test_paths carry a nil Default because their binary
// default is empty (their shown values are rendering examples only).
func Fields() ([]Field, error) {
	tiers, err := tierRows()
	if err != nil {
		return nil, err
	}

	fields := []Field{
		{
			Key:         "project.name",
			Default:     nil,
			Description: "Project display name. Read by skills for orientation and PR bodies.",
			Scope:       ScopeProject,
			Advertise:   false,
			InitSeed:    true,
			Segment: `# project — identity and PR metadata.
project:
  name: "My Project"                 # skills: orientation, PR bodies
  description: "One-line project description"  # skills: orientation, PR bodies
  # linear_workspace: myteam         # optional — enables Linear issue links in
                                     # PR bodies (https://linear.app/<slug>/issue/<ID>).
                                     # Omit or leave null for bare issue-ID text.`,
		},
		{
			Key:         "project.description",
			Default:     nil,
			Description: "One-line project description. Read by skills for orientation and PR bodies.",
			Scope:       ScopeProject,
			Advertise:   false,
			InitSeed:    true,
			// Rendered inline in the project.name Segment (project is one YAML
			// block); this row carries no Segment of its own.
		},
		{
			Key:         "project.linear_workspace",
			Default:     nil,
			Description: "Optional Linear workspace slug — enables Linear issue links in PR bodies. Omit/null for bare issue-ID text.",
			Scope:       ScopeProject,
			Advertise:   false,
			// Rendered inline in the project.name Segment (project is one YAML block).
		},
		{
			Key:         "source_paths",
			Default:     nil, // binary default empty; `- src/` is a rendering example.
			Description: "Directories containing implementation code (relative to repo root). Read by skills to scope apply context.",
			Scope:       ScopeProject,
			Advertise:   false,
			InitSeed:    true,
			Segment: `# source_paths — directories containing implementation code (relative to repo
# root). Read by skills to scope apply context.
source_paths:
  - src/`,
		},
		{
			Key:         "test_paths",
			Default:     nil, // binary default empty; the `- "**/*_test.go"` line is a rendering example.
			Description: "Glob/pathspec patterns identifying test files. Used by the /git-pr true-impact breakdown to attribute lines to tests vs. implementation. No kit default.",
			Scope:       ScopeProject,
			Advertise:   true,
			// InitSeed: written live at init ONLY when detection found a test
			// convention (the seed value); otherwise it stays fence-advertised.
			InitSeed: true,
			Segment: "# test_paths — glob/pathspec patterns identifying test files. Used by the\n" +
				"# /git-pr true-impact breakdown to attribute lines to tests vs. implementation\n" +
				"# (impl = total − tests). Language-specific — no kit default. Patterns are\n" +
				"# :(glob) magic pathspecs, so `**` matches across directories and `*` does\n" +
				"# NOT match `/`. Anchor to your language's test convention rather than a bare\n" +
				"# substring (a substring like `*test*` miscounts production code such as\n" +
				"# `attestation.go` or `latest.go`). When absent/empty, the breakdown collapses\n" +
				"# to a single total.\n" +
				"#\n" +
				"# Examples per stack (uncomment/adapt the line for yours):\n" +
				"#   - \"**/*_test.go\"                  # Go     — `_test.go` suffix\n" +
				"#   - \"**/test_*.py\"                  # Python (pytest) — `test_` prefix\n" +
				"#   - \"**/*.spec.ts\"                  # JS/TS  (Jest/Vitest) — `.spec` infix\n" +
				"#   - \"**/*.test.ts\"                  # JS/TS  — `.test` infix\n" +
				"#   - \"**/src/test/**\"               # Java/Kotlin (Maven/Gradle) — test source root\n" +
				"test_paths:\n" +
				"  - \"**/*_test.go\"                   # example (Go — `_test.go` suffix)",
		},
		{
			Key:         "true_impact_exclude",
			Default:     nil,
			Description: "Pathspec exclusions used by /git-pr to compute the true-impact line counts (excluding noise directories). Optional — when absent/empty the impact block is omitted.",
			Scope:       ScopeProject,
			Advertise:   true,
			Segment: `# true_impact_exclude — pathspec exclusions used by /git-pr to compute the "true
# impact" line counts in the PR body (excluding noise directories). Optional —
# when absent or empty, the impact block is omitted.
true_impact_exclude:
  - fab/
  - docs/`,
		},
		{
			Key:         "checklist.extra_categories",
			Default:     nil,
			Description: "Project-specific quality categories appended to the built-in plan.md ## Acceptance categories. Each becomes an extra subsection under plan.md ## Acceptance.",
			Scope:       ScopeProject,
			Advertise:   true,
			Segment: `# checklist.extra_categories — project-specific quality categories appended to
# the built-in plan.md ## Acceptance categories (functional_completeness,
# behavioral_correctness, scenario_coverage, edge_cases, code_quality, security).
# Each becomes an extra subsection under plan.md ## Acceptance.
checklist:
  extra_categories: []               # example: [performance, accessibility, i18n]`,
		},
		{
			Key:         "consolidate.detectors",
			Default:     nil,
			Description: "Duplicate-detection commands `/fab-dedupe` runs to seed its sweep. Each entry is a shell command template; `{paths}` and `{out}` are substituted at run time as shell-quoted values. Missing binaries are skipped silently.",
			Scope:       ScopeProject,
			Advertise:   true,
			Segment: `# consolidate.detectors — duplicate-detection commands /fab-dedupe runs to seed
# its sweep. Each entry is a shell command template; {paths} (the resolved scope)
# and {out} (a scratch dir) are substituted at run time as shell-quoted values,
# so paths containing spaces or shell metacharacters stay intact arguments.
# A detector whose binary is missing is skipped silently; a non-zero exit is
# treated as a finding, not an error. Detectors only SEED the sweep — the agent
# does the clustering.
# consolidate:
#   detectors:
#     - jscpd --reporters json --output {out} {paths}`,
		},
		{
			Key:         "providers",
			Default:     providerDefaults(),
			Description: "Named agent invocation grammars plus their optional default fill. Each provider MAY carry session_command (interactive session) and dispatch_command (headless stage task) — never merged, no fallback between them — plus optional model/effort fill values that supply the {model}/{effort} placeholders (precedence: invocation flag > tier field > provider fill > empty). fab-kit ships claude, codex, and gemini as grammar-only built-ins (no fill). Provider names are opaque, user-chosen strings.",
			Scope:       ScopeBoth,
			Advertise:   true,
			Segment:     providersSegment(),
		},
		{
			Key:         "agent.tiers",
			Default:     tierProfileDefaults(tiers),
			Description: "Per-stage model override. A tier is a named {provider, model, effort} profile; the stage→tier mapping is fixed and fab-owned. Override only what each tier means; omitted fields inherit the default tier then the built-in.",
			Scope:       ScopeBoth,
			Advertise:   true,
			Segment:     agentTiersSegment(tiers),
		},
		{
			Key: "dispatch.watchable",
			// false IS the canonical built-in default (a real value, not "no
			// default"), so it is carried typed rather than as nil: the cascade
			// bottoms out at false and the JSON dump must advertise that.
			Default:     false,
			Description: "Watchable-pane opt-in. When true AND the orchestrator sits inside tmux, a session_command-only provider (e.g. the built-in claude) becomes CLI-dispatch-eligible, so its stages run in a watchable tmux pane; outside tmux they stay on native Agent-tool dispatch. A provider's own dispatch_command always wins. Scope both — settable once machine-wide. Default false.",
			Scope:       ScopeBoth,
			Advertise:   true,
			Segment:     dispatchSegment(),
		},
		{
			Key:         "stage_hooks",
			Default:     nil,
			Description: "Optional per-stage pre/post shell commands honored by fab status start/finish. Each runs as sh -c from the repo root; a failing pre hook blocks start. Not seeded by the scaffold — add by hand.",
			Scope:       ScopeProject,
			Advertise:   true,
			Segment:     stageHooksSegment(),
		},
		{
			Key:         "branch_prefix",
			Default:     nil,
			Description: "Optional prefix applied by fab batch switch when creating worktree branches (branch name = {branch_prefix}{folder_name}). Empty when absent.",
			Scope:       ScopeProject,
			Advertise:   true,
			Segment: "# branch_prefix — optional prefix applied by `fab batch switch` when creating\n" +
				"# worktree branches (branch name = `{branch_prefix}{folder_name}`). Empty when\n" +
				"# absent.\n" +
				`# branch_prefix: ""`,
		},
	}

	if err := lintFields(fields); err != nil {
		return nil, err
	}
	return fields, nil
}

// referenceHeader is the fixed preamble of the reference — the file-level banner
// that precedes the first field segment. It is not a field row (it documents no
// single key); Render() emits it, then the field segments in table order.
const referenceHeader = `# Full reference of all available options: fab config reference
#
# This is the canonical, generated reference for fab/project/config.yaml. Every
# key below is documented — baseline keys appear live with example values;
# optional override blocks (agent.tiers, stage_hooks, branch_prefix) are shown
# commented-out with fab-kit's built-in defaults. Uncomment a block to opt in.
# Values here are examples/defaults, not your project's settings.`

// providersSegment renders the providers block. Every command string is
// interpolated from its canonical agent constant (no literal copy):
// agent.DefaultSessionCommand for claude, and the four
// agent.DefaultCodex*/DefaultGemini* constants for the other two built-ins.
//
// Presentation (260805-j3cm): all three providers are BUILT-IN, so codex/gemini
// are rendered as commented reference-style defaults — the same presentation every
// other non-overridden default uses — not as uncomment-to-opt-in blocks. The
// commented form still registers no project override (presence=intent holds for
// BEHAVIOR: a built-in provider is inert until a tier or flag names it), and
// whole-block uncommenting still yields valid YAML because all per-provider prose
// stays above the `providers:` key.
//
// This segment carries the registry's only DELIBERATELY-COMMENTED content lines —
// claude's indented `# dispatch_command:` and the `# codex:` / `# gemini:` blocks.
// configupgrade.CommentOutSegment prefixes those like any live line (its column-0
// rule), so in a rendered fence every marker lands at column 0 and the "strip the
// leading '# ' from every line of a block" instruction below restores this text
// byte-exactly — with those lines still commented at their original indent.
func providersSegment() string {
	return "# providers — named agent invocation grammars plus their optional default fill.\n" +
		"# Each provider MAY carry two command fields (they are NOT merged — session and\n" +
		"# dispatch are different invocations of the same binary):\n" +
		"#   session_command  — opens an interactive agent SESSION (fab operator /\n" +
		"#                       fab batch / fab agent). {model}/{effort} placeholders are\n" +
		"#                       substituted from the resolved tier profile, or from the\n" +
		"#                       --model/--effort flags on `fab agent --provider <name>`\n" +
		"#                       (which bypasses tier resolution); the built-in commands\n" +
		"#                       below are all templated this way. A command carrying\n" +
		"#                       NO placeholder instead gets --model/--effort appended.\n" +
		"#   dispatch_command — runs ONE headless stage task via fab dispatch. ABSENT →\n" +
		"#                      native Agent-tool dispatch (the default). There is NO\n" +
		"#                      fallback from dispatch_command to session_command. fab\n" +
		"#                      dispatch pipes the stage prompt to the command's STDIN.\n" +
		"# and two optional fill fields that supply those placeholders by default:\n" +
		"#   model / effort   — this provider's DEFAULT FILL. Position in the precedence:\n" +
		"#                      invocation flag > explicit tier field > provider fill >\n" +
		"#                      empty (empty drops the placeholder's token, so the CLI's\n" +
		"#                      own default applies). Scope `both`, so a machine-wide fill\n" +
		"#                      is settable once in ~/.fab-kit/config.yaml.\n" +
		"# Provider names are opaque, user-chosen strings — fab NEVER infers a provider\n" +
		"# from a model string. The cutoff is by provider NAME, not by vendor: a tier that\n" +
		"# explicitly sets `provider:` to a name differing from the built-in tier's loses\n" +
		"# that tier's model/effort inheritance and fills its unset fields from THAT\n" +
		"# provider's own fill, then empty — even when the two names front the same vendor\n" +
		"# (a second claude entry under another name still loses the inheritance). Pin\n" +
		"# `model:` on the tier to be explicit.\n" +
		"#\n" +
		"# fab-kit ships THREE built-in providers — claude (the default), codex, and\n" +
		"# gemini — as GRAMMAR ONLY: the command templates are built into the binary, but\n" +
		"# no built-in carries a model/effort fill (non-claude model IDs rot at CLI\n" +
		"# cadence, so they belong in config, not in a release). Naming codex or gemini in\n" +
		"# a tier (or via `fab agent --provider` / `fab resolve-agent --provider`) resolves\n" +
		"# with NO providers: block at all; set providers.<name>.model to pin its fill.\n" +
		"# Every block below is shown commented because it merely restates a built-in\n" +
		"# default — except claude's session_command, shown live as the baseline example.\n" +
		"# Note codex/gemini DO carry a dispatch_command, so naming one flips that tier's\n" +
		"# stages from native Agent-tool dispatch to headless CLI dispatch; claude's\n" +
		"# dispatch_command is deliberately absent from the built-in (uncommenting the\n" +
		"# line below flips claude's stages the same way).\n" +
		"#\n" +
		"# Per-provider notes (kept out of the blocks below so uncommenting a whole block\n" +
		"# yields valid YAML — strip the leading '# ' from every line of a block):\n" +
		"#   claude.dispatch_command — claude -p reads the prompt from stdin; uncommenting\n" +
		"#     runs claude's stages as headless CLI processes instead of native sub-agents.\n" +
		"#   codex — codex exec reads the prompt from stdin. Set providers.codex.model to a\n" +
		"#     current model ID (e.g. gpt-5.3-codex) — fab ships none and does not validate it.\n" +
		"#   gemini — no {effort} (the gemini CLI has no reasoning-effort flag) and no -p:\n" +
		"#     gemini's -p takes prompt TEXT (appended after stdin), whereas fab dispatch\n" +
		"#     pipes the prompt to stdin, which gemini reads as the prompt in non-TTY mode.\n" +
		"providers:\n" +
		"  claude:\n" +
		"    session_command: '" + agent.DefaultSessionCommand + "'\n" +
		"    # dispatch_command: 'claude -p --dangerously-skip-permissions --model {model} --effort {effort}'\n" +
		"  # codex:\n" +
		"  #   session_command: '" + agent.DefaultCodexSessionCommand + "'\n" +
		"  #   dispatch_command: '" + agent.DefaultCodexDispatchCommand + "'\n" +
		"  #   model: gpt-5.3-codex                    # example fill — fab ships no model ID for codex\n" +
		"  #   effort: high\n" +
		"  # gemini:\n" +
		"  #   session_command: '" + agent.DefaultGeminiSessionCommand + "'\n" +
		"  #   dispatch_command: '" + agent.DefaultGeminiDispatchCommand + "'   # no {effort} flag; no -p (fab dispatch pipes the prompt to stdin)\n" +
		"  #   model: gemini-2.5-pro                   # example fill — fab ships no model ID for gemini"
}

// agentTiersSegment renders the agent.tiers block. The FIXED stage→tier mapping
// comment and the built-in default profiles are both emitted from the single
// tierRows() walk — the same rows the agent.tiers Default is built from — so no
// tier value is a literal copy and the loop is not duplicated.
func agentTiersSegment(tiers []tierRow) string {
	var b strings.Builder
	b.WriteString("# agent.tiers — per-stage model override. A \"tier\" is a named\n")
	b.WriteString("# {provider, model, effort} profile (the invocation command lives on the provider,\n")
	b.WriteString("# above — NOT on the tier). fab-kit owns the FIXED, non-overridable stage→tier\n")
	b.WriteString("# mapping below; you override only WHAT EACH TIER MEANS. Omit any tier (or the\n")
	b.WriteString("# whole tiers: block) to use fab-kit's built-in default. An omitted field within a\n")
	b.WriteString("# tier inherits the project's `default` tier, then fab-kit's built-in; an empty\n")
	b.WriteString("# model means \"inherit the session model\". Resolved per stage by\n")
	b.WriteString("# `fab resolve-agent <stage>` at sub-agent dispatch time. Values pass through\n")
	b.WriteString("# verbatim — fab does no provider validation. See docs/specs/stage-models.md.\n")
	b.WriteString("#\n")
	b.WriteString("# FIXED stage→tier mapping (fab-owned, NOT overridable — shown for reference):\n")
	for _, t := range tiers {
		fmt.Fprintf(&b, "#   %-9s %s\n", t.Name, t.Stages)
	}
	b.WriteString("#\n")
	b.WriteString("# fab-kit's built-in default profiles (today):\n")
	b.WriteString("agent:\n")
	b.WriteString("  tiers:\n")
	for _, t := range tiers {
		fmt.Fprintf(&b, "    %-9s { provider: %s, model: %s, effort: %s }\n",
			t.Name+":", t.Profile.Provider, t.Profile.Model, t.Profile.Effort)
	}
	// Trim the trailing newline: Render() re-inserts the inter-field separator.
	return strings.TrimRight(b.String(), "\n")
}

// dispatchSegment renders the dispatch.watchable block — the watchable-pane
// opt-in. Prose only (no constant to interpolate): the default is the Go zero
// value, so there is no literal copy to drift.
func dispatchSegment() string {
	return "# dispatch.watchable — opt in to WATCHABLE-PANE dispatch for providers that\n" +
		"# carry only a session_command (e.g. the built-in claude). When true, TMUX\n" +
		"# PRESENCE decides the adapter: inside tmux (`$TMUX` set) `fab resolve-agent`\n" +
		"# emits a `dispatch=` line for such a provider, so the stage dispatches into a\n" +
		"# tmux pane you can watch and steer; outside tmux the line is omitted and the\n" +
		"# stage stays on native Agent-tool dispatch. HEADLESS CLI dispatch is never\n" +
		"# reached this way — it stays gated on a real dispatch_command.\n" +
		"# A provider's own dispatch_command always WINS (unchanged); watchable only\n" +
		"# ADDS eligibility for providers that have none — so it replaces uncommenting\n" +
		"# claude's dispatch_command, which would also flip every OUT-of-tmux dispatch\n" +
		"# to headless CLI. Scope `both`, so it is settable once machine-wide in\n" +
		"# ~/.fab-kit/config.yaml. Default false (byte-stable current behavior).\n" +
		"# dispatch:\n" +
		"#   watchable: false"
}

// stageHooksSegment renders the stage_hooks block. The valid stage-keys list is
// interpolated from agent.StageNames() (sorted, deterministic) — no literal copy
// of the stage set.
func stageHooksSegment() string {
	return "# stage_hooks — optional per-stage pre/post shell commands honored by\n" +
		"# `fab status start` / `fab status finish`. Each command runs as `sh -c` from\n" +
		"# the repo root. A failing `pre` hook blocks `fab status start`; a `post` hook\n" +
		"# runs after `finish` saves. Not seeded by the scaffold — add by hand.\n" +
		"# Valid stage keys: " + strings.Join(agent.StageNames(), ", ") + ".\n" +
		"# stage_hooks:\n" +
		"#   apply:\n" +
		"#     pre: ./scripts/check-clean-tree.sh\n" +
		"#     post: make test"
}

// lintFields is the fail-loud registry validation: every row must have a
// non-empty Description and a valid Scope. A violation is a construction bug
// (a new row added without metadata), caught here rather than shipped as a
// degraded reference — the same discipline as the tier-profile invariant above.
func lintFields(fields []Field) error {
	for _, f := range fields {
		if f.Description == "" {
			return fmt.Errorf("configref: field %q has an empty description (every registry row must document its field)", f.Key)
		}
		if !validScope(f.Scope) {
			return fmt.Errorf("configref: field %q has invalid scope %q (want one of project/system/both)", f.Key, f.Scope)
		}
		// Single-source guard: the row's Scope MUST equal the leaf-package
		// taxonomy for the field's top-level key. The loader (internal/config)
		// prunes the system layer on that same leaf table, so a divergence here
		// would silently split the scope taxonomy in two. Fail loud at
		// construction instead. See internal/configscope.
		if want := scopeFor(f.Key); f.Scope != want {
			return fmt.Errorf("configref: field %q has scope %q but internal/configscope says %q — the scope taxonomy is single-sourced in configscope; fix it there", f.Key, f.Scope, want)
		}
	}
	return nil
}

// FieldKeys returns the dotted key paths of every registry row, in table order.
// Used by the JSON/YAML key-parity guard and any external consumer needing the
// documented key set.
func FieldKeys() ([]string, error) {
	fields, err := Fields()
	if err != nil {
		return nil, err
	}
	keys := make([]string, len(fields))
	for i, f := range fields {
		keys[i] = f.Key
	}
	return keys, nil
}

// InitSeedKeys returns the dotted keys of the A-class IDENTITY fields written live
// at `fab config init --project` time (InitSeed rows), in table order. These are
// the only fields the init generator emits above the managed fence; everything
// else is fence territory from day one. Used by the init generator and its tests.
func InitSeedKeys() ([]string, error) {
	fields, err := Fields()
	if err != nil {
		return nil, err
	}
	var keys []string
	for _, f := range fields {
		if f.InitSeed {
			keys = append(keys, f.Key)
		}
	}
	return keys, nil
}

// Render returns the fully-commented reference config.yaml, generated by walking
// the field registry: the fixed header followed by each row's rendered Segment in
// table order, one blank line between blocks. The output is byte-stable for a
// given binary version and is what `fab config reference` prints to stdout. It
// returns an error rather than emitting partial/degraded output if an invariant
// breaks (Fields surfaces the tier-map drift and the registry lint), so a future
// edit that breaks an invariant fails loudly instead of silently shipping a
// malformed reference.
//
// The emitted text is contract-equivalent to the pre-metadata-table renderer
// (same key coverage, live/commented split, and every documented-semantics prose
// block the tests assert verbatim) — the restructure changed the SOURCE of the
// reference (prose template → metadata table walked here), not its output
// contract.
func Render() (string, error) {
	fields, err := Fields()
	if err != nil {
		return "", err
	}
	var b strings.Builder
	b.WriteString(referenceHeader)
	for _, f := range fields {
		if f.Segment == "" {
			// A field rendered inside another field's block (e.g. project.description
			// / project.linear_workspace live in the project.name segment) carries no
			// segment of its own — skip it in the walk.
			continue
		}
		b.WriteString("\n\n")
		b.WriteString(f.Segment)
	}
	b.WriteString("\n")
	return b.String(), nil
}

// RenderJSON returns the field registry as a machine-readable JSON array — the
// tooling surface Changes 2-3 and external tools consume. It is a flat array in
// table (rendering) order, each element a per-field object
// {key, default, description, scope, advertise, renamed_from(omitempty)}.
// Deterministic and byte-stable like Render(): the table is ordered and the
// marshalling is stable. Two-space indented with a trailing newline. Segment is
// excluded — it is the YAML rendering, not part of the machine-readable schema.
func RenderJSON() (string, error) {
	fields, err := Fields()
	if err != nil {
		return "", err
	}
	view := make([]jsonField, len(fields))
	for i, f := range fields {
		view[i] = jsonField{
			Key:         f.Key,
			Default:     f.Default,
			Description: f.Description,
			Scope:       f.Scope,
			Advertise:   f.Advertise,
			RenamedFrom: f.RenamedFrom,
		}
	}
	var buf bytes.Buffer
	enc := json.NewEncoder(&buf)
	enc.SetIndent("", "  ")
	enc.SetEscapeHTML(false)
	if err := enc.Encode(view); err != nil {
		return "", fmt.Errorf("configref: marshalling reference JSON: %w", err)
	}
	return buf.String(), nil
}
