// Package configref generates the fully-commented reference config.yaml that
// `fab config explain` prints to stdout, and exposes the same schema as a
// machine-readable field table (`--json`). The reference is the single
// discoverability surface for the config.yaml schema — it documents BOTH the
// binary-consumed keys (modeled on internal/config.Config) and the
// skill-consumed keys (read by markdown skills, invisible to Go reflection).
//
// METADATA TABLE, NOT A PROSE TEMPLATE. The schema is modeled as an ordered
// per-field metadata table (the Fields registry): each entry carries the field's
// canonical default, expected YAML kind, one-line description, scope (project/system/both), advertise
// flag, renamed_from carry-forward, AND the rendered YAML segment (the commented
// block that documents the field in the reference). Both renderings — the
// commented YAML and the JSON dump — are generated by walking that one table:
// Render() concatenates each row's Segment in table order, RenderJSON() marshals
// each row's metadata. There is no second copy of the schema and no monolithic
// template to drift against the table. This is Change 1 of the config-upgrade
// effort; the scope/advertise/renamed_from metadata is consumed by the downstream
// cascade resolver, `fab config init --system`, and `fab config upgrade`
// (Changes 2-3). See docs/specs/config.md.
//
// GENERATED, NOT HAND-WRITTEN. Every default value that has a canonical Go
// symbol is sourced from that symbol, never copied — the built-in providers via
// agent.ResolveProvider over agent.ProviderNames (so the provider SET is derived
// too, not a hand-maintained name list), the per-role default profiles via
// agent.DefaultProfile over agent.RoleNames, the pipeline stage names via
// agent.StageNames, and the pane-worker column width via
// config.DefaultDispatchColumnWidth. The dynamic segments (providers, agent, stage_hooks)
// interpolate those same symbols when the row is built, so the reference text
// carries no literal copy of any value. The providers SEGMENT still names the
// four built-ins one by one (via agent.DefaultInteractiveCommand and the
// agent.DefaultCodex*/DefaultAgy*/DefaultKimi* vars) because its per-provider
// commentary is bespoke prose, not a derivable projection — only the values are
// interpolated.
//
// ADVERTISED SURFACE vs. FULL REFERENCE. `advertise` decides only what the managed
// fence scaffolds into every project's config.yaml. As of 260806-j9nh the advertised
// agent surface is exactly the two depth knobs (agent.session, agent.workers); the
// machinery beneath them — agent.profiles and the whole providers table — is
// demoted to advertise:false, so it no longer costs ~90 commented lines in every
// repo. It keeps its registry rows, its --json defaults, and its rendered segments,
// because `fab config explain` is the canonical full schema surface and
// `fab config init --system` renders from those same segments.
//
// Canonical default vs. rendering example: a field's Default holds the CANONICAL
// built-in default (what the downstream cascade falls back to), not the value the
// reference happens to show as an example. source_paths/test_paths render an
// example (`- src/`, `- "**/*_test.go"`) but their binary default is empty, so
// their Default is nil — the example lives in the rendered Segment, not in the
// metadata.
//
// Empty-default convention: a field with no meaningful built-in default carries a
// nil Default (JSON `null`), NOT a typed empty (`[]`, `{}`, `""`). The nil is the
// uniform "no built-in default — the cascade falls back to absent" signal the
// downstream resolver (Change 2) consumes; distinguishing []string{} from nil
// would leak an implementation detail with no cascade meaning. A non-nil Default
// therefore always denotes a real built-in value (the four built-in providers'
// command grammars AND their per-role fills, the resolved per-role profiles, the
// two depth knobs' claude, dispatch.mode's native, dispatch.column_width's 35,
// dispatch.reap_done's true).
// The convention still governs WITHIN a provider: codex's and agy's fill maps are
// SPARSE, so a role fab-kit ships no fill for is simply absent rather than emitted
// as an empty object — and kimi, which ships no fills at all, projects no fill map
// rather than an empty one. The three dispatch rows are the convention's
// boundary cases: mode carries its real string default, and an absent yaml int is
// indistinguishable from 0 (which the accessor therefore reads as unset), so each
// carries its real built-in value rather than
// the typed-empty placeholder the convention forbids. reap_done is the sharpest of
// the three — its default is TRUE, so the config struct models it as a *bool to
// keep an explicit false distinguishable from absent. See docs/specs/config.md
// § Default semantics.
//
// Render() output is BYTE-STABLE for a given binary version: the field table is
// fixed and ordered, the interpolated role/stage lists come from the
// already-sorted agent.RoleNames/agent.StageNames accessors, and no map is
// range-iterated during rendering. RenderJSON() is byte-stable for the same
// reasons (ordered table, deterministic marshalling).
package configref

import (
	"bytes"
	"encoding/json"
	"fmt"
	"strconv"
	"strings"
	"unicode"

	"github.com/sahil87/fab-kit/src/go/fab/internal/agent"
	"github.com/sahil87/fab-kit/src/go/fab/internal/config"
	"github.com/sahil87/fab-kit/src/go/fab/internal/configscope"
	"github.com/sahil87/fab-kit/src/go/fab/internal/configvalue"
)

// Scope is a field's override visibility across the config cascade layers. The
// type and its three values are SINGLE-SOURCED in the leaf package
// internal/configscope (the config loader consumes the same source cycle-free);
// they are aliased here so the registry and the cascade share one definition. As
// of Change 2 (lpb5) the cascade resolver PRUNES a project-scoped field found in
// the system file (with a warning) and `fab config init --system` renders only
// system/both fields. See docs/specs/config.md § Scope taxonomy.
type Scope = configscope.Scope

const (
	// ScopeProject: overridable only in the project file (fab/project/config.yaml).
	// Semantics-class fields stay repo-reproducible for teammates/CI.
	ScopeProject = configscope.ScopeProject
	// ScopeSystem: overridable only in the system file (~/.fab-kit/config.yaml).
	// (No field is system-only today; the value exists for completeness.)
	ScopeSystem = configscope.ScopeSystem
	// ScopeBoth: overridable in either layer (preference-class fields).
	ScopeBoth = configscope.ScopeBoth
)

// validScope reports whether s is one of the three known scope values. Used by
// the registry lint (a scope outside this set is a fail-loud construction error).
// Delegates to the single-source leaf package.
func validScope(s Scope) bool {
	return configscope.Valid(s)
}

// scopeFor returns the scope for a registry row's dotted Key by collapsing it to
// its top-level YAML key (e.g. "project.name" → "project") and consulting the
// single-source leaf table. Every registry Key's top-level segment is a known
// scope key; an unknown one is a construction bug and is caught by the lint
// (scopeFor returns "" for unknown, which validScope rejects).
func scopeFor(key string) Scope {
	top := key
	if i := strings.IndexByte(key, '.'); i >= 0 {
		top = key[:i]
	}
	s, ok := configscope.ScopeFor(top)
	if !ok {
		return "" // lint rejects the empty scope, surfacing the missing taxonomy entry
	}
	return s
}

// Field is one row of the per-field metadata table — the single source the two
// renderings (commented YAML, JSON) are both generated from. It models the
// override UNIT (a meaningful override surface), which is coarser than a leaf
// key: map-valued fields (providers, agent.profiles, stage_hooks) are single rows
// with structured defaults, matching the downstream per-field deep-merge (maps
// merge per-key, lists replace, scalars replace).
type Field struct {
	// Key is the dotted path of the override surface (e.g. "agent.profiles",
	// "project.name", "true_impact_exclude"). It is the identity used by the
	// JSON dump and the JSON/YAML key-parity check.
	Key string
	// Default is the CANONICAL built-in default (typed), NOT a rendering example.
	// nil means "no built-in default" (the cascade falls back to empty/absent) —
	// e.g. source_paths/test_paths, whose shown values are examples only. A typed
	// empty is never used for "no default"; see the package-doc empty-default
	// convention.
	Default any
	// Kind is the YAML value shape accepted when this override unit is set as a
	// whole. Deep paths beneath map-valued rows are resolved separately by
	// ResolveKey, which returns their leaf kind.
	Kind configvalue.Kind
	// Description is the one-line summary of the field. Required (non-empty) —
	// the registry lint rejects an empty description. It feeds the JSON dump and
	// the future generated comment scaffold (Change 3). This is the short summary;
	// the long-form documentation prose lives in Segment (the rendered YAML block).
	Description string
	// Scope is the field's override visibility (project/system/both). Data-only
	// here; enforced in Change 2.
	Scope Scope
	// Advertise is the "C flag": whether Change 3's managed fence scaffolds this
	// field as a commented reference when it is not overridden. NO behavioral
	// consumer in this change — data + JSON exposure only.
	Advertise bool
	// RenamedFrom is the previous key path for mechanical rename carry-forward.
	// One row carries it today — `agent.profiles`, recording the 260806-j9nh rename
	// from `agent.tiers`; every other row is "". The carry is a top-level-key
	// operation, so a same-top-level rename like that one still ships a hand-written
	// migration; the field spares FUTURE top-level renames that cost. Omitted from
	// the JSON dump when empty.
	RenamedFrom string
	// InitSeed marks an A-class IDENTITY field written LIVE at `fab config init
	// --project` time from a seed value (the project's name/description/source/test
	// paths). These are the only fields the generator writes above the managed
	// fence on a fresh repo; every other field is fence territory from day one
	// (presence=intent — an init-pinned knob or role profile would be an accidental override that
	// stops tracking fab-kit's defaults). Consumed by the init generator; not part
	// of the JSON schema dump.
	InitSeed bool
	// Segment is the rendered commented-YAML block that documents this field in
	// the reference — the field's own lines (leading comment prose + the live or
	// commented key), WITHOUT a trailing newline or the inter-field blank line.
	// Render() concatenates the segments in table order (blank line between). For
	// the symbol-backed fields (providers, the agent: block, stage_hooks) the segment
	// is built by interpolating the same Go symbols Default reads, so the
	// rendered text carries no literal copy of any value. Not exposed in the JSON
	// dump (it is the human-readable rendering of the same metadata).
	Segment string
}

// jsonField is the JSON projection of a Field: stable snake_case keys and
// renamed_from,omitempty (carried by one row today — agent.profiles — and absent
// from every other row's dump). Segment is intentionally excluded — it is the YAML rendering of
// the same metadata, not part of the machine-readable schema. Kept separate from
// Field so the Go struct-field names stay idiomatic while the wire shape stays
// snake_case and stable for Changes 2-3.
type jsonField struct {
	Key         string `json:"key"`
	Default     any    `json:"default"`
	Description string `json:"description"`
	Scope       Scope  `json:"scope"`
	Advertise   bool   `json:"advertise"`
	RenamedFrom string `json:"renamed_from,omitempty"`
}

// roleProfileDefault is the structured canonical default for one agent role —
// what lands in the agent.profiles row's Default (and the JSON dump). Sourced from
// agent.DefaultProfile; never a literal copy.
type roleProfileDefault struct {
	Provider string `json:"provider"`
	Model    string `json:"model"`
	Effort   string `json:"effort"`
}

// providerProfileDefault is one built-in per-role fill on a provider — the
// `providers.<name>.profiles.<role>` value. Both fields are `omitempty` so a fill
// that carries only a model does not assert an empty effort.
type providerProfileDefault struct {
	Model  string `json:"model,omitempty"`
	Effort string `json:"effort,omitempty"`
}

// providerDefault is the structured canonical default for ONE built-in provider.
// Every field is `omitempty` because a built-in may legitimately carry only some.
// Native is capability data rather than a provider-name inference. That
// matches the registry's empty-default convention: a non-nil Default always denotes
// a real built-in value, so an absent key means "fab-kit ships none", not "empty" —
// which is also why a sparse fill map (codex, agy) omits the roles it does not
// fill rather than emitting empty objects for them.
//
// The DEPRECATED flat fill (providers.<name>.model/.effort) is deliberately not
// projected: no built-in carries it, and it exists only as a read-time alias for
// profiles.default until the 2.16.19-to-2.17.0 migration rewrites a user's config.
type providerDefault struct {
	InteractiveCommand string                            `json:"interactive_command,omitempty"`
	HeadlessCommand    string                            `json:"headless_command,omitempty"`
	Native             bool                              `json:"native,omitempty"`
	Profiles           map[string]providerProfileDefault `json:"profiles,omitempty"`
}

// providerDefaults is the structured canonical default for the providers row:
// every built-in provider fab-kit ships, DERIVED from the agent package's own
// table rather than from a hand-maintained name list. Walking
// agent.ProviderNames(nil) and resolving each through agent.ResolveProvider(nil,
// …) — both nil-safe, and a nil *config.Config resolves exactly the built-in set
// with no project overrides — means the JSON dump advertises precisely the set
// `agent.ResolveProvider` resolves with no config, and adding or renaming a
// built-in in defaults.yaml needs no edit here.
//
// Like roleRows, it fails loud on table drift — a name ProviderNames reports must
// resolve.
func providerDefaults() (map[string]providerDefault, error) {
	names := agent.ProviderNames(nil)
	defaults := make(map[string]providerDefault, len(names))
	for _, name := range names {
		p, ok := agent.ResolveProvider(nil, name)
		if !ok {
			return nil, fmt.Errorf("configref: provider %q from agent.ProviderNames does not resolve via agent.ResolveProvider", name)
		}
		var profiles map[string]providerProfileDefault
		if len(p.Profiles) > 0 {
			profiles = make(map[string]providerProfileDefault, len(p.Profiles))
			for role, fill := range p.Profiles {
				profiles[role] = providerProfileDefault{Model: fill.Model, Effort: fill.Effort}
			}
		}
		defaults[name] = providerDefault{
			InteractiveCommand: p.InteractiveCommand,
			HeadlessCommand:    p.HeadlessCommand,
			Native:             p.Native,
			Profiles:           profiles,
		}
	}
	return defaults, nil
}

// roleRow is one resolved role: its name and its default {provider, model, effort}
// profile (from agent.DefaultProfile). It is the single per-role view both the
// agent.profiles Default (as roleProfileDefault) and the rendered `agent:` Segment
// are built from — one walk of agent.RoleNames(), no duplicated loop.
type roleRow struct {
	Name    string
	Profile roleProfileDefault
}

// roleRows returns the ordered per-role view, one row per agent.RoleNames()
// entry (sorted, so deterministic). It is the SINGLE source that both the
// agent.profiles Default and the rendered `agent:` Segment consume — there is no
// second RoleNames/DefaultProfile loop. It fails loud on role-map drift: a role
// agent.RoleNames reports must resolve through agent.DefaultProfile.
func roleRows() ([]roleRow, error) {
	names := agent.RoleNames()
	rows := make([]roleRow, 0, len(names))
	for _, name := range names {
		p, ok := agent.DefaultProfile(name)
		if !ok {
			return nil, fmt.Errorf("configref: role %q from agent.RoleNames does not resolve via agent.DefaultProfile", name)
		}
		rows = append(rows, roleRow{
			Name:    name,
			Profile: roleProfileDefault{Provider: p.Provider, Model: p.Model, Effort: p.Effort},
		})
	}
	return rows, nil
}

// roleProfileDefaults projects roleRows into the map keyed by role name that the
// agent.profiles Field.Default carries (and the JSON dump emits).
func roleProfileDefaults(rows []roleRow) map[string]roleProfileDefault {
	out := make(map[string]roleProfileDefault, len(rows))
	for _, r := range rows {
		out[r.Name] = r.Profile
	}
	return out
}

// Fields returns the ordered per-field metadata table — the single source for
// both renderings. Slice order is the rendering order (deterministic, byte-stable).
// Each row carries its rendered YAML Segment; Render() walks the slice and
// concatenates the segments, RenderJSON() marshals each row's metadata.
//
// It fails loudly on a broken invariant rather than silently emitting a degraded
// reference:
//   - agent.DefaultProfile must resolve every role agent.RoleNames reports (via
//     roleRows) — the symbol-sourced default set must be complete.
//   - the registry lint (below) rejects any row with an empty Description or an
//     invalid Scope.
//
// Defaults are sourced from canonical Go symbols where they exist
// (agent.DefaultInteractiveCommand, agent.DefaultProfile). No literal here duplicates a
// Go symbol; source_paths/test_paths carry a nil Default because their binary
// default is empty (their shown values are rendering examples only).
func Fields() ([]Field, error) {
	roles, err := roleRows()
	if err != nil {
		return nil, err
	}

	providers, err := providerDefaults()
	if err != nil {
		return nil, err
	}

	roleOrder := agent.RoleNames()

	fields := []Field{
		{
			Key:         "project.name",
			Default:     nil,
			Kind:        configvalue.KindString,
			Description: "Project display name. Read by skills for orientation and PR bodies.",
			Scope:       ScopeProject,
			Advertise:   false,
			InitSeed:    true,
			Segment: `# project — identity and PR metadata.
project:
  name: "My Project"                 # skills: orientation, PR bodies
  description: "One-line project description"  # skills: orientation, PR bodies
  # linear_workspace: myteam         # optional — enables Linear issue links in
                                     # PR bodies (https://linear.app/<slug>/issue/<ID>).
                                     # Omit or leave null for bare issue-ID text.`,
		},
		{
			Key:         "project.description",
			Default:     nil,
			Kind:        configvalue.KindString,
			Description: "One-line project description. Read by skills for orientation and PR bodies.",
			Scope:       ScopeProject,
			Advertise:   false,
			InitSeed:    true,
			// Rendered inline in the project.name Segment (project is one YAML
			// block); this row carries no Segment of its own.
		},
		{
			Key:         "project.linear_workspace",
			Default:     nil,
			Kind:        configvalue.KindString,
			Description: "Optional Linear workspace slug — enables Linear issue links in PR bodies. Omit/null for bare issue-ID text.",
			Scope:       ScopeProject,
			Advertise:   false,
			// Rendered inline in the project.name Segment (project is one YAML block).
		},
		{
			Key:         "source_paths",
			Default:     nil, // binary default empty; `- src/` is a rendering example.
			Kind:        configvalue.KindSequence,
			Description: "Directories containing implementation code (relative to repo root). Read by skills to scope apply context.",
			Scope:       ScopeProject,
			Advertise:   false,
			InitSeed:    true,
			Segment: `# source_paths — directories containing implementation code (relative to repo
# root). Read by skills to scope apply context.
source_paths:
  - src/`,
		},
		{
			Key:         "test_paths",
			Default:     nil, // binary default empty; the `- "**/*_test.go"` line is a rendering example.
			Kind:        configvalue.KindSequence,
			Description: "Glob/pathspec patterns identifying test files. Used by the /git-pr true-impact breakdown to attribute lines to tests vs. implementation. No kit default.",
			Scope:       ScopeProject,
			Advertise:   true,
			// InitSeed: written live at init ONLY when detection found a test
			// convention (the seed value); otherwise it stays fence-advertised.
			InitSeed: true,
			Segment: "# test_paths — glob/pathspec patterns identifying test files. Used by the\n" +
				"# /git-pr true-impact breakdown to attribute lines to tests vs. implementation\n" +
				"# (impl = total − tests). Language-specific — no kit default. Patterns are\n" +
				"# :(glob) magic pathspecs, so `**` matches across directories and `*` does\n" +
				"# NOT match `/`. Anchor to your language's test convention rather than a bare\n" +
				"# substring (a substring like `*test*` miscounts production code such as\n" +
				"# `attestation.go` or `latest.go`). When absent/empty, the breakdown collapses\n" +
				"# to a single total.\n" +
				"#\n" +
				"# Examples per stack (uncomment/adapt the line for yours):\n" +
				"#   - \"**/*_test.go\"                  # Go     — `_test.go` suffix\n" +
				"#   - \"**/test_*.py\"                  # Python (pytest) — `test_` prefix\n" +
				"#   - \"**/*.spec.ts\"                  # JS/TS  (Jest/Vitest) — `.spec` infix\n" +
				"#   - \"**/*.test.ts\"                  # JS/TS  — `.test` infix\n" +
				"#   - \"**/src/test/**\"               # Java/Kotlin (Maven/Gradle) — test source root\n" +
				"test_paths:\n" +
				"  - \"**/*_test.go\"                   # example (Go — `_test.go` suffix)",
		},
		{
			Key:         "true_impact_exclude",
			Default:     nil,
			Kind:        configvalue.KindSequence,
			Description: "Pathspec exclusions used by /git-pr to compute the true-impact line counts (excluding noise directories). Optional — when absent/empty the impact block is omitted.",
			Scope:       ScopeProject,
			Advertise:   true,
			Segment: `# true_impact_exclude — pathspec exclusions used by /git-pr to compute the "true
# impact" line counts in the PR body (excluding noise directories). Optional —
# when absent or empty, the impact block is omitted.
true_impact_exclude:
  - fab/
  - docs/`,
		},
		{
			Key:         "checklist.extra_categories",
			Default:     nil,
			Kind:        configvalue.KindSequence,
			Description: "Project-specific quality categories appended to the built-in plan.md ## Acceptance categories. Each becomes an extra subsection under plan.md ## Acceptance.",
			Scope:       ScopeProject,
			Advertise:   true,
			Segment: `# checklist.extra_categories — project-specific quality categories appended to
# the built-in plan.md ## Acceptance categories (functional_completeness,
# behavioral_correctness, scenario_coverage, edge_cases, code_quality, security).
# Each becomes an extra subsection under plan.md ## Acceptance.
checklist:
  extra_categories: []               # example: [performance, accessibility, i18n]`,
		},
		{
			Key:         "consolidate.detectors",
			Default:     nil,
			Kind:        configvalue.KindSequence,
			Description: "Duplicate-detection commands `/fab-dedupe` runs to seed its sweep. Each entry is a shell command template; `{paths}` and `{out}` are substituted at run time as shell-quoted values. Missing binaries are skipped silently.",
			Scope:       ScopeProject,
			Advertise:   true,
			Segment: `# consolidate.detectors — duplicate-detection commands /fab-dedupe runs to seed
# its sweep. Each entry is a shell command template; {paths} (the resolved scope)
# and {out} (a scratch dir) are substituted at run time as shell-quoted values,
# so paths containing spaces or shell metacharacters stay intact arguments.
# A detector whose binary is missing is skipped silently; a non-zero exit is
# treated as a finding, not an error. Detectors only SEED the sweep — the agent
# does the clustering.
# consolidate:
#   detectors:
#     - jscpd --reporters json --output {out} {paths}`,
		},
		{
			Key:         "agent.session",
			Default:     agent.DefaultProviderName,
			Kind:        configvalue.KindString,
			Description: "Provider for the Tier-1 (session) roles — the agents you talk to: fab agent, fab operator, fab batch worker sessions (roles default and operator). Names an entry in the providers table; applies at launch time. Scope both — settable once machine-wide, where it outranks the project file. Default claude.",
			Scope:       ScopeBoth,
			Advertise:   true,
			Segment:     agentSegment(roles),
		},
		{
			Key:         "agent.workers",
			Default:     agent.DefaultProviderName,
			Kind:        configvalue.KindString,
			Description: "Provider for the Tier-2 (worker) roles — the agents pipeline stages dispatch to: apply, review, hydrate, ship, review-pr (roles doing, review, hydrate, fast). Names an entry in the providers table; applies at every stage dispatch. Scope both — settable once machine-wide, where it outranks the project file. Default claude.",
			Scope:       ScopeBoth,
			Advertise:   true,
			// Rendered inline in the agent.session Segment (agent is one YAML block,
			// so a second `agent:` parent would collide into a duplicate key); this
			// row carries no Segment of its own. Same pattern as project.description
			// and dispatch.column_width.
		},
		{
			Key:         "agent.profiles",
			Default:     roleProfileDefaults(roles),
			Kind:        configvalue.KindMapping,
			Description: "Sparse per-role override beneath the two depth knobs. Keyed by role (default/operator/doing/review/hydrate/fast), each value a {provider, model, effort} with every field optional: a set provider beats the role's depth knob, a set model/effort beats the provider's own fill. There is no cross-role inheritance — agent.profiles.default is the default role's override, not a fallback for the others. The stage→role mapping and the role→depth partition are fixed and fab-owned.",
			Scope:       ScopeBoth,
			// Demoted from the managed fence (260806-j9nh): the advertised agent
			// surface is the two knobs, and scaffolding the six role profiles into
			// every project's config.yaml was ~30 of the ~90 lines the fence spent on
			// machinery nobody overrides. Still fully documented — in the `agent:`
			// segment's pointer lines, in --json (this row's Default), and in
			// docs/specs/config.md.
			Advertise:   false,
			RenamedFrom: "agent.tiers",
			// Rendered inline in the agent.session Segment (one `agent:` block).
		},
		{
			Key:         "providers",
			Default:     providers,
			Kind:        configvalue.KindMapping,
			Description: "Named agent capability grammars: four built-in providers with per-role fills on the kit-release cadence. Each provider MAY carry interactive_command (pane/session), headless_command (headless stage task), and native (native Agent-tool capability); presence describes how and never selects dispatch mode. Command fields are never merged or substituted for one another. interactive_command MAY additionally carry a {prompt} placeholder marking where an initial prompt is delivered — substituted with the shell-quoted prompt by every prompt-carrying launch (fab operator, fab batch, pane dispatch), dropped with its preceding flag at the one promptless launch, bare `fab agent`; a command without one receives the prompt as a trailing positional argument instead. Only {model}/{effort} select template mode, so a command whose only placeholder is {prompt} still gets --model/--effort appended. profiles supplies {model}/{effort} placeholders with precedence invocation flag > agent.profiles.<role> field > providers.<p>.profiles.<role> > providers.<p>.profiles.default > empty. Fill roster: claude ships all six role fills, codex and agy sparse maps whose `default` entry is the cross-role fallback, and kimi NO fills at all (its -m takes a user-config model alias, so the empty model drops the flag and the CLI's own default_model applies). Provider names are opaque, user-chosen strings.",
			Scope:       ScopeBoth,
			// Demoted from the managed fence (260806-j9nh) for the same reason as
			// agent.profiles: naming a built-in in a knob needs no providers: block at
			// all, so ~60 commented lines of grammar per repo bought nothing. Still
			// rendered here and in `fab config init --system`.
			Advertise: false,
			// The command fields were renamed INSIDE this nested table in 2.19.0
			// (session_command → interactive_command, dispatch_command →
			// headless_command). The top-level renamed_from mechanical carry
			// cannot fire on nested keys, so this metadata is informational for
			// --json consumers; the on-disk rewrite is the 2.18.1-to-2.19.0
			// migration's job, and the read-time alias keeps old spellings
			// resolving meanwhile.
			RenamedFrom: "providers.<name>.session_command, providers.<name>.dispatch_command",
			Segment:     providersSegment(providers, roleOrder),
		},
		{
			Key:         "dispatch.mode",
			Default:     config.DefaultDispatchMode,
			Kind:        configvalue.KindString,
			Description: "Preferred stage-dispatch mode: pane, native, or headless. Resolution starts at the preference and descends pane → native → headless without ascending, choosing the first mode supported by the provider and environment. Scope both — settable once machine-wide, where it outranks the project file. Default native.",
			Scope:       ScopeBoth,
			Advertise:   true,
			Segment:     dispatchSegment(),
		},
		{
			Key: "dispatch.column_width",
			// Like mode, a real built-in value rather than "no default": the
			// cascade bottoms out at 35, and an absent yaml int is indistinguishable
			// from 0, so the accessor treats out-of-range as unset. Sourced from the
			// canonical config symbol, never a literal copy.
			Default:     config.DefaultDispatchColumnWidth,
			Kind:        configvalue.KindInt,
			Description: "Pane-worker column width, in percent of the window, applied by the column-carving `-h` split that opens a pane-mode stage worker beside its dispatching agent (`split-window -h -l <n>%`). Only that first split is sized — later workers stack inside the column with unsized `-v` splits. Out-of-range values (and an absent key) resolve to the default. Scope both — settable once machine-wide, where it outranks the project file. Default 35.",
			Scope:       ScopeBoth,
			Advertise:   true,
			// Rendered inline in the dispatch.mode Segment (dispatch is one YAML
			// block, so a second `# dispatch:` block would collide if a reader
			// uncommented both); this row carries no Segment of its own. Same pattern
			// as project.description / project.linear_workspace.
		},
		{
			Key: "dispatch.reap_done",
			// The third real built-in value under `dispatch:` — and the boundary case
			// that needed a POINTER on the config struct: the default is TRUE, so the
			// Go zero value means the opposite of it and an absent key had to stay
			// distinguishable from an explicit `false`. Sourced from the canonical
			// config symbol, never a literal copy.
			Default:     config.DefaultDispatchReapDone,
			Kind:        configvalue.KindBool,
			Description: "Done-worker pane reaping. When true, `fab dispatch reap` kills a pane-mode stage worker's tmux pane once its result file is present, reclaiming the column space a finished worker would otherwise hold for the rest of the run. Reap is not kill: it never touches a running, orphaned, or failed dispatch, and it removes no .fab-dispatch/ state. Set false to keep a done worker's scrollback. Scope both — settable once machine-wide, where it outranks the project file. Default true.",
			Scope:       ScopeBoth,
			Advertise:   true,
			// Rendered inline in the dispatch.mode Segment, same as
			// dispatch.column_width; this row carries no Segment of its own.
		},
		{
			Key:         "stage_hooks",
			Default:     nil,
			Kind:        configvalue.KindMapping,
			Description: "Optional per-stage pre/post shell commands honored by fab status start/finish. Each runs as sh -c from the repo root; a failing pre hook blocks start. Not seeded by the scaffold — add by hand.",
			Scope:       ScopeProject,
			Advertise:   true,
			Segment:     stageHooksSegment(),
		},
		{
			Key:         "branch_prefix",
			Default:     nil,
			Kind:        configvalue.KindString,
			Description: "Optional prefix applied by fab batch switch when creating worktree branches (branch name = {branch_prefix}{folder_name}). Empty when absent.",
			Scope:       ScopeProject,
			Advertise:   true,
			Segment: "# branch_prefix — optional prefix applied by `fab batch switch` when creating\n" +
				"# worktree branches (branch name = `{branch_prefix}{folder_name}`). Empty when\n" +
				"# absent.\n" +
				`# branch_prefix: ""`,
		},
	}

	if err := lintFields(fields); err != nil {
		return nil, err
	}
	return fields, nil
}

// referenceHeader is the fixed preamble of the reference — the file-level banner
// that precedes the first field segment. It is not a field row (it documents no
// single key); Render() emits it, then the field segments in table order.
const referenceHeader = `# Full reference of all available options: fab config explain
#
# This is the canonical, generated reference for fab/project/config.yaml. Every
# key below is documented — baseline keys appear live with example values;
# optional override blocks (agent.profiles, stage_hooks, branch_prefix) are shown
# commented-out with fab-kit's built-in defaults. Uncomment a block to opt in.
# Values here are examples/defaults, not your project's settings.
#
# This is the FULL reference. Your project's own config.yaml carries a slimmer
# managed fence: only the advertised fields are scaffolded there, so the agent
# machinery below (agent.profiles, providers) is documented here rather than
# copied into every repo. See docs/specs/config.md.`

// providersSegment renders the providers block. Every command string is
// interpolated from its canonical agent var (no literal copy):
// agent.DefaultInteractiveCommand / agent.DefaultHeadlessCommand for claude, and the
// agent.DefaultCodex*/DefaultAgy*/DefaultKimi* vars for the other three built-ins
// (codex and agy carry both commands; kimi is dispatch-only).
// The per-role FILLS are interpolated the same way, from the already-derived
// providerDefaults() view — so the shipped values appear here without a literal copy,
// and a bump in defaults.yaml reaches the rendered reference by itself. kimi ships no
// fills, so profilesLines renders no `profiles:` key for it at all.
//
// Fill lines are emitted in roleOrder (agent.RoleNames(), sorted) so the output stays
// BYTE-STABLE: the profiles map is looked up by key, never range-iterated.
//
// Presentation (260805-j3cm): all four providers are BUILT-IN, so the non-claude
// blocks are rendered as commented reference-style defaults — the same presentation
// every other non-overridden default uses — not as uncomment-to-opt-in blocks. The
// commented form still registers no project override (presence=intent holds for
// BEHAVIOR: a built-in provider is inert until a knob, a role override, or a flag names it), and
// whole-block uncommenting still yields valid YAML because all per-provider prose
// stays above the `providers:` key.
//
// This segment carries the registry's only DELIBERATELY-COMMENTED content lines —
// the `# codex:` / `# agy:` / `# kimi:` blocks.
// configupgrade.CommentOutSegment prefixes those like any live line (its column-0
// rule), so in a rendered fence every marker lands at column 0 and the "strip the
// leading '# ' from every line of a block" instruction below restores this text
// byte-exactly — with those lines still commented at their original indent.
func providersSegment(providers map[string]providerDefault, roleOrder []string) string {
	return "# providers — named independent interactive, headless, and native launch capabilities plus their per-role fills. This\n" +
		"# block is MACHINERY: naming a built-in on a depth knob (agent.session /\n" +
		"# agent.workers, above) needs no `providers:` entry at all, so it is documented\n" +
		"# here rather than scaffolded into your config. Full schema: docs/specs/config.md.\n" +
		"#\n" +
		"# Each provider MAY carry two command fields plus native capability (the command\n" +
		"# fields are NOT merged — interactive and headless are different invocations):\n" +
		"#   interactive_command — opens an interactive agent SESSION (fab operator /\n" +
		"#                         fab batch / fab agent). {model}/{effort} placeholders\n" +
		"#                         are substituted from the resolved role profile, or\n" +
		"#                         from the --model/--effort flags on `fab agent\n" +
		"#                         --provider <name>` (which bypasses role resolution);\n" +
		"#                         the built-in commands below are all templated this\n" +
		"#                         way. ONLY {model}/{effort} select template mode: a\n" +
		"#                         command carrying neither instead gets --model/--effort\n" +
		"#                         APPENDED, and that includes a command whose only\n" +
		"#                         placeholder is {prompt}. {prompt} marks where an\n" +
		"#                         initial prompt is delivered — the shell-quoted prompt\n" +
		"#                         is substituted there by every prompt-carrying launch\n" +
		"#                         (fab operator, fab batch, pane dispatch) and drops\n" +
		"#                         with its preceding flag at the one promptless launch,\n" +
		"#                         bare `fab agent`. A command without it receives the\n" +
		"#                         prompt as a trailing positional argument instead.\n" +
		"#   headless_command    — runs ONE headless stage task via fab dispatch. There\n" +
		"#                         is NO substitution between command fields; fab\n" +
		"#                         dispatch pipes the stage prompt to the command's\n" +
		"#                         STDIN.\n" +
		"#   native              — declares native Agent-tool capability. Provider names\n" +
		"#                         are opaque, so fab never infers this capability from a\n" +
		"#                         name.\n" +
		"# Presence is capability data (how), never mode policy (whether). dispatch.mode\n" +
		"# owns the preference and descends pane → native → headless.\n" +
		"# (`session_command` / `dispatch_command` are the pre-2.19.0 spellings of those\n" +
		"# two command fields — still read as PER-FIELD aliases, so a half-migrated\n" +
		"# config resolves; the 2.18.1-to-2.19.0 migration rewrites them on disk, and\n" +
		"# `fab config set/unset` accepts the new spellings only.)\n" +
		"# Each provider also carries a per-role fill map that supplies those placeholders:\n" +
		"#   profiles.<role>     — {model, effort} for when THIS provider plays THAT\n" +
		"#                         role. Keyed by the six role names; `default` doubles\n" +
		"#                         as this provider's cross-role fallback. Precedence:\n" +
		"#                         invocation flag > agent.profiles.<role> field >\n" +
		"#                         profiles.<role> > profiles.default > empty (empty\n" +
		"#                         drops the placeholder's token, so the CLI's own\n" +
		"#                         default applies). Scope `both`, so a machine-wide fill\n" +
		"#                         is settable once in ~/.fab-kit/config.yaml, where it\n" +
		"#                         outranks the project file. (The pre-2.17.0 flat\n" +
		"#                         providers.<name>.model / .effort is still read as an\n" +
		"#                         alias for profiles.default; the 2.16.19-to-2.17.0\n" +
		"#                         migration rewrites it.)\n" +
		"# Provider names are opaque, user-chosen strings — fab NEVER infers a provider\n" +
		"# from a model string, and values pass through verbatim with no validation.\n" +
		"#\n" +
		"# fab-kit ships FOUR built-in providers — claude (the default), codex, agy and\n" +
		"# kimi — so `agent.workers: codex` needs no providers: block at all. claude, codex\n" +
		"# and agy carry per-role fills, and every role still resolves a model suited to it;\n" +
		"# the non-claude maps are SPARSE: a role absent from one takes that provider's\n" +
		"# `default` entry. Those fills are refreshed at KIT-RELEASE cadence and pass through\n" +
		"# unvalidated — override one with providers.<name>.profiles.<role>.model to pin a\n" +
		"# newer model. kimi deliberately ships NO fills (see its note below), so it\n" +
		"# resolves an empty model and the -m flag drops out.\n" +
		"# Only the non-claude maps are PRINTED below — claude's six fills are the role\n" +
		"# defaults `fab resolve-agent <stage>` resolves, and every provider's map is\n" +
		"# projected by `fab config explain --json`; their absence from claude's\n" +
		"# block below is a rendering choice, not a missing fill.\n" +
		"# Every non-claude block below is commented because it merely restates a built-in\n" +
		"# default; claude's three capabilities are shown live as the baseline example.\n" +
		"# Claude carries all three capabilities; codex and agy carry pane + headless and\n" +
		"# therefore descend from the default native preference to headless. kimi ships NO\n" +
		"# interactive_command — it is the one DISPATCH-ONLY built-in, with no pane\n" +
		"# capability: pane dispatch delivers the worker's pointer prompt through that\n" +
		"# command (substituted at a {prompt} placeholder, or appended as a positional\n" +
		"# argument when there is none), and kimi can receive it neither way (see its note\n" +
		"# below) — so mode resolution lands its stages on headless. Add\n" +
		"# providers.kimi.interactive_command yourself if you want `fab agent --provider kimi`\n" +
		"# to open an interactive session, accepting that pane-dispatched stages will not\n" +
		"# receive their prompt.\n" +
		"#\n" +
		"# Per-provider notes (kept out of the blocks below so uncommenting a whole block\n" +
		"# yields valid YAML — strip the leading '# ' from every line of a block):\n" +
		"#   claude.headless_command — claude -p reads the prompt from stdin.\n" +
		"#   codex — codex exec reads the prompt from stdin; both commands carry\n" +
		"#     --dangerously-bypass-approvals-and-sandbox. Its -m takes a concrete model\n" +
		"#     SLUG, so the fills below are pinned IDs: override one to pin a newer model.\n" +
		"#   agy — the Antigravity CLI. There is no {effort}: its model IDs EMBED the\n" +
		"#     reasoning level (gemini-3.1-pro-high), so its fills are model-only. `agy -p`\n" +
		"#     takes the prompt as an ARGUMENT and ignores stdin, so headless_command nests\n" +
		"#     a shell — POSIX expands $(cat) before fab dispatch's stdin redirect applies,\n" +
		"#     making the inner sh's stdin the prompt. --print-timeout is raised well above\n" +
		"#     its 5m default because stage workers run far longer. Its interactive_command\n" +
		"#     ends on `-i {prompt}` (--prompt-interactive) because agy DROPS a positional\n" +
		"#     prompt and its -i takes a VALUE: every prompt-carrying launch (fab operator,\n" +
		"#     fab batch, pane dispatch) substitutes its shell-quoted prompt there, and the\n" +
		"#     one promptless launch, bare `fab agent`, substitutes empty so the pair\n" +
		"#     token-drops.\n" +
		"#     CAVEAT: agy gates a fresh workspace behind an interactive trust dialog even\n" +
		"#     under --dangerously-skip-permissions, so a pane worker in a not-yet-trusted\n" +
		"#     worktree parks there once until a human answers it (the trust store is\n" +
		"#     ~/.gemini/antigravity-cli/settings.json trustedWorkspaces, exact-match paths;\n" +
		"#     fab does not seed it).\n" +
		"#   kimi — the kimi-code CLI, and the one built-in shipping NO fills: its -m takes\n" +
		"#     a USER-CONFIG model alias rather than a catalog ID, so a pinned value would\n" +
		"#     break non-managed installs. The empty model drops `-m` and kimi falls back to\n" +
		"#     your own default_model; pin one with providers.kimi.profiles.<role>.model if\n" +
		"#     you want per-role differentiation. Same nested-shell stdin idiom as agy, and\n" +
		"#     no approval flag on dispatch: `kimi -p` already auto-approves tools and\n" +
		"#     REJECTS --yolo/--auto. No interactive_command: kimi parses a bare positional\n" +
		"#     as a SUBCOMMAND and exits non-zero, and has no interactive-initial-prompt\n" +
		"#     flag at all — not even a value-taking one a {prompt} placeholder could target.\n" +
		"# The bypass flags are deliberate: unattended stage workers cannot answer approval\n" +
		"# prompts. Override the corresponding provider command to restore an\n" +
		"# approval-gated posture.\n" +
		"providers:\n" +
		"  claude:\n" +
		"    native: " + strconv.FormatBool(providers[agent.DefaultProviderName].Native) + "\n" +
		"    interactive_command: " + YAMLSingleQuoted(agent.DefaultInteractiveCommand) + "\n" +
		"    headless_command: " + YAMLSingleQuoted(agent.DefaultHeadlessCommand) + "\n" +
		"  # codex:\n" +
		"  #   interactive_command: " + YAMLSingleQuoted(agent.DefaultCodexInteractiveCommand) + "\n" +
		"  #   headless_command: " + YAMLSingleQuoted(agent.DefaultCodexHeadlessCommand) + "\n" +
		profilesLines(providers["codex"].Profiles, roleOrder) +
		"  # agy:\n" +
		"  #   interactive_command: " + YAMLSingleQuoted(agent.DefaultAgyInteractiveCommand) + "   # -i takes a VALUE, so the pointer rides {prompt}\n" +
		"  #   headless_command: " + YAMLSingleQuoted(agent.DefaultAgyHeadlessCommand) + "   # no {effort} flag; nested shell so $(cat) reads the piped prompt\n" +
		profilesLines(providers["agy"].Profiles, roleOrder) +
		// kimi ships no fills, so profilesLines renders nothing for it — the trim
		// therefore has to span the whole kimi block, not just its (empty) fill
		// lines, or the segment would end with a stray newline.
		strings.TrimRight(
			"  # kimi:\n"+
				"  #   headless_command: "+YAMLSingleQuoted(agent.DefaultKimiHeadlessCommand)+"   # dispatch only; no fills shipped, so the empty {model} drops -m\n"+
				profilesLines(providers["kimi"].Profiles, roleOrder), "\n")
}

// YAMLSingleQuoted wraps a command string as a YAML single-quoted scalar, doubling
// any interior `'` per the YAML spec.
//
// It is load-bearing rather than cosmetic: the segment's own prose promises that
// stripping the leading `# ` from a whole block yields VALID YAML, and the agy/kimi
// dispatch commands nest a shell (`sh -c '… -p "$(cat)"'`) so they contain single
// quotes. Naive wrapping would close the scalar early and hand a user who uncomments
// the block a parse error.
//
// Exported because the rendering rule has exactly one owner: tests that assert the
// rendered form (cmd/fab, internal/configupgrade) call this rather than re-deriving
// the doubling, so a change to the quoting can never leave an assertion behind.
func YAMLSingleQuoted(s string) string {
	return "'" + strings.ReplaceAll(s, "'", "''") + "'"
}

// profilesLines renders a provider's per-role fill map as commented reference lines
// under a `# profiles:` key, one role per line in roleOrder (so the output is
// byte-stable — the map is looked up by key, never ranged over). A role absent from
// the map is skipped, which is what keeps a SPARSE built-in rendering sparse. The
// effort half is omitted for a fill that carries none (agy), so the rendered YAML
// never asserts an effort the provider has no flag for.
//
// Returns "" for a provider with no fills, so a grammar-only built-in (kimi) renders
// no `profiles:` key at all rather than an empty one.
func profilesLines(profiles map[string]providerProfileDefault, roleOrder []string) string {
	if len(profiles) == 0 {
		return ""
	}
	var b strings.Builder
	b.WriteString("  #   profiles:\n")
	for _, role := range roleOrder {
		fill, ok := profiles[role]
		if !ok {
			continue
		}
		// Only the fields the fill actually carries are rendered: an effort-only
		// entry inherits its model from `default` and must not claim an empty one,
		// and a model-only entry must not assert an effort its CLI has no flag for.
		var set []string
		if fill.Model != "" {
			set = append(set, "model: "+fill.Model)
		}
		if fill.Effort != "" {
			set = append(set, "effort: "+fill.Effort)
		}
		if len(set) == 0 {
			continue
		}
		fmt.Fprintf(&b, "  #     %s: { %s }\n", role, strings.Join(set, ", "))
	}
	return b.String()
}

// agentSegment renders the WHOLE `agent:` block — the two advertised depth knobs
// live, plus a commented agent.profiles pointer/example — since `agent` is one YAML
// block and two separately-uncommentable `agent:` parents would collide into a
// duplicate key (the project.name / dispatch.mode precedent). The
// agent.workers and agent.profiles registry rows therefore carry no Segment of
// their own.
//
// This is the ONLY agent-side block the managed fence scaffolds, which is the whole
// point of the 260806-j9nh demotion: the fixed role→referent grouping and the
// built-in per-role profiles are emitted from the single roleRows() walk — the same
// rows the agent.profiles Default is built from — so no value here is a literal copy
// and the loop is not duplicated.
func agentSegment(roles []roleRow) string {
	var b strings.Builder
	b.WriteString("# agent.session / agent.workers — the two knobs, one per agent DEPTH. `session`\n")
	b.WriteString("# is what YOU talk to (fab agent, fab operator, fab batch); `workers` is what\n")
	b.WriteString("# pipeline STAGES dispatch to. Each names an entry in the `providers:` table,\n")
	b.WriteString("# which `fab config explain` prints in full (it is machinery, so the managed\n")
	b.WriteString("# fence omits it) — fab-kit ships claude, codex, agy and kimi, so `workers: codex`\n")
	b.WriteString("# needs no other config. Both default to claude. Scope `both`, so the choice is\n")
	b.WriteString("# settable once machine-wide in ~/.fab-kit/config.yaml, where it outranks\n")
	b.WriteString("# the project file.\n")
	b.WriteString("#\n")
	// The role→depth partition, compacted to one line per depth. internal/agent OWNS
	// the partition; agent.IsSessionRole is the exported read of it, so this rendering
	// never re-encodes which roles sit at which depth. The full role→referent table
	// (which stages each role governs) lives in docs/specs/stage-models.md — the fence
	// carries the ADVERTISED surface, not the taxonomy behind it.
	var session, workers []string
	for _, r := range roles {
		if agent.IsSessionRole(r.Name) {
			session = append(session, r.Name)
			continue
		}
		workers = append(workers, r.Name)
	}
	fmt.Fprintf(&b, "#   session roles: %s\n", strings.Join(session, ", "))
	fmt.Fprintf(&b, "#   workers roles: %s\n", strings.Join(workers, ", "))
	b.WriteString("#\n")
	b.WriteString("# agent.profiles.<role> is the sparse per-role escape hatch beneath the knobs —\n")
	b.WriteString("# {provider, model, effort}, every field optional, no cross-role inheritance.\n")
	b.WriteString("# Reach for it only to dial ONE role; see `fab config explain --json` and\n")
	b.WriteString("# docs/specs/config.md. (`agent.tiers` is its pre-2.17.0 spelling — still read,\n")
	b.WriteString("# rewritten by the 2.16.19-to-2.17.0 migration.)\n")
	b.WriteString("agent:\n")
	b.WriteString("  session: " + agent.DefaultProviderName + "                    # Tier 1 — the agents you talk to\n")
	b.WriteString("  workers: " + agent.DefaultProviderName + "                    # Tier 2 — the agents stages dispatch to\n")
	b.WriteString("  # profiles:\n")
	b.WriteString("  #   review: { provider: codex }      # example: run just the critic elsewhere\n")
	// Trim the trailing newline: Render() re-inserts the inter-field separator.
	return strings.TrimRight(b.String(), "\n")
}

// dispatchSegment renders the whole `dispatch:` block — ALL THREE keys under it,
// since `dispatch` is one YAML block and two separately-uncommentable `# dispatch:`
// parents would collide into a duplicate key. dispatch.mode is the preferred
// descent-ladder rung; dispatch.column_width sizes the worker column;
// dispatch.reap_done reclaims a done worker's pane. All three have canonical
// constants to interpolate: config.DefaultDispatchMode,
// config.DefaultDispatchColumnWidth, and config.DefaultDispatchReapDone.
//
// The dispatch.column_width and dispatch.reap_done registry rows therefore carry no
// Segment of their own — the project.name / project.description precedent for
// multiple keys in one block.
func dispatchSegment() string {
	return "# dispatch.mode — preferred stage-worker adapter: pane, native, or headless.\n" +
		"# Resolution starts at the preference and DESCENDS pane → native → headless,\n" +
		"# never ascending, until provider capability + environment make a rung possible:\n" +
		"# pane needs tmux + interactive_command; native needs native: true; headless needs\n" +
		"# headless_command. Command fields are pure capability grammar — presence says\n" +
		"# HOW, never WHETHER. `pane` is the watchable preference (no `auto` value):\n" +
		"# outside tmux it descends to native or headless. Default native reproduces the\n" +
		"# shipped behavior (claude native; codex/agy/kimi headless). Scope `both`, so it\n" +
		"# is settable once machine-wide in ~/.fab-kit/config.yaml, where it outranks\n" +
		"# the project file. Invalid values warn and fail open to " + config.DefaultDispatchMode + ".\n" +
		"#\n" +
		"# dispatch.column_width — width, in PERCENT of the window, of the pane-worker\n" +
		"# column a pane-mode stage worker is opened into. The first worker CARVES the\n" +
		"# column out of the dispatching agent's pane (`tmux split-window -h -l <n>%`),\n" +
		"# so the agent you are watching keeps the other " + strconv.Itoa(100-config.DefaultDispatchColumnWidth) + "%; later workers STACK\n" +
		"# inside that column with unsized `-v` splits and the left/right separator is\n" +
		"# never touched again. An absent key — or a value outside 1..99 — resolves to\n" +
		"# the default (an absent yaml int is indistinguishable from 0, and 0/100 are\n" +
		"# degenerate widths). A tmux too old for `-l <n>%` (pre-3.1) degrades to an\n" +
		"# unsized split with a warning rather than failing the dispatch. Scope `both`,\n" +
		"# so it is settable once machine-wide in ~/.fab-kit/config.yaml, where it\n" +
		"# outranks the project file.\n" +
		"#\n" +
		"# dispatch.reap_done — whether `fab dispatch reap` reclaims a DONE pane-mode\n" +
		"# worker's tmux pane. A pane worker never exits on completion (it writes\n" +
		"# {stage}-result.yaml and sits at its prompt), so without reaping every\n" +
		"# finished stage keeps its slice of the worker column for the rest of the run\n" +
		"# and the panes you actually watch shrink with each completed stage. The\n" +
		"# orchestrator calls reap right after it reads a done result. REAP IS NOT KILL:\n" +
		"# it fires only on `done`, never on a running/orphaned/failed dispatch, is a\n" +
		"# no-op for headless dispatches (the process already exited), and touches NO\n" +
		"# .fab-dispatch/ state — the record and result file stay, so a reaped dispatch\n" +
		"# still reads `done` forever. Set false to keep a done worker's pane and its\n" +
		"# scrollback. Scope `both`, so it is settable once machine-wide in\n" +
		"# ~/.fab-kit/config.yaml, where it outranks the project file. Default " + strconv.FormatBool(config.DefaultDispatchReapDone) + ".\n" +
		"# dispatch:\n" +
		"#   mode: " + config.DefaultDispatchMode + "\n" +
		"#   column_width: " + strconv.Itoa(config.DefaultDispatchColumnWidth) + "\n" +
		"#   reap_done: " + strconv.FormatBool(config.DefaultDispatchReapDone)
}

// stageHooksSegment renders the stage_hooks block. The valid stage-keys list is
// interpolated from agent.StageNames() (sorted, deterministic) — no literal copy
// of the stage set.
func stageHooksSegment() string {
	return "# stage_hooks — optional per-stage pre/post shell commands honored by\n" +
		"# `fab status start` / `fab status finish`. Each command runs as `sh -c` from\n" +
		"# the repo root. A failing `pre` hook blocks `fab status start`; a `post` hook\n" +
		"# runs after `finish` saves. Not seeded by the scaffold — add by hand.\n" +
		"# Valid stage keys: " + strings.Join(agent.StageNames(), ", ") + ".\n" +
		"# stage_hooks:\n" +
		"#   apply:\n" +
		"#     pre: ./scripts/check-clean-tree.sh\n" +
		"#     post: make test"
}

// lintFields is the fail-loud registry validation: every row must have a
// non-empty Description and a valid Scope. A violation is a construction bug
// (a new row added without metadata), caught here rather than shipped as a
// degraded reference — the same discipline as the role-profile invariant above.
func lintFields(fields []Field) error {
	for _, f := range fields {
		if f.Description == "" {
			return fmt.Errorf("configref: field %q has an empty description (every registry row must document its field)", f.Key)
		}
		if !validScope(f.Scope) {
			return fmt.Errorf("configref: field %q has invalid scope %q (want one of project/system/both)", f.Key, f.Scope)
		}
		if !configvalue.Valid(f.Kind) {
			return fmt.Errorf("configref: field %q has invalid value kind %q", f.Key, f.Kind)
		}
		// Single-source guard: the row's Scope MUST equal the leaf-package
		// taxonomy for the field's top-level key. The loader (internal/config)
		// prunes the system layer on that same leaf table, so a divergence here
		// would silently split the scope taxonomy in two. Fail loud at
		// construction instead. See internal/configscope.
		if want := scopeFor(f.Key); f.Scope != want {
			return fmt.Errorf("configref: field %q has scope %q but internal/configscope says %q — the scope taxonomy is single-sourced in configscope; fix it there", f.Key, f.Scope, want)
		}
	}
	return nil
}

// KeyMatch is the registry resolution for an exact key or supported deep path.
// Field is the override-unit row that supplies scope and schema ownership;
// Owner is the row whose Segment renders the key; Kind is the exact value kind
// accepted at the requested path.
type KeyMatch struct {
	Field Field
	Owner Field
	Kind  configvalue.Kind
}

// ResolveKey validates a dotted config key against the registry. Map-valued
// rows accept only their documented dynamic axes, so plausible typos do not
// become silent writes. Quoted/escaped key spellings are deliberately refused;
// the command surface accepts canonical unquoted dotted paths only.
func ResolveKey(key string) (KeyMatch, bool, error) {
	fields, err := Fields()
	if err != nil {
		return KeyMatch{}, false, err
	}
	parts := strings.Split(key, ".")
	if len(parts) >= 2 && parts[0] == "providers" {
		if reason := invalidProviderName(parts[1]); reason != "" {
			return KeyMatch{}, false, fmt.Errorf(
				"config key %q uses provider name %q, which cannot be represented by the dotted config-key grammar: %s",
				key, parts[1], reason,
			)
		}
	}
	if !validDottedKey(key) {
		return KeyMatch{}, false, nil
	}

	for i, field := range fields {
		if field.Key == key {
			return KeyMatch{Field: field, Owner: segmentOwner(fields, i), Kind: field.Kind}, true, nil
		}
	}
	// Structural parents of registry rows are real mapping keys too (`project`,
	// `agent`, `dispatch`, ...), even though the registry models their children as
	// separate override units.
	for i, field := range fields {
		if strings.HasPrefix(field.Key, key+".") {
			return KeyMatch{Field: field, Owner: segmentOwner(fields, i), Kind: configvalue.KindMapping}, true, nil
		}
	}

	switch {
	case len(parts) == 3 && parts[0] == "agent" && parts[1] == "profiles" &&
		contains(agent.RoleNames(), parts[2]):
		return dynamicMatch(fields, "agent.profiles", configvalue.KindMapping)

	case len(parts) == 4 && parts[0] == "agent" && parts[1] == "profiles" &&
		contains(agent.RoleNames(), parts[2]) && contains([]string{"provider", "model", "effort"}, parts[3]):
		return dynamicMatch(fields, "agent.profiles", configvalue.KindString)

	case len(parts) == 2 && parts[0] == "providers":
		return dynamicMatch(fields, "providers", configvalue.KindMapping)

	case len(parts) == 3 && parts[0] == "providers" &&
		contains([]string{"interactive_command", "headless_command"}, parts[2]):
		return dynamicMatch(fields, "providers", configvalue.KindString)

	case len(parts) == 3 && parts[0] == "providers" && parts[2] == "profiles":
		return dynamicMatch(fields, "providers", configvalue.KindMapping)

	case len(parts) == 4 && parts[0] == "providers" && parts[2] == "profiles" && contains(agent.RoleNames(), parts[3]):
		return dynamicMatch(fields, "providers", configvalue.KindMapping)

	case len(parts) == 5 && parts[0] == "providers" && parts[2] == "profiles" &&
		contains(agent.RoleNames(), parts[3]) && contains([]string{"model", "effort"}, parts[4]):
		return dynamicMatch(fields, "providers", configvalue.KindString)

	case len(parts) == 2 && parts[0] == "stage_hooks" && contains(agent.StageNames(), parts[1]):
		return dynamicMatch(fields, "stage_hooks", configvalue.KindMapping)

	case len(parts) == 3 && parts[0] == "stage_hooks" &&
		contains(agent.StageNames(), parts[1]) && contains([]string{"pre", "post"}, parts[2]):
		return dynamicMatch(fields, "stage_hooks", configvalue.KindString)
	}

	return KeyMatch{}, false, nil
}

func dynamicMatch(fields []Field, fieldKey string, kind configvalue.Kind) (KeyMatch, bool, error) {
	for i, field := range fields {
		if field.Key == fieldKey {
			return KeyMatch{Field: field, Owner: segmentOwner(fields, i), Kind: kind}, true, nil
		}
	}
	return KeyMatch{}, false, fmt.Errorf("configref: dynamic key owner %q is missing from the registry", fieldKey)
}

func segmentOwner(fields []Field, index int) Field {
	if fields[index].Segment != "" {
		return fields[index]
	}
	top := topLevel(fields[index].Key)
	for i := index - 1; i >= 0; i-- {
		if topLevel(fields[i].Key) != top {
			break
		}
		if fields[i].Segment != "" {
			return fields[i]
		}
	}
	return fields[index]
}

func validDottedKey(key string) bool {
	if key == "" || key != strings.TrimSpace(key) {
		return false
	}
	parts := strings.Split(key, ".")
	for index, part := range parts {
		if part == "" {
			return false
		}
		// Provider names are user-defined map keys, not schema identifiers. Keep
		// the surrounding providers/profiles/role/leaf axes strict while accepting
		// any canonical unquoted segment on this one dynamic axis.
		if len(parts) >= 2 && parts[0] == "providers" && index == 1 {
			if !validProviderName(part) {
				return false
			}
			continue
		}
		for i := 0; i < len(part); i++ {
			c := part[i]
			letter := c >= 'A' && c <= 'Z' || c >= 'a' && c <= 'z'
			if letter || c == '_' || (i > 0 && (c >= '0' && c <= '9' || c == '-')) {
				continue
			}
			return false
		}
	}
	return true
}

func validProviderName(name string) bool {
	return invalidProviderName(name) == ""
}

// invalidProviderName keeps the dotted CLI grammar unambiguous. Provider names
// remain opaque (digits, bool-like words, a leading hyphen, and Unicode are all
// accepted); the mutation writer quotes their on-disk YAML key when needed.
func invalidProviderName(name string) string {
	if name == "" {
		return "the name is empty"
	}
	if name != strings.TrimSpace(name) {
		return "leading or trailing whitespace requires quoting"
	}
	for _, r := range name {
		if unicode.IsSpace(r) || unicode.IsControl(r) {
			return "whitespace and control characters require quoting"
		}
		// Dots are path separators. The remaining characters are YAML indicators
		// or quoted/escaped spellings that would make the dotted input ambiguous.
		if strings.ContainsRune(".:,[]{}#&*!|>'\"%@`\\", r) {
			return fmt.Sprintf("character %q requires quoting", r)
		}
	}
	return ""
}

func contains(values []string, want string) bool {
	for _, value := range values {
		if value == want {
			return true
		}
	}
	return false
}

func topLevel(key string) string {
	if i := strings.IndexByte(key, '.'); i >= 0 {
		return key[:i]
	}
	return key
}

// FieldsForKey returns every registry row represented by the requested key's
// owning rendered segment, in registry order. This is the keyed JSON explain
// projection; a one-row segment returns a one-element slice.
func FieldsForKey(key string) ([]Field, error) {
	match, ok, err := ResolveKey(key)
	if err != nil {
		return nil, err
	}
	if !ok {
		return nil, fmt.Errorf("unknown config key %q", key)
	}
	fields, err := Fields()
	if err != nil {
		return nil, err
	}
	var out []Field
	started := false
	for _, field := range fields {
		if field.Key == match.Owner.Key {
			started = true
		}
		if !started {
			continue
		}
		if len(out) > 0 && field.Segment != "" {
			break
		}
		out = append(out, field)
	}
	return out, nil
}

// RenderKey returns only the owning YAML segment for key.
func RenderKey(key string) (string, error) {
	match, ok, err := ResolveKey(key)
	if err != nil {
		return "", err
	}
	if !ok || match.Owner.Segment == "" {
		return "", fmt.Errorf("unknown config key %q", key)
	}
	return match.Owner.Segment + "\n", nil
}

// RenderJSONKey returns the rows represented by key's owning segment using the
// same deterministic object shape as RenderJSON.
func RenderJSONKey(key string) (string, error) {
	fields, err := FieldsForKey(key)
	if err != nil {
		return "", err
	}
	return renderJSONFields(fields)
}

// FieldKeys returns the dotted key paths of every registry row, in table order.
// Used by the JSON/YAML key-parity guard and any external consumer needing the
// documented key set.
func FieldKeys() ([]string, error) {
	fields, err := Fields()
	if err != nil {
		return nil, err
	}
	keys := make([]string, len(fields))
	for i, f := range fields {
		keys[i] = f.Key
	}
	return keys, nil
}

// InitSeedKeys returns the dotted keys of the A-class IDENTITY fields written live
// at `fab config init --project` time (InitSeed rows), in table order. These are
// the only fields the init generator emits above the managed fence; everything
// else is fence territory from day one. Used by the init generator and its tests.
func InitSeedKeys() ([]string, error) {
	fields, err := Fields()
	if err != nil {
		return nil, err
	}
	var keys []string
	for _, f := range fields {
		if f.InitSeed {
			keys = append(keys, f.Key)
		}
	}
	return keys, nil
}

// Render returns the fully-commented reference config.yaml, generated by walking
// the field registry: the fixed header followed by each row's rendered Segment in
// table order, one blank line between blocks. The output is byte-stable for a
// given binary version and is what `fab config explain` prints to stdout. It
// returns an error rather than emitting partial/degraded output if an invariant
// breaks (Fields surfaces the role-map drift and the registry lint), so a future
// edit that breaks an invariant fails loudly instead of silently shipping a
// malformed reference.
//
// The emitted text is contract-equivalent to the pre-metadata-table renderer
// (same key coverage, live/commented split, and every documented-semantics prose
// block the tests assert verbatim) — the restructure changed the SOURCE of the
// reference (prose template → metadata table walked here), not its output
// contract.
func Render() (string, error) {
	fields, err := Fields()
	if err != nil {
		return "", err
	}
	var b strings.Builder
	b.WriteString(referenceHeader)
	for _, f := range fields {
		if f.Segment == "" {
			// A field rendered inside another field's block (e.g. project.description
			// / project.linear_workspace live in the project.name segment) carries no
			// segment of its own — skip it in the walk.
			continue
		}
		b.WriteString("\n\n")
		b.WriteString(f.Segment)
	}
	b.WriteString("\n")
	return b.String(), nil
}

// RenderJSON returns the field registry as a machine-readable JSON array — the
// tooling surface Changes 2-3 and external tools consume. It is a flat array in
// table (rendering) order, each element a per-field object
// {key, default, description, scope, advertise, renamed_from(omitempty)}.
// Deterministic and byte-stable like Render(): the table is ordered and the
// marshalling is stable. Two-space indented with a trailing newline. Segment is
// excluded — it is the YAML rendering, not part of the machine-readable schema.
func RenderJSON() (string, error) {
	fields, err := Fields()
	if err != nil {
		return "", err
	}
	return renderJSONFields(fields)
}

func renderJSONFields(fields []Field) (string, error) {
	view := make([]jsonField, len(fields))
	for i, f := range fields {
		view[i] = jsonField{
			Key:         f.Key,
			Default:     f.Default,
			Description: f.Description,
			Scope:       f.Scope,
			Advertise:   f.Advertise,
			RenamedFrom: f.RenamedFrom,
		}
	}
	var buf bytes.Buffer
	enc := json.NewEncoder(&buf)
	enc.SetIndent("", "  ")
	enc.SetEscapeHTML(false)
	if err := enc.Encode(view); err != nil {
		return "", fmt.Errorf("configref: marshalling reference JSON: %w", err)
	}
	return buf.String(), nil
}
