package memoryindex

import "strings"

const (
	curatedStart    = "<!-- fab docs-index:curated:start -->"
	curatedEnd      = "<!-- fab docs-index:curated:end -->"
	tombstoneMarker = "<!-- fab docs-index:historical -->"
)

// curatedNavigation recognizes first-run hand-curated navigation and the
// explicit seed region kept on subsequent runs. Old generated indexes never
// seed themselves: removing a source description still trips the loss guard.
func curatedNavigation(existing string) (string, bool) {
	if a := strings.Index(existing, curatedStart); a >= 0 {
		if b := strings.Index(existing[a:], curatedEnd); b >= 0 {
			return existing[a+len(curatedStart) : a+b], false
		}
	}
	if strings.Contains(existing, "Generated by `fab ") || strings.Contains(existing, GeneratedStart) {
		return "", false
	}
	if len(parseIndexRows(existing)) == 0 && len(parseStructuralHeadings(existing)) == 0 {
		return "", false
	}
	body := stripFrontmatter(existing)
	lines := strings.Split(body, "\n")
	for i, l := range lines {
		if strings.HasPrefix(l, "# ") {
			lines = append(lines[:i], lines[i+1:]...)
			break
		}
	}
	return strings.TrimSpace(strings.Join(lines, "\n")), true
}

// adoptNavigation updates imported table rows in place so their custom sections
// and surrounding prose survive. Existing descriptions seed missing values only
// within this explicitly marked region. First-run historical rows are retained
// visibly; newly removed live rows are dropped and detected by Classify.
func adoptNavigation(existing, rendered string, exists, superseded func(string) bool) string {
	curated, first := curatedNavigation(existing)
	if curated == "" {
		return rendered
	}
	generated := rowsByTarget(parseIndexRows(rendered))
	used := map[string]bool{}
	lines := strings.Split(strings.Trim(curated, "\n"), "\n")
	var out []string
	for _, line := range lines {
		rows := parseIndexRows(line)
		if len(rows) == 0 {
			out = append(out, line)
			continue
		}
		row := rows[0]
		if superseded(row.Target) {
			continue
		}
		if next, ok := generated[row.Target]; ok {
			used[row.Target] = true
			if next.Description == missingCell || next.Description == "" {
				out = append(out, line)
				continue
			}
			if next.Description == row.Description {
				out = append(out, line)
				continue
			}
			// Preserve the curated label and extra columns; only the routing description
			// changes when its source now supplies one.
			cells := splitTableRow(strings.TrimSpace(line))
			if len(cells) > 1 {
				cells[1] = next.Description
			}
			out = append(out, "| "+strings.Join(cells, " | ")+" |")
			continue
		}
		_, local := relMemoryTarget("", row.Target)
		if !local || strings.Contains(line, tombstoneMarker) {
			out = append(out, line)
			continue
		}
		if exists(row.Target) {
			out = append(out, line)
			continue
		}
		if first && !exists(row.Target) {
			out = append(out, line+" "+tombstoneMarker)
			continue
		}
		// Existing targets omitted intentionally (e.g. superseded status) are folded
		// into generated summaries; removed live rows are left to the loss guard.
	}
	// Remove imported rows from the normal generated tables, leaving newly
	// discovered content there. The whole file remains a deterministic projection.
	var rest []string
	for _, line := range strings.Split(rendered, "\n") {
		rows := parseIndexRows(line)
		if len(rows) > 0 && used[rows[0].Target] {
			continue
		}
		rest = append(rest, line)
	}
	generatedRest := strings.TrimRight(strings.Join(rest, "\n"), "\n")
	boundary := strings.Index(generatedRest, "| ")
	if boundary < 0 {
		boundary = len(generatedRest)
	}
	return generatedRest[:boundary] + curatedStart + "\n" + strings.Join(out, "\n") + "\n" + curatedEnd + "\n\n" + generatedRest[boundary:] + "\n"
}
