package memoryindex

import "strings"

const (
	manualStart     = "<!-- fab docs-index:manual:start -->"
	manualEnd       = "<!-- fab docs-index:manual:end -->"
	tombstoneMarker = "<!-- fab docs-index:historical -->"
)

// The legacy marker spelling, recognized on READ for one version; only the
// manual spelling is ever written. Dropping recognition is a follow-up for the
// next minor after the rename ships.
const (
	legacyCuratedStart = "<!-- fab docs-index:curated:start -->"
	legacyCuratedEnd   = "<!-- fab docs-index:curated:end -->"
)

// manualBlockSeed is the agent-facing comment written when the generator
// CREATES a manual block. An existing block's content is preserved verbatim —
// the comment is content the adoption loop passes through, not scaffolding
// re-emitted every run.
const manualBlockSeed = "<!-- Hand-managed rows (non-markdown descriptions, external links, groupings) — preserved verbatim. -->"

// manualNavigation finds the hand-managed navigation in an existing landing:
// the explicit block (either spelling — manual first, then the legacy curated
// pair) or, on a first run, the pre-existing hand-written rows imported as the
// seed. Old generated indexes never seed themselves: removing a source
// description still trips the loss guard.
func manualNavigation(existing string) (string, bool) {
	for _, pair := range [][2]string{{manualStart, manualEnd}, {legacyCuratedStart, legacyCuratedEnd}} {
		if a := strings.Index(existing, pair[0]); a >= 0 {
			if b := strings.Index(existing[a:], pair[1]); b >= 0 {
				return existing[a+len(pair[0]) : a+b], false
			}
		}
	}
	if strings.Contains(existing, "Generated by `fab ") || strings.Contains(existing, GeneratedStart) {
		return "", false
	}
	if len(parseIndexRows(existing)) == 0 && len(parseStructuralHeadings(existing)) == 0 {
		return "", false
	}
	body := stripFrontmatter(existing)
	lines := strings.Split(body, "\n")
	for i, l := range lines {
		if strings.HasPrefix(l, "# ") {
			lines = append(lines[:i], lines[i+1:]...)
			break
		}
	}
	return strings.TrimSpace(strings.Join(lines, "\n")), true
}

// adoptNavigation updates imported table rows in place so their custom sections
// and surrounding prose survive. Existing descriptions seed missing values only
// within this explicitly marked region. First-run historical rows are retained
// visibly; newly removed live rows are dropped and detected by Classify.
// Every primary landing carries the block: when the landing had none (and
// first-run seed import found nothing to import), the block is created and
// seeded with the agent-facing comment.
func adoptNavigation(existing, rendered string, exists, superseded func(string) bool) string {
	manual, first := manualNavigation(existing)
	if manual == "" && !strings.Contains(existing, manualStart) && !strings.Contains(existing, legacyCuratedStart) {
		return withManualBlock(rendered, manualBlockSeed)
	}
	generated := rowsByTarget(parseIndexRows(rendered))
	used := map[string]bool{}
	lines := strings.Split(strings.Trim(manual, "\n"), "\n")
	var out []string
	for _, line := range lines {
		rows := parseIndexRows(line)
		if len(rows) == 0 {
			out = append(out, line)
			continue
		}
		row := rows[0]
		if superseded(row.Target) {
			continue
		}
		if next, ok := generated[row.Target]; ok {
			used[row.Target] = true
			if next.Description == missingCell || next.Description == "" {
				out = append(out, line)
				continue
			}
			if next.Description == row.Description {
				out = append(out, line)
				continue
			}
			// Preserve the hand-written label and extra columns; only the routing
			// description changes when its source now supplies one.
			cells := splitTableRow(strings.TrimSpace(line))
			if len(cells) > 1 {
				cells[1] = next.Description
			}
			out = append(out, "| "+strings.Join(cells, " | ")+" |")
			continue
		}
		_, local := relMemoryTarget("", row.Target)
		if !local || strings.Contains(line, tombstoneMarker) {
			out = append(out, line)
			continue
		}
		if exists(row.Target) {
			out = append(out, line)
			continue
		}
		if first && !exists(row.Target) {
			out = append(out, line+" "+tombstoneMarker)
			continue
		}
		// Existing targets omitted intentionally (e.g. superseded status) are folded
		// into generated summaries; removed live rows are left to the loss guard.
	}
	// Remove imported rows from the normal generated tables, leaving newly
	// discovered content there. The whole file remains a deterministic projection.
	var rest []string
	for _, line := range strings.Split(rendered, "\n") {
		rows := parseIndexRows(line)
		if len(rows) > 0 && used[rows[0].Target] {
			continue
		}
		rest = append(rest, line)
	}
	return withManualBlock(strings.Join(rest, "\n"), strings.Join(out, "\n"))
}

// withManualBlock inserts the manual block (markers + body, always the new
// spelling) into a rendered primary landing immediately before the first
// table — after the "Generated by" note and any nav_note.
func withManualBlock(rendered, body string) string {
	rest := strings.TrimRight(rendered, "\n")
	boundary := tableBoundary(rest)
	return rest[:boundary] + manualStart + "\n" + body + "\n" + manualEnd + "\n\n" + rest[boundary:] + "\n"
}

// tableBoundary returns the byte offset where the first table begins — the
// first line starting with "| ". Anchoring to a line start keeps a "| "
// sequence inside nav_note prose (free-form markdown) from hijacking the
// boundary; no table at all returns the end.
func tableBoundary(rendered string) int {
	if strings.HasPrefix(rendered, "| ") {
		return 0
	}
	if i := strings.Index(rendered, "\n| "); i >= 0 {
		return i + 1
	}
	return len(rendered)
}
