package memoryindex

import (
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"github.com/sahil87/fab-kit/src/go/fab/internal/config"
	"github.com/sahil87/fab-kit/src/go/fab/internal/frontmatter"
)

const (
	GeneratedStart         = "<!-- fab docs-index:generated:start -->"
	GeneratedEnd           = "<!-- fab docs-index:generated:end -->"
	KindMissingDescription = "missing-description"
)

// Target is one deterministic write or removal and its matching loss-check input.
type Target struct {
	Path    string
	Content string
	IsLog   bool
	IsRoot  bool
	Remove  bool
	// SupersededCleanup retires tool-owned output under an explicit superseded
	// boundary. This intentional removal is benign drift in --check.
	SupersededCleanup bool
}

type docFolder struct {
	dir, landing, existing string
	data                   DomainData
	children               []*docFolder
	superseded             bool
	count, supersededFiles int
}

type docWalk struct {
	repo, root string
	cfg        config.DocsIndexRoot
	reg        map[string]changeMeta
	warnings   []Warning
}

// GatherRoot gathers an arbitrary documentation root without mutating anything.
// The same targets feed check and write, including first-run seed adoption.
func GatherRoot(repo, fabRoot string, cfg config.DocsIndexRoot, rebuild bool) ([]Target, []Warning, error) {
	if err := validateGlobs(cfg.Superseded); err != nil {
		return nil, nil, err
	}
	w := docWalk{repo: repo, root: filepath.Join(repo, filepath.FromSlash(cfg.Path)), cfg: cfg}
	if cfg.Log {
		w.reg = gatherChangeRegistry(fabRoot)
	}
	tree, err := w.walk(w.root, false, 0)
	if err != nil {
		return nil, nil, fmt.Errorf("%s: %w", cfg.Path, err)
	}
	var targets []Target
	var dates *gitDates
	if cfg.Log {
		dates = loadGitDatesForRoot(repo, cfg.Path)
	}
	var emit func(*docFolder, bool) error
	emit = func(f *docFolder, isRoot bool) error {
		content, err := w.renderFolder(f, isRoot)
		if err != nil {
			return fmt.Errorf("%s: %w", f.dir, err)
		}
		targets = append(targets, Target{Path: filepath.Join(f.dir, f.landing), Content: content, IsRoot: isRoot})
		if cfg.Log && !f.superseded && !isRoot {
			if t, ok := buildLogTarget(repo, dates, w.reg, f.dir, relOrBase(w.root, f.dir), f.data.Title, rebuild, append([]string{cfg.IndexFile}, cfg.AlsoAccept...)...); ok {
				targets = append(targets, Target{Path: t.Path, Content: t.Content, IsLog: true})
			}
		}
		if f.superseded {
			cleanup, err := w.supersededCleanup(f, false)
			if err != nil {
				return err
			}
			targets = append(targets, cleanup...)
		} else {
			for _, c := range f.children {
				if err := emit(c, false); err != nil {
					return err
				}
			}
		}
		return nil
	}
	if err := emit(tree, true); err != nil {
		return nil, nil, err
	}
	sortWarnings(w.warnings)
	return targets, w.warnings, nil
}

// supersededCleanup removes only recognizable generated output: whole primary
// landings/logs and the owned blocks in alternate landings. Human prose, seeds,
// topic files, and symlinks are never removed. The boundary keeps its own index.
func (w *docWalk) supersededCleanup(f *docFolder, descendant bool) ([]Target, error) {
	var targets []Target
	names := []string{}
	if descendant {
		names = append(names, w.cfg.IndexFile)
		names = append(names, w.cfg.AlsoAccept...)
	}
	if w.cfg.Log {
		names = append(names, "log.md")
	}
	seen := map[string]bool{}
	for _, name := range names {
		if seen[name] {
			continue
		}
		seen[name] = true
		p := filepath.Join(f.dir, name)
		st, err := os.Lstat(p)
		if os.IsNotExist(err) {
			continue
		}
		if err != nil {
			return nil, err
		}
		if !st.Mode().IsRegular() {
			continue
		}
		data, err := os.ReadFile(p)
		if err != nil {
			return nil, err
		}
		existing := string(data)
		t := Target{Path: p, IsLog: name == "log.md", SupersededCleanup: true}
		if name != w.cfg.IndexFile && !t.IsLog {
			if !strings.Contains(existing, GeneratedStart) && !strings.Contains(existing, GeneratedEnd) {
				continue
			}
			if _, err := replaceGeneratedBlock(existing, ""); err != nil {
				return nil, fmt.Errorf("%s: %w", p, err)
			}
			start, end := strings.Index(existing, GeneratedStart), strings.Index(existing, GeneratedEnd)
			t.Content = existing[:start] + existing[end+len(GeneratedEnd):]
		} else {
			header := "> **Generated by `fab "
			if t.IsLog {
				header = "<!-- Generated by `fab "
			}
			if !strings.Contains(existing, header+"docs-index`") && !strings.Contains(existing, header+"memory-index`") {
				continue
			}
			t.Remove = true
		}
		targets = append(targets, t)
	}
	for _, child := range f.children {
		cleanup, err := w.supersededCleanup(child, true)
		if err != nil {
			return nil, err
		}
		targets = append(targets, cleanup...)
	}
	return targets, nil
}

func (w *docWalk) landing(dir string) string {
	for _, name := range append([]string{w.cfg.IndexFile}, w.cfg.AlsoAccept...) {
		if st, err := os.Stat(filepath.Join(dir, name)); err == nil && !st.IsDir() {
			return name
		}
	}
	return w.cfg.IndexFile
}
func (w *docWalk) isTopic(name string) bool {
	if !strings.HasSuffix(name, ".md") || name == w.cfg.IndexFile {
		return false
	}
	for _, a := range w.cfg.AlsoAccept {
		if name == a {
			return false
		}
	}
	return !w.cfg.Log || name != "log.md" && name != seedFileName
}

func (w *docWalk) walk(dir string, inherited bool, depth int) (*docFolder, error) {
	entries, err := os.ReadDir(dir)
	if err != nil {
		return nil, err
	}
	f, err := w.readFolder(dir, inherited)
	if err != nil {
		return nil, err
	}
	depthWarned := false
	for _, e := range entries {
		// Do not follow symlinks: navigation generation must stay within its root.
		if e.Type()&os.ModeSymlink != 0 {
			continue
		}
		p := filepath.Join(dir, e.Name())
		if e.IsDir() {
			child, err := w.walk(p, f.superseded, depth+1)
			if err != nil {
				return nil, err
			}
			// Retain top-level empty memory domains for legacy byte compatibility.
			if child.count == 0 && child.existing == "" && !child.superseded && !(w.cfg.Log && depth == 0) {
				continue
			}
			f.children = append(f.children, child)
			f.count += child.count
			continue
		}
		if !w.isTopic(e.Name()) {
			continue
		}
		f.count++
		if f.superseded || supersededPath(w.cfg.Superseded, relOrBase(w.root, p)) {
			f.supersededFiles++
			continue
		}
		w.readTopic(f, p)
		if depth+1 > w.cfg.MaxDepth && !depthWarned {
			w.warnings = append(w.warnings, Warning{Path: relOrBase(w.repo, dir), Kind: KindDepth, Depth: depth + 1, Limit: w.cfg.MaxDepth})
			depthWarned = true
		}
	}
	w.finishFolder(f, depth)
	return f, nil
}
func (f *docFolder) rowDescription() string {
	if f.superseded {
		return supersededSummary(f.children, f.count)
	}
	desc := f.data.Description
	if f.supersededFiles > 0 {
		if desc != "" {
			desc += " — "
		}
		desc += fmt.Sprintf("%d superseded files", f.supersededFiles)
	}
	return desc
}

func indexBody(content string) string {
	lines := strings.Split(content, "\n")
	for i, l := range lines {
		if strings.HasPrefix(l, "| ") {
			return strings.Join(lines[i:], "\n")
		}
	}
	return ""
}
func replaceGeneratedBlock(existing, body string) (string, error) {
	start, end := strings.Index(existing, GeneratedStart), strings.Index(existing, GeneratedEnd)
	if (start < 0) != (end < 0) || start >= 0 && (end < start || strings.Count(existing, GeneratedStart) != 1 || strings.Count(existing, GeneratedEnd) != 1) {
		return "", fmt.Errorf("malformed docs-index generated block; restore matching markers")
	}
	block := GeneratedStart + "\n" + body + GeneratedEnd
	if start >= 0 {
		return existing[:start] + block + existing[end+len(GeneratedEnd):], nil
	}
	separator := "\n\n"
	if existing == "" {
		separator = ""
	} else if strings.HasSuffix(existing, "\n") {
		separator = "\n"
	}
	return existing + separator + block + "\n", nil
}

// Alternate landings keep their original rows outside the generated block. Those
// human-owned rows are the seed source, never the generated block itself.
func seedAlternateBody(existing, body string) string {
	if start, end := strings.Index(existing, GeneratedStart), strings.Index(existing, GeneratedEnd); start >= 0 && end > start {
		existing = existing[:start] + existing[end+len(GeneratedEnd):]
	}
	seeds := rowsByTarget(parseIndexRows(existing))
	lines := strings.Split(body, "\n")
	for i, line := range lines {
		rows := parseIndexRows(line)
		if len(rows) == 0 {
			continue
		}
		r := rows[0]
		if seed, ok := seeds[r.Target]; ok && r.Description == missingCell {
			cells := splitTableRow(line)
			if len(cells) > 1 {
				cells[1] = seed.Description
				lines[i] = "| " + strings.Join(cells, " | ") + " |"
			}
		}
	}
	return strings.Join(lines, "\n")
}

func (w *docWalk) isSupersededTarget(dir, target string) bool {
	if strings.Contains(target, "://") || strings.HasPrefix(target, "/") {
		return false
	}
	target = strings.SplitN(target, "#", 2)[0]
	rel := relOrBase(w.root, filepath.Join(dir, filepath.FromSlash(target)))
	for rel != "." && rel != "" {
		if supersededPath(w.cfg.Superseded, rel) {
			return true
		}
		next := filepath.ToSlash(filepath.Dir(rel))
		if next == rel {
			break
		}
		rel = next
	}
	return false
}

func sortWarnings(warnings []Warning) {
	sort.Slice(warnings, func(i, j int) bool {
		a, b := warnings[i], warnings[j]
		if a.Path != b.Path {
			return a.Path < b.Path
		}
		if a.Kind != b.Kind {
			return a.Kind < b.Kind
		}
		return a.Detail < b.Detail
	})
}

func (w *docWalk) renderFolder(f *docFolder, isRoot bool) (string, error) {
	legacyRoot := isRoot && w.cfg.Log && w.cfg.Path == "docs/memory" && w.cfg.IndexFile == "index.md" && len(w.cfg.AlsoAccept) == 0
	content := RenderDomain(f.data)
	if legacyRoot {
		root := RootData{NavNote: w.cfg.NavNote}
		for _, c := range f.children {
			root.Domains = append(root.Domains, DomainRow{Name: c.data.Name, Description: c.rowDescription(), Link: c.data.Name + "/" + c.landing})
		}
		content = RenderRoot(root)
	}
	if isRoot && w.cfg.Log && !legacyRoot {
		if strings.HasPrefix(content, "---\n") {
			content = strings.Replace(content, "---\n", "---\nfkf_version: \"0.1\"\n", 1)
		} else {
			content = rootFrontmatter + content
		}
	}
	// A configured nav_note on a generic root lands on the root landing, right
	// after the "Generated by" note; unset/empty renders nothing. (Primary
	// landings only — an alternate landing's prose outside the generated block
	// is human-owned, so the note has no anchor there.)
	if isRoot && !legacyRoot && f.landing == w.cfg.IndexFile && w.cfg.NavNote != nil && *w.cfg.NavNote != "" {
		content = insertNavNote(content, *w.cfg.NavNote)
	}
	if f.landing != w.cfg.IndexFile {
		body := indexBody(content)
		if !f.superseded {
			body = seedAlternateBody(f.existing, body)
		}
		return replaceGeneratedBlock(f.existing, body)
	} else {
		content = adoptNavigation(f.existing, content, func(target string) bool {
			_, e := os.Stat(filepath.Join(f.dir, filepath.FromSlash(target)))
			return e == nil
		}, func(target string) bool { return w.isSupersededTarget(f.dir, target) })
	}
	return content, nil
}

// insertNavNote inserts note (followed by a blank line) immediately after the
// "Generated by" note in a rendered landing. A content without that note is
// returned unchanged (defensive — RenderDomain always emits it).
func insertNavNote(content, note string) string {
	const generatedBy = "> **Generated by `fab docs-index`**"
	i := strings.Index(content, generatedBy)
	if i < 0 {
		return content
	}
	end := strings.Index(content[i:], "\n\n")
	if end < 0 {
		return content
	}
	at := i + end + 2
	return content[:at] + note + "\n\n" + content[at:]
}

func (w *docWalk) readFolder(dir string, inherited bool) (*docFolder, error) {
	f := &docFolder{dir: dir, landing: w.landing(dir), superseded: inherited || supersededPath(w.cfg.Superseded, relOrBase(w.root, dir))}
	if f.superseded && f.landing != w.cfg.IndexFile {
		data, e := os.ReadFile(filepath.Join(dir, f.landing))
		if e != nil && !os.IsNotExist(e) {
			return nil, e
		}
		f.existing = string(data)
	}
	f.data = DomainData{Generic: !w.cfg.Log || w.cfg.Path != "docs/memory" || w.cfg.IndexFile != "index.md" || len(w.cfg.AlsoAccept) > 0 || len(w.cfg.Superseded) > 0, Name: filepath.Base(dir), Title: titleCase(filepath.Base(dir)) + " Documentation"}
	if !f.superseded {
		landing := filepath.Join(dir, f.landing)
		data, e := os.ReadFile(landing)
		if e != nil && !os.IsNotExist(e) {
			return nil, e
		}
		f.existing = string(data)
		if title := readH1(landing); title != "" {
			f.data.Title = title
		}
		f.data.Description = frontmatter.Field(landing, "description")
		w.warnings = append(w.warnings, sourceWarnings(w.root, landing, relOrBase(w.repo, landing), w.reg, w.cfg.Log, true)...)
	}

	return f, nil
}

func (w *docWalk) readTopic(f *docFolder, p string) {
	desc := frontmatter.Field(p, "description")
	label := strings.TrimSuffix(filepath.Base(p), ".md")
	title := readH1(p)
	if desc == "" {
		w.warnings = append(w.warnings, Warning{Path: relOrBase(w.repo, p), Kind: KindMissingDescription})
		if title != "" && f.data.Generic {
			label = title
		}
	}
	f.data.Files = append(f.data.Files, FileEntry{Base: strings.TrimSuffix(filepath.Base(p), ".md"), Title: title, Description: desc, Label: label})
	w.warnings = append(w.warnings, sourceWarnings(w.root, p, relOrBase(w.repo, p), w.reg, w.cfg.Log, false)...)

}

func (w *docWalk) finishFolder(f *docFolder, depth int) {
	if f.superseded {
		// Count-only below this boundary: no topic or landing descriptions are read.
		for _, c := range f.children {
			f.data.Files = append(f.data.Files, FileEntry{Base: c.data.Name, Label: c.data.Name + "/", Link: c.data.Name + "/", Description: fmt.Sprintf("Superseded — %d files", c.count)})
		}
	} else {
		for _, c := range f.children {
			row := c.data
			row.Description = c.rowDescription()
			row.Link = c.data.Name + "/" + c.landing
			f.data.SubDomains = append(f.data.SubDomains, row)
		}
		width := len(f.data.Files)
		if width > WidthWarnThreshold && !(w.cfg.Log && depth == 1 && reservedDomains[f.data.Name]) {
			w.warnings = append(w.warnings, Warning{Path: relOrBase(w.repo, f.dir), Kind: KindWidth, Count: width})
		}
		if w.cfg.Log && depth == 1 && f.data.Name == "_unsorted" && width > 0 {
			w.warnings = append(w.warnings, Warning{Path: relOrBase(w.repo, f.dir), Kind: KindUnsorted, Count: width})
		}
		if depth == 0 && f.supersededFiles > 0 {
			f.data.Note = fmt.Sprintf("%d superseded files", f.supersededFiles)
		}
	}
	sort.Slice(f.data.Files, func(i, j int) bool { return f.data.Files[i].Base < f.data.Files[j].Base })

}
