package memoryindex

// Full-document golden tests for the generated memory indexes (260612-tb6f,
// F41). Byte-stability is a documented property of `fab docs-index` (re-running
// over an unchanged tree writes nothing). The existing
// tests assert determinism and suffixes; these pin the complete document
// bytes so any rendering or serialization change that would churn every
// generated index in user repos fails loudly here first.

import "testing"

func TestGolden_RenderRoot_FullDocument(t *testing.T) {
	got := RenderRoot(RootData{Domains: []DomainRow{
		{Name: "auth", Description: "Authentication & session handling"},
		{Name: "billing", Description: ""}, // missing description degrades
	}})
	want := "---\n" +
		"fkf_version: \"0.1\"\n" +
		"---\n" +
		"# Memory Index\n" +
		"\n" +
		"> **Memory files are post-implementation artifacts** — what actually *happened*. They are the\n" +
		"> authoritative source of truth for system behavior and design decisions, maintained by\n" +
		"> `/fab-continue` (hydrate) after each change is completed.\n" +
		">\n" +
		"> Contrast with [`docs/specs/index.md`](../specs/index.md): specs are *pre-implementation* —\n" +
		"> what you planned. Specs capture conceptual design intent and are human-curated.\n" +
		"\n" +
		"> **Generated by `fab docs-index`** — everything outside the manual block below is\n" +
		"> regenerated from the tree and each file's own metadata (`description:` frontmatter,\n" +
		"> HTML `<title>`/`<meta name=\"description\">`): don't edit it, re-run the command. The manual\n" +
		"> block is the one hand-managed region: edit it, it is preserved verbatim.\n" +
		"\n" +
		"| Domain | Description |\n" +
		"|--------|-------------|\n" +
		"| [auth](auth/index.md) | Authentication & session handling |\n" +
		"| [billing](billing/index.md) | — |\n"
	if got != want {
		t.Errorf("RenderRoot full-document golden mismatch.\n--- got ---\n%s\n--- want ---\n%s", got, want)
	}
}

func TestGolden_RenderDomain_FullDocument(t *testing.T) {
	got := RenderDomain(DomainData{
		Name:        "auth",
		Title:       "Auth Documentation",
		Description: "Authentication & session handling",
		Files: []FileEntry{
			{Base: "login-flow", Description: "Login + MFA flow"},
			{Base: "sessions", Description: ""}, // description degrades
		},
		SubDomains: []DomainData{
			{Name: "tokens", Description: "Token issuance & rotation"},
		},
	})
	want := "---\n" +
		"description: \"Authentication & session handling\"\n" +
		"---\n" +
		"# Auth Documentation\n" +
		"\n" +
		"> **Generated by `fab docs-index`** — everything outside the manual block below is regenerated from the tree and each file's own metadata (`description:` frontmatter, HTML `<title>`/`<meta name=\"description\">`): don't edit it, re-run the command. The manual block is the one hand-managed region: edit it, it is preserved verbatim.\n" +
		"\n" +
		"| File | Description |\n" +
		"|------|-------------|\n" +
		"| [login-flow](login-flow.md) | Login + MFA flow |\n" +
		"| [sessions](sessions.md) | — |\n" +
		"\n" +
		"## Sub-Domains\n" +
		"\n" +
		"| Sub-Domain | Description |\n" +
		"|------------|-------------|\n" +
		"| [tokens](tokens/index.md) | Token issuance & rotation |\n"
	if got != want {
		t.Errorf("RenderDomain full-document golden mismatch.\n--- got ---\n%s\n--- want ---\n%s", got, want)
	}
}
