package memoryindex

// FKF per-folder log.md generation (C-lite, docs/specs/fkf.md §6).
//
// A log.md records one folder's change history, assembled from two sources that
// no agent hand-edits: git history (the *when* / *which file* / *change-id*,
// keyed to the folder) joined with each change's `.status.yaml` `summary:` (the
// *what*). The render is a pure function of gathered inputs (LogData) — mirroring
// RenderRoot/RenderDomain — so the output is byte-stable / idempotent, the same
// single-writer discipline as index.md.
//
// This file holds the pure half (RenderLog + verb derivation + the commit→change
// attribution rule, which is pure over a gathered registry). The I/O half — the
// batched git pass that captures per-commit tuples, the change registry walk, and
// the per-folder LogData assembly — lives in memoryindex.go alongside Gather.

import (
	"fmt"
	"sort"
	"strings"
)

// Log verbs — the optional leading bold token of a log entry (FKF §6.2),
// derived per (commit, file) from git's name-status.
const (
	verbCreation    = "**Creation**"
	verbDeprecation = "**Deprecation**"
	verbUpdate      = "**Update**"
)

// LogEntry is one rendered line of a log.md: a single change's effect on a
// single file, under a single date. Pure value consumed by RenderLog.
type LogEntry struct {
	// Date is the commit date, ISO YYYY-MM-DD (the date-group heading key).
	Date string
	// Verb is the optional leading bold token ("**Creation**" / "**Deprecation**"
	// / "**Update**"); "" omits the verb (FKF §6.2 makes it optional).
	Verb string
	// FileBase is the changed file's link label (its name without .md).
	FileBase string
	// BundleRelPath is the bundle-relative link target beginning with "/"
	// (resolved from docs/memory/, FKF §7), e.g. "/distribution/migrations.md".
	BundleRelPath string
	// Summary is the descriptive line: the change's `.status.yaml` summary, or
	// the change slug fallback when no summary exists, or "—" when the commit is
	// unattributable (FKF §6.3 graceful degradation).
	Summary string
	// ChangeID is the 4-char change id rendered as "(id)"; "" omits the token
	// (an unattributable commit — direct main edit, pre-FKF, squash-dropped).
	ChangeID string
}

// LogData is everything RenderLog needs for one folder's log.md. Plain value →
// RenderLog is pure.
type LogData struct {
	// Title is the human heading rendered after "# Log — " (the folder's domain
	// index Title, or a Title-Cased folder name).
	Title string
	// Entries are the folder's log entries. RenderLog sorts them deterministically
	// (newest date first), so the caller need not pre-sort — but the input order
	// is otherwise preserved within a date for stable secondary ordering.
	Entries []LogEntry
}

// logHeaderComment marks log.md as a single-writer generated artifact, the same
// discipline as the index header comments.
const logHeaderComment = "<!-- Generated by `fab memory-index` from git history + per-change summaries. Do not hand-edit. -->"

// RenderLog assembles the complete log.md markdown for d. It is pure: identical
// LogData always yields identical output (byte-stable / idempotent). Entries are
// date-grouped, newest date first; within a date the caller's order is preserved
// (the gatherer supplies a deterministic order). FKF §6.2 format.
func RenderLog(d LogData) string {
	var b strings.Builder
	fmt.Fprintf(&b, "# Log — %s\n", d.Title)
	b.WriteString(logHeaderComment)
	b.WriteString("\n")

	// Group by date, preserving each date's first-seen order for the heading
	// sequence, then sort dates newest-first. A stable sort keeps the gatherer's
	// intra-date ordering intact.
	order := []string{}
	byDate := map[string][]LogEntry{}
	for _, e := range d.Entries {
		if _, seen := byDate[e.Date]; !seen {
			order = append(order, e.Date)
		}
		byDate[e.Date] = append(byDate[e.Date], e)
	}
	sort.SliceStable(order, func(i, j int) bool { return order[i] > order[j] }) // newest first

	for _, date := range order {
		fmt.Fprintf(&b, "\n## %s\n", date)
		for _, e := range byDate[date] {
			b.WriteString(renderLogEntry(e))
		}
	}
	return b.String()
}

// renderLogEntry renders one "- {**Verb** }[base](/bundle-rel.md) — {desc}{ (id)}"
// line. The verb and the (id) token are both optional; the descriptive line
// falls back to the missing-cell "—" when empty.
func renderLogEntry(e LogEntry) string {
	var b strings.Builder
	b.WriteString("- ")
	if e.Verb != "" {
		b.WriteString(e.Verb)
		b.WriteString(" ")
	}
	fmt.Fprintf(&b, "[%s](%s)", e.FileBase, e.BundleRelPath)
	desc := strings.TrimSpace(e.Summary)
	if desc == "" {
		desc = missingCell
	}
	fmt.Fprintf(&b, " — %s", desc)
	if e.ChangeID != "" {
		fmt.Fprintf(&b, " (%s)", e.ChangeID)
	}
	b.WriteString("\n")
	return b.String()
}

// nameStatusVerb maps a git name-status code to the leading bold log verb.
// The status is the first whitespace-delimited token of a --name-status line:
// "A" added → Creation, "D" deleted → Deprecation, "M"/"R{score}"/"C{score}"
// modified/renamed/copied → Update. An unknown/empty code yields "" (verb
// omitted — FKF §6.2 makes it optional; never an error). change_type is a
// secondary hint the caller may apply, but the per-commit name-status is the
// primary signal.
func nameStatusVerb(status string) string {
	status = strings.TrimSpace(status)
	if status == "" {
		return ""
	}
	switch status[0] {
	case 'A':
		return verbCreation
	case 'D':
		return verbDeprecation
	case 'M', 'R', 'C', 'T':
		// T = type-change (e.g. file↔symlink); still an in-place update.
		return verbUpdate
	default:
		return ""
	}
}
