package memoryindex

import (
	"os"
	"path/filepath"
	"strings"
	"testing"
)

// --- RenderLog pure renderer (byte-for-byte, FKF §6.2) ---------------------

func TestGolden_RenderLog_FullDocument(t *testing.T) {
	got := RenderLog(LogData{
		Title: "Distribution Documentation",
		Entries: []LogEntry{
			{Date: "2026-06-13", Verb: verbUpdate, FileBase: "migrations", BundleRelPath: "/distribution/migrations.md",
				Summary: "surfaces the optional agent.tiers override as a commented config block", ChangeID: "l3ja"},
			{Date: "2026-06-12", Verb: verbUpdate, FileBase: "migrations", BundleRelPath: "/distribution/migrations.md",
				Summary: "drops the dead stage_directives block", ChangeID: "c5tr"},
			{Date: "2026-06-12", Verb: verbCreation, FileBase: "setup", BundleRelPath: "/distribution/setup.md",
				Summary: "adds the setup doc", ChangeID: "tb6f"},
		},
	})
	want := "# Log — Distribution Documentation\n" +
		"<!-- Generated by `fab memory-index` from git history + per-change summaries. Do not hand-edit. -->\n" +
		"\n" +
		"## 2026-06-13\n" +
		"- **Update** [migrations](/distribution/migrations.md) — surfaces the optional agent.tiers override as a commented config block (l3ja)\n" +
		"\n" +
		"## 2026-06-12\n" +
		"- **Update** [migrations](/distribution/migrations.md) — drops the dead stage_directives block (c5tr)\n" +
		"- **Creation** [setup](/distribution/setup.md) — adds the setup doc (tb6f)\n"
	if got != want {
		t.Errorf("RenderLog full-document golden mismatch.\n--- got ---\n%s\n--- want ---\n%s", got, want)
	}
}

func TestRenderLog_DateGroupingNewestFirst(t *testing.T) {
	// Out-of-order input must render newest-date-first regardless of input order.
	got := RenderLog(LogData{Title: "X", Entries: []LogEntry{
		{Date: "2026-01-01", FileBase: "a", BundleRelPath: "/x/a.md", Summary: "old", ChangeID: "aaaa"},
		{Date: "2026-12-31", FileBase: "b", BundleRelPath: "/x/b.md", Summary: "new", ChangeID: "bbbb"},
	}})
	iNew := strings.Index(got, "## 2026-12-31")
	iOld := strings.Index(got, "## 2026-01-01")
	if iNew < 0 || iOld < 0 || iNew > iOld {
		t.Errorf("newest date must come first:\n%s", got)
	}
}

func TestRenderLog_OptionalVerbAndID(t *testing.T) {
	// No verb, no change-id, empty summary → degrades cleanly.
	got := RenderLog(LogData{Title: "X", Entries: []LogEntry{
		{Date: "2026-06-01", FileBase: "orphan", BundleRelPath: "/x/orphan.md"},
	}})
	want := "- [orphan](/x/orphan.md) — " + missingCell + "\n"
	if !strings.Contains(got, want) {
		t.Errorf("verb+id-less entry with empty summary should render %q, got:\n%s", want, got)
	}
	if strings.Contains(got, "**") {
		t.Errorf("no verb should mean no bold token, got:\n%s", got)
	}
}

func TestRenderLog_SlugFallbackLine(t *testing.T) {
	// A slug fallback is just a normal Summary value to the renderer.
	got := RenderLog(LogData{Title: "X", Entries: []LogEntry{
		{Date: "2026-06-01", FileBase: "a", BundleRelPath: "/x/a.md", Summary: "some-change-slug", ChangeID: "abcd"},
	}})
	if !strings.Contains(got, "— some-change-slug (abcd)\n") {
		t.Errorf("slug fallback line mismatch, got:\n%s", got)
	}
}

func TestRenderLog_Idempotent(t *testing.T) {
	d := LogData{Title: "X", Entries: []LogEntry{
		{Date: "2026-06-01", Verb: verbUpdate, FileBase: "a", BundleRelPath: "/x/a.md", Summary: "s", ChangeID: "abcd"},
		{Date: "2026-06-01", Verb: verbUpdate, FileBase: "b", BundleRelPath: "/x/b.md", Summary: "t", ChangeID: "efgh"},
	}}
	if RenderLog(d) != RenderLog(d) {
		t.Error("RenderLog is not byte-stable for identical input")
	}
}

// --- Verb derivation -------------------------------------------------------

func TestNameStatusVerb(t *testing.T) {
	cases := map[string]string{
		"A":    verbCreation,
		"D":    verbDeprecation,
		"M":    verbUpdate,
		"R099": verbUpdate, // rename
		"R":    verbUpdate,
		"C075": verbUpdate, // copy
		"T":    verbUpdate, // type change
		"":     "",         // unknown → omit
		"X":    "",         // unknown status → omit (never errors)
	}
	for status, want := range cases {
		if got := nameStatusVerb(status); got != want {
			t.Errorf("nameStatusVerb(%q) = %q, want %q", status, got, want)
		}
	}
}

// --- Commit → change-id attribution (registry-gated) -----------------------

func TestAttributeCommit(t *testing.T) {
	reg := map[string]changeMeta{
		"yrgo": {Folder: "260317-yrgo-operator5-branch-fallback", Slug: "operator5-branch-fallback"},
		"l3ja": {Folder: "260613-l3ja-per-stage-model-tiers", Slug: "per-stage-model-tiers"},
	}
	cases := []struct {
		name, subject, wantID string
		wantOK                bool
	}{
		{"merge-commit branch token", "Merge pull request #265 from wvrdz/260317-yrgo-operator5-branch-fallback", "yrgo", true},
		{"bare registered id token", "fix something (l3ja)", "l3ja", true},
		{"squash subject, no token", "feat: extend memory-index (#420)", "", false},
		{"unregistered folder token", "Merge pull request #9 from x/260101-zzzz-unknown", "", false},
		{"id substring is not a bare-id match", "this mentions yrgoXX inline", "", false},
	}
	for _, c := range cases {
		t.Run(c.name, func(t *testing.T) {
			gotID, gotOK := attributeCommit(c.subject, reg)
			if gotID != c.wantID || gotOK != c.wantOK {
				t.Errorf("attributeCommit(%q) = (%q,%v), want (%q,%v)", c.subject, gotID, gotOK, c.wantID, c.wantOK)
			}
		})
	}
}

func TestExtractIDSlug(t *testing.T) {
	cases := []struct{ folder, id, slug string }{
		{"260317-yrgo-operator5-branch-fallback", "yrgo", "operator5-branch-fallback"},
		{"260615-bmzo-memory-index-log", "bmzo", "memory-index-log"},
		{"260615-5943", "5943", ""}, // no slug part
		{"garbage", "", ""},
	}
	for _, c := range cases {
		id, slug := extractIDSlug(c.folder)
		if id != c.id || slug != c.slug {
			t.Errorf("extractIDSlug(%q) = (%q,%q), want (%q,%q)", c.folder, id, slug, c.id, c.slug)
		}
	}
}

// --- Registry enumeration (active + archive) -------------------------------

func TestGatherChangeRegistry(t *testing.T) {
	fabRoot := t.TempDir()
	// Active change with a summary.
	writeFile(t, fabRoot, "changes/260615-abcd-active-change/.status.yaml",
		"id: abcd\nname: 260615-abcd-active-change\nsummary: \"did the active thing\"\n")
	// Archived change (bucketed) with no summary → slug fallback.
	writeFile(t, fabRoot, "changes/archive/2026/03/260301-efgh-archived/.status.yaml",
		"id: efgh\nname: 260301-efgh-archived\n")
	// A non-change dir inside changes/ that lacks an id-shaped name is ignored.
	if err := os.MkdirAll(filepath.Join(fabRoot, "changes", "notachange"), 0o755); err != nil {
		t.Fatal(err)
	}

	reg := gatherChangeRegistry(fabRoot)
	if m, ok := reg["abcd"]; !ok || m.Summary != "did the active thing" || m.Slug != "active-change" {
		t.Errorf("active change registry entry mismatch: %+v (ok=%v)", reg["abcd"], ok)
	}
	if m, ok := reg["efgh"]; !ok || m.Summary != "" || m.Slug != "archived" {
		t.Errorf("archived change registry entry mismatch: %+v (ok=%v)", reg["efgh"], ok)
	}
	if _, ok := reg["notachange"]; ok {
		t.Error("a non-id-shaped folder must not register")
	}
}

func TestGatherChangeRegistry_MissingFabRoot(t *testing.T) {
	if reg := gatherChangeRegistry(""); reg == nil || len(reg) != 0 {
		t.Errorf("empty fabRoot should yield an empty non-nil registry, got %v", reg)
	}
	if reg := gatherChangeRegistry(t.TempDir()); reg == nil || len(reg) != 0 {
		t.Errorf("fabRoot with no changes/ should yield an empty registry, got %v", reg)
	}
}

// --- GatherLogs integration on a real git repo -----------------------------

// TestGatherLogs_RealRepo exercises the full C-lite join end-to-end: a merge
// commit whose subject names a registered change → attributed (id + slug),
// versus a squash-style commit with no recoverable token → graceful degradation
// (no id, empty/missing-cell line). Mirrors TestLoadGitDates_BatchEqualsPerFile.
func TestGatherLogs_RealRepo(t *testing.T) {
	repo := t.TempDir()
	gitDateRun(t, repo, "init")

	// Registry: one registered change with a summary.
	writeFile(t, repo, "fab/changes/260301-aaaa-first-change/.status.yaml",
		"id: aaaa\nname: 260301-aaaa-first-change\nsummary: \"the curated summary line\"\n")

	// Commit 1: attributable via a merge-style subject naming the folder.
	writeFile(t, repo, "docs/memory/auth/login.md", "# Login\n")
	gitDateRun(t, repo, "add", ".")
	gitDateRun(t, repo, "commit", "-m", "Merge pull request #1 from o/260301-aaaa-first-change",
		"--date", "2026-03-01T12:00:00 +0000")

	// Commit 2: a later squash-style edit with no recoverable token → degrades.
	writeFile(t, repo, "docs/memory/auth/login.md", "# Login updated\n")
	gitDateRun(t, repo, "add", ".")
	gitDateRun(t, repo, "commit", "-m", "fix: tweak login (#42)", "--date", "2026-04-01T12:00:00 +0000")

	targets, err := GatherLogs(repo, filepath.Join(repo, "fab"))
	if err != nil {
		t.Fatal(err)
	}
	var authLog *LogTarget
	for i := range targets {
		if strings.HasSuffix(filepath.ToSlash(targets[i].Path), "docs/memory/auth/log.md") {
			authLog = &targets[i]
		}
	}
	if authLog == nil {
		t.Fatalf("expected an auth/log.md target, got %d targets: %+v", len(targets), targets)
	}
	content := authLog.Content
	// Newest (squash, unattributable) entry: no (id); the commit subject is the
	// graceful-degradation descriptive line (R7); Update verb.
	if !strings.Contains(content, "## 2026-04-01") {
		t.Errorf("expected the 2026-04-01 squash commit date heading, got:\n%s", content)
	}
	if !strings.Contains(content, "- **Update** [login](/auth/login.md) — fix: tweak login (#42)\n") {
		t.Errorf("unattributable commit should degrade to the commit subject (no id), got:\n%s", content)
	}
	if strings.Contains(content, "(#42))") {
		t.Errorf("unattributable commit must not synthesize a (change-id) token, got:\n%s", content)
	}
	// Older (attributed) entry: (aaaa) + the curated summary, Creation verb (added).
	if !strings.Contains(content, "## 2026-03-01") {
		t.Errorf("expected the 2026-03-01 attributed commit date heading, got:\n%s", content)
	}
	if !strings.Contains(content, "- **Creation** [login](/auth/login.md) — the curated summary line (aaaa)\n") {
		t.Errorf("attributed commit should carry summary + (id), got:\n%s", content)
	}
}

func TestGatherLogs_SlugFallbackWhenNoSummary(t *testing.T) {
	repo := t.TempDir()
	gitDateRun(t, repo, "init")
	// Registered change with NO summary → the log line falls back to the slug.
	writeFile(t, repo, "fab/changes/260301-bbbb-slug-only-change/.status.yaml",
		"id: bbbb\nname: 260301-bbbb-slug-only-change\n")
	writeFile(t, repo, "docs/memory/d/topic.md", "# T\n")
	gitDateRun(t, repo, "add", ".")
	gitDateRun(t, repo, "commit", "-m", "Merge pull request #1 from o/260301-bbbb-slug-only-change",
		"--date", "2026-03-01T12:00:00 +0000")

	targets, err := GatherLogs(repo, filepath.Join(repo, "fab"))
	if err != nil {
		t.Fatal(err)
	}
	found := false
	for _, tg := range targets {
		if strings.Contains(tg.Content, "— slug-only-change (bbbb)") {
			found = true
		}
	}
	if !found {
		t.Errorf("a summary-less attributed change should project its slug; targets:\n%+v", targets)
	}
}

func TestGatherLogs_NonGitDirNoTargets(t *testing.T) {
	// Outside a git repo the batched pass fails → no log targets, no error.
	repo := t.TempDir()
	writeFile(t, repo, "docs/memory/d/topic.md", "# T\n")
	targets, err := GatherLogs(repo, filepath.Join(repo, "fab"))
	if err != nil {
		t.Fatalf("non-git dir should degrade gracefully, got err: %v", err)
	}
	if len(targets) != 0 {
		t.Errorf("non-git dir should yield no log targets, got %+v", targets)
	}
}

func TestGatherLogs_EmptyFolderSkipped(t *testing.T) {
	// A folder whose only file is uncommitted (no attributable history) yields
	// no log.md (Design Decision 4: skip empty, do not emit a header-only file).
	repo := t.TempDir()
	gitDateRun(t, repo, "init")
	writeFile(t, repo, "docs/memory/committed/a.md", "# A\n")
	gitDateRun(t, repo, "add", ".")
	gitDateRun(t, repo, "commit", "-m", "init", "--date", "2026-01-01T12:00:00 +0000")
	// Uncommitted-only folder: present on disk, absent from git history.
	writeFile(t, repo, "docs/memory/uncommitted/b.md", "# B\n")

	targets, err := GatherLogs(repo, filepath.Join(repo, "fab"))
	if err != nil {
		t.Fatal(err)
	}
	for _, tg := range targets {
		if strings.Contains(filepath.ToSlash(tg.Path), "docs/memory/uncommitted/log.md") {
			t.Errorf("a folder with no attributable history must be skipped, got target: %s", tg.Path)
		}
	}
}

// --- M1 regression: log.md is a generated artifact, never a topic-file row ---

// TestGather_ExcludesGeneratedLogAndIndex pins the M1 fix: a generated log.md
// (and index.md) sitting alongside real topic files must NOT be gathered as a
// topic file — otherwise a second `fab memory-index` run reads the just-written
// log.md back and appends a spurious `[log](log.md)` row to the domain index,
// breaking idempotence/byte-stability (Constitution III). Before the gatherFiles
// fix this asserts FAIL: Files would contain a "log" entry and the rendered
// index would carry a `[log](log.md)` row.
func TestGather_ExcludesGeneratedLogAndIndex(t *testing.T) {
	repo := t.TempDir()
	// Two real topic files plus the two generated, single-writer artifacts.
	writeFile(t, repo, "docs/memory/auth/authentication.md", "# Authentication\n")
	writeFile(t, repo, "docs/memory/auth/sessions.md", "# Sessions\n")
	writeFile(t, repo, "docs/memory/auth/index.md", "# Auth Documentation\n")
	writeFile(t, repo, "docs/memory/auth/log.md",
		"# Log — Auth Documentation\n<!-- Generated by `fab memory-index` ... -->\n")

	_, domains, _, err := Gather(repo)
	if err != nil {
		t.Fatal(err)
	}
	if len(domains) != 1 {
		t.Fatalf("expected one domain, got %d: %+v", len(domains), domains)
	}
	// Only the two real topic files — index.md AND log.md excluded.
	if len(domains[0].Files) != 2 {
		t.Fatalf("expected 2 topic files (index.md + log.md excluded), got %d: %+v",
			len(domains[0].Files), domains[0].Files)
	}
	for _, f := range domains[0].Files {
		if f.Base == "log" || f.Base == "index" {
			t.Errorf("generated artifact %q.md must not be gathered as a topic file", f.Base)
		}
	}
	// And the rendered domain index must carry no `[log]` / `[index]` row.
	out := RenderDomain(domains[0])
	if strings.Contains(out, "[log](log.md)") || strings.Contains(out, "[log](") {
		t.Errorf("domain index must not contain a [log] row, got:\n%s", out)
	}
}

// TestGather_SubDomainExcludesGeneratedLog pins the same exclusion one level
// down — gatherSubDomains delegates to gatherFiles, so it must inherit the fix
// (a sub-domain's log.md must not become a spurious topic row in its index).
func TestGather_SubDomainExcludesGeneratedLog(t *testing.T) {
	repo := t.TempDir()
	writeFile(t, repo, "docs/memory/pipeline/sub/topic.md", "# Topic\n")
	writeFile(t, repo, "docs/memory/pipeline/sub/index.md", "# Sub\n")
	writeFile(t, repo, "docs/memory/pipeline/sub/log.md", "# Log — Sub\n")

	_, domains, _, err := Gather(repo)
	if err != nil {
		t.Fatal(err)
	}
	if len(domains) != 1 || len(domains[0].SubDomains) != 1 {
		t.Fatalf("expected one domain with one sub-domain, got %+v", domains)
	}
	sub := domains[0].SubDomains[0]
	if len(sub.Files) != 1 || sub.Files[0].Base != "topic" {
		t.Fatalf("sub-domain should hold only the real topic file (log.md/index.md excluded), got %+v", sub.Files)
	}
}

// TestMemoryIndex_GenerateThenGenerateIsByteStable is the whole-tree
// idempotence integration test for M1 — the `--check`-equivalent. It builds the
// full target set (root + domain index.md + per-folder log.md) exactly as the
// `fab memory-index` cmd does, writes it to disk (the "first generate"), then
// re-gathers and asserts EVERY target is byte-identical to what is on disk (the
// "second generate" writes nothing → `--check` would exit 0). Before the
// gatherFiles fix the second pass adds a `[log](log.md)` row to auth/index.md,
// so this asserts FAIL. Mirrors the real-git-repo style of
// TestGatherLogs_RealRepo / TestLoadGitDates_BatchEqualsPerFile.
func TestMemoryIndex_GenerateThenGenerateIsByteStable(t *testing.T) {
	repo := t.TempDir()
	gitDateRun(t, repo, "init")
	writeFile(t, repo, "fab/changes/260301-aaaa-first-change/.status.yaml",
		"id: aaaa\nname: 260301-aaaa-first-change\nsummary: \"the curated summary line\"\n")
	writeFile(t, repo, "docs/memory/auth/login.md", "# Login\n")
	writeFile(t, repo, "docs/memory/auth/index.md", "# Auth Documentation\n")
	gitDateRun(t, repo, "add", ".")
	gitDateRun(t, repo, "commit", "-m", "Merge pull request #1 from o/260301-aaaa-first-change",
		"--date", "2026-03-01T12:00:00 +0000")

	fabRoot := filepath.Join(repo, "fab")
	memRoot := filepath.Join(repo, "docs", "memory")

	// buildTargets mirrors the cmd's target assembly: root + domain/sub index.md
	// + per-folder log.md, all from one Gather + GatherLogs pass.
	buildTargets := func() map[string]string {
		root, domains, _, err := Gather(repo)
		if err != nil {
			t.Fatal(err)
		}
		out := map[string]string{
			filepath.Join(memRoot, "index.md"): RenderRoot(root),
		}
		for _, d := range domains {
			out[filepath.Join(memRoot, d.Name, "index.md")] = RenderDomain(d)
			for _, sd := range d.SubDomains {
				out[filepath.Join(memRoot, d.Name, sd.Name, "index.md")] = RenderDomain(sd)
			}
		}
		logTargets, err := GatherLogs(repo, fabRoot)
		if err != nil {
			t.Fatal(err)
		}
		for _, lt := range logTargets {
			out[lt.Path] = lt.Content
		}
		return out
	}

	// First generate: write every target to disk.
	first := buildTargets()
	if _, ok := first[filepath.Join(memRoot, "auth", "log.md")]; !ok {
		t.Fatalf("expected an auth/log.md target on the first generate, got %v", first)
	}
	for path, content := range first {
		if err := os.WriteFile(path, []byte(content), 0o644); err != nil {
			t.Fatal(err)
		}
	}

	// Second generate: re-gather against the now-fully-generated tree and assert
	// every target is byte-identical to what is on disk (nothing to write).
	second := buildTargets()
	for path, content := range second {
		existing, err := os.ReadFile(path)
		if err != nil {
			t.Fatalf("second-pass target %s missing from disk: %v", path, err)
		}
		if string(existing) != content {
			relPath, _ := filepath.Rel(repo, path)
			t.Errorf("NOT idempotent: second generate of %s differs from the first.\n--- on disk ---\n%s\n--- re-rendered ---\n%s",
				filepath.ToSlash(relPath), existing, content)
		}
	}
	// Belt-and-suspenders: the auth domain index must never gain a [log] row on
	// the second pass (the exact M1 symptom).
	if got := second[filepath.Join(memRoot, "auth", "index.md")]; strings.Contains(got, "[log](log.md)") {
		t.Errorf("second generate added a spurious [log] row to auth/index.md:\n%s", got)
	}
}
