package memoryindex

import (
	"os"
	"os/exec"
	"path/filepath"
	"strings"
	"testing"
)

// --- Pure renderer fixtures (byte-for-byte) -------------------------------

func TestRenderRoot_DomainsOnly(t *testing.T) {
	got := RenderRoot(RootData{
		Domains: []DomainRow{
			{Name: "auth", Description: "Authentication and authorization"},
			{Name: "payments", Description: "Payment processing and billing"},
		},
	})

	// Domains-only table — no inlined per-file column.
	wantRows := "" +
		"| Domain | Description |\n" +
		"|--------|-------------|\n" +
		"| [auth](auth/index.md) | Authentication and authorization |\n" +
		"| [payments](payments/index.md) | Payment processing and billing |\n"
	if !strings.HasSuffix(got, wantRows) {
		t.Fatalf("RenderRoot table mismatch.\n--- got ---\n%s\n--- want suffix ---\n%s", got, wantRows)
	}
	if !strings.HasPrefix(got, "---\nfkf_version: \"0.1\"\n---\n# Memory Index\n") {
		t.Errorf("RenderRoot should start with the fkf_version frontmatter + Memory Index H1, got:\n%s", got)
	}
	if strings.Contains(got, "Memory Files") {
		t.Error("RenderRoot must NOT contain the legacy 'Memory Files' per-file column")
	}
}

func TestRenderRoot_MissingDescriptionDegrades(t *testing.T) {
	got := RenderRoot(RootData{Domains: []DomainRow{{Name: "auth", Description: ""}}})
	want := "| [auth](auth/index.md) | " + missingCell + " |\n"
	if !strings.HasSuffix(got, want) {
		t.Fatalf("missing description should degrade to %q.\ngot:\n%s", missingCell, got)
	}
}

func TestRenderDomain_FileRows(t *testing.T) {
	got := RenderDomain(DomainData{
		Name:  "auth",
		Title: "Auth Documentation",
		Files: []FileEntry{
			{Base: "authentication", Description: "Login & sessions"},
			{Base: "authorization", Description: "Roles & permissions"},
		},
	})
	wantRows := "" +
		"| File | Description |\n" +
		"|------|-------------|\n" +
		"| [authentication](authentication.md) | Login & sessions |\n" +
		"| [authorization](authorization.md) | Roles & permissions |\n"
	if !strings.HasSuffix(got, wantRows) {
		t.Fatalf("RenderDomain table mismatch.\n--- got ---\n%s\n--- want suffix ---\n%s", got, wantRows)
	}
	if !strings.HasPrefix(got, "# Auth Documentation\n") {
		t.Errorf("RenderDomain should start with the domain Title H1, got:\n%s", got)
	}
	if strings.Contains(got, "Last Updated") {
		t.Error("RenderDomain must NOT contain the dropped 'Last Updated' column")
	}
}

func TestRenderDomain_NoSubDomainsByteIdentical(t *testing.T) {
	// A flat domain (no sub-domains) must render byte-for-byte the same as
	// before recursion was added — no `## Sub-Domains` section.
	got := RenderDomain(DomainData{
		Name:  "auth",
		Title: "Auth Documentation",
		Files: []FileEntry{{Base: "authentication", Description: "Login & sessions"}},
	})
	if strings.Contains(got, "Sub-Domains") {
		t.Errorf("a sub-domain-free domain must not emit a Sub-Domains section, got:\n%s", got)
	}
	want := "# Auth Documentation\n\n" +
		"> **Generated by `fab memory-index`** — do not hand-edit. Descriptions come from each file's `description:` frontmatter.\n\n" +
		"| File | Description |\n" +
		"|------|-------------|\n" +
		"| [authentication](authentication.md) | Login & sessions |\n"
	if got != want {
		t.Fatalf("flat domain render drifted.\n--- got ---\n%q\n--- want ---\n%q", got, want)
	}
}

func TestRenderDomain_WithSubDomains(t *testing.T) {
	got := RenderDomain(DomainData{
		Name:  "fab-workflow",
		Title: "Fab Workflow Documentation",
		Files: []FileEntry{{Base: "context-loading", Description: "Loading convention"}},
		SubDomains: []DomainData{
			{Name: "runtime", Description: "Runtime agents & skills"},
			{Name: "schemas", Description: ""}, // missing description → degrades
		},
	})
	wantSuffix := "" +
		"| [context-loading](context-loading.md) | Loading convention |\n" +
		"\n## Sub-Domains\n\n" +
		"| Sub-Domain | Description |\n" +
		"|------------|-------------|\n" +
		"| [runtime](runtime/index.md) | Runtime agents & skills |\n" +
		"| [schemas](schemas/index.md) | " + missingCell + " |\n"
	if !strings.HasSuffix(got, wantSuffix) {
		t.Fatalf("RenderDomain with sub-domains mismatch.\n--- got ---\n%s\n--- want suffix ---\n%s", got, wantSuffix)
	}
}

func TestRenderDomain_MissingDescriptionDegrades(t *testing.T) {
	got := RenderDomain(DomainData{
		Name:  "auth",
		Title: "Auth Documentation",
		Files: []FileEntry{{Base: "orphan", Description: ""}},
	})
	want := "| [orphan](orphan.md) | " + missingCell + " |\n"
	if !strings.HasSuffix(got, want) {
		t.Fatalf("missing description should degrade.\ngot:\n%s", got)
	}
}

func TestRender_Idempotent(t *testing.T) {
	root := RootData{Domains: []DomainRow{{Name: "auth", Description: "x"}}}
	if RenderRoot(root) != RenderRoot(root) {
		t.Error("RenderRoot is not byte-stable for identical input")
	}
	dom := DomainData{Name: "auth", Title: "Auth", Files: []FileEntry{{Base: "a", Description: "d"}}}
	if RenderDomain(dom) != RenderDomain(dom) {
		t.Error("RenderDomain is not byte-stable for identical input")
	}
}

// --- Warning rendering -----------------------------------------------------

func TestWarning_String(t *testing.T) {
	w := Warning{Path: "docs/memory/fab-workflow", Kind: "width", Count: 20}
	got := w.String()
	if !strings.Contains(got, "20 topic files") || !strings.Contains(got, "~12") {
		t.Errorf("width warning should name count and bound, got: %q", got)
	}
	d := Warning{Path: "docs/memory/a/b/c", Kind: "depth", Depth: 4}
	if !strings.Contains(d.String(), "4 levels") || !strings.Contains(d.String(), "max: 3") {
		t.Errorf("depth warning should name observed depth and max, got: %q", d.String())
	}
}

// --- Gather integration on a synthetic tree --------------------------------

// writeFile writes content to repoRoot/relpath, creating parent dirs.
func writeFile(t *testing.T, repoRoot, relpath, content string) {
	t.Helper()
	full := filepath.Join(repoRoot, filepath.FromSlash(relpath))
	if err := os.MkdirAll(filepath.Dir(full), 0o755); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(full, []byte(content), 0o644); err != nil {
		t.Fatal(err)
	}
}

func TestGather_ReadsFrontmatterAndH1(t *testing.T) {
	repo := t.TempDir()
	writeFile(t, repo, "docs/memory/auth/authentication.md",
		"---\ndescription: \"Login & sessions\"\n---\n# Authentication\n\n## Overview\n")
	writeFile(t, repo, "docs/memory/auth/index.md",
		"---\ndescription: \"Auth domain\"\n---\n# Auth Documentation\n")

	root, domains, _, err := Gather(repo)
	if err != nil {
		t.Fatal(err)
	}
	if len(domains) != 1 || domains[0].Name != "auth" {
		t.Fatalf("expected one auth domain, got %+v", domains)
	}
	if len(domains[0].Files) != 1 {
		t.Fatalf("expected one topic file (index.md excluded), got %d", len(domains[0].Files))
	}
	f := domains[0].Files[0]
	if f.Base != "authentication" || f.Description != "Login & sessions" || f.Title != "Authentication" {
		t.Errorf("file entry mismatch: %+v", f)
	}
	// Domain index.md H1 + description feed Title and root row.
	if domains[0].Title != "Auth Documentation" {
		t.Errorf("domain title should come from index.md H1, got %q", domains[0].Title)
	}
	if len(root.Domains) != 1 || root.Domains[0].Description != "Auth domain" {
		t.Errorf("root row should use domain index.md description, got %+v", root.Domains)
	}
}

func TestGather_MissingDescriptionDegrades(t *testing.T) {
	// A file with no `description:` frontmatter renders the missing-cell
	// fallback in the (now two-column) domain index.
	repo := t.TempDir()
	writeFile(t, repo, "docs/memory/auth/x.md", "# X\n")
	_, domains, _, err := Gather(repo)
	if err != nil {
		t.Fatal(err)
	}
	if domains[0].Files[0].Description != "" {
		t.Errorf("file without frontmatter should have empty Description, got %q", domains[0].Files[0].Description)
	}
	out := RenderDomain(domains[0])
	if !strings.Contains(out, "| "+missingCell+" |") {
		t.Errorf("missing description should render as %q in domain index, got:\n%s", missingCell, out)
	}
}

func TestGather_WidthWarningAndReservedExemption(t *testing.T) {
	repo := t.TempDir()
	// fab-workflow: 13 files → over the 12 bound → warns.
	for i := 0; i < WidthWarnThreshold+1; i++ {
		writeFile(t, repo, "docs/memory/fab-workflow/f"+string(rune('a'+i))+".md", "# F\n")
	}
	// _unsorted: also over-wide, but reserved → exempt.
	for i := 0; i < WidthWarnThreshold+1; i++ {
		writeFile(t, repo, "docs/memory/_unsorted/g"+string(rune('a'+i))+".md", "# G\n")
	}
	// small domain: under bound → no warning.
	writeFile(t, repo, "docs/memory/small/a.md", "# A\n")

	_, _, warnings, err := Gather(repo)
	if err != nil {
		t.Fatal(err)
	}
	var widthPaths []string
	for _, w := range warnings {
		if w.Kind == "width" {
			widthPaths = append(widthPaths, w.Path)
		}
	}
	if len(widthPaths) != 1 || widthPaths[0] != "docs/memory/fab-workflow" {
		t.Fatalf("expected exactly one width warning for fab-workflow, got %v", widthPaths)
	}
}

func TestGather_DepthWarning(t *testing.T) {
	repo := t.TempDir()
	// docs/memory/d/sub/deep/topic.md = depth 4 under docs/memory/ → warns.
	writeFile(t, repo, "docs/memory/d/sub/deep/topic.md", "# T\n")
	_, _, warnings, err := Gather(repo)
	if err != nil {
		t.Fatal(err)
	}
	found := false
	for _, w := range warnings {
		if w.Kind == "depth" {
			found = true
		}
	}
	if !found {
		t.Errorf("expected a depth warning for a depth-4 file, got %+v", warnings)
	}
}

// --- Malformed-frontmatter + description-length warnings (260715-xu0k) ------

// warningsByKind returns all warnings of a given kind.
func warningsByKind(warnings []Warning, kind string) []Warning {
	var out []Warning
	for _, w := range warnings {
		if w.Kind == kind {
			out = append(out, w)
		}
	}
	return out
}

// TestGather_MalformedFrontmatter_GluedFence pins the loom corruption verbatim:
// `description: "text"---` glued on one line with no closing fence and no
// trailing newline. Gather must surface BOTH the unclosed-fence warning and the
// malformed-description (quote-strip failure) warning naming the file — and the
// rendered index output must stay byte-identical to the same tree carrying a
// clean value (byte-stability, intake #3).
func TestGather_MalformedFrontmatter_GluedFence(t *testing.T) {
	repo := t.TempDir()
	// The loom corruption, verbatim shape (no trailing newline).
	writeFile(t, repo, "docs/memory/auth/login.md", "---\ndescription: \"a login flow\"---")
	writeFile(t, repo, "docs/memory/auth/index.md",
		"---\ndescription: \"Auth domain\"\n---\n# Auth Documentation\n")

	_, domains, warnings, err := Gather(repo)
	if err != nil {
		t.Fatal(err)
	}

	fence := warningsByKind(warnings, KindMalformedFence)
	if len(fence) != 1 || fence[0].Path != "docs/memory/auth/login.md" {
		t.Errorf("expected one malformed-fence warning for auth/login.md, got %+v", fence)
	}
	desc := warningsByKind(warnings, KindMalformedDescription)
	if len(desc) != 1 || desc[0].Path != "docs/memory/auth/login.md" {
		t.Fatalf("expected one malformed-description warning for auth/login.md, got %+v", desc)
	}
	if desc[0].Detail != "\"a login flow\"---" {
		t.Errorf("malformed-description warning should carry the offending value, got %q", desc[0].Detail)
	}

	// Byte-stability: the domain index row renders the corrupted value verbatim,
	// exactly as it would today (validation never changes rendered bytes). The
	// corrupted value goes through as the description cell (no crash, no repair).
	out := RenderDomain(domains[0])
	if !strings.Contains(out, "| [login](login.md) | \"a login flow\"--- |") {
		t.Errorf("corrupted value must still render verbatim into the row (byte-stability), got:\n%s", out)
	}
}

// TestGather_MalformedFrontmatter_DomainIndexStub confirms the validation pass
// also covers domain/sub-domain index.md stubs (a corrupted domain description
// mangles the root row exactly like a corrupted topic description).
func TestGather_MalformedFrontmatter_DomainIndexStub(t *testing.T) {
	repo := t.TempDir()
	writeFile(t, repo, "docs/memory/auth/login.md",
		"---\ndescription: \"clean\"\n---\n# Login\n")
	// Domain index stub with an unclosed fence.
	writeFile(t, repo, "docs/memory/auth/index.md",
		"---\ndescription: \"Auth domain\"\n# Auth Documentation\n")

	_, _, warnings, err := Gather(repo)
	if err != nil {
		t.Fatal(err)
	}
	fence := warningsByKind(warnings, KindMalformedFence)
	if len(fence) != 1 || fence[0].Path != "docs/memory/auth/index.md" {
		t.Errorf("expected a malformed-fence warning for the auth/index.md stub, got %+v", fence)
	}
}

// TestGather_DescriptionLength_Boundary pins the exact 500-char boundary: 501
// runes warns, 500 does not (strictly greater than the cap), and the warning
// carries the observed length. Uses non-ASCII runes to confirm rune-counting
// (not byte-counting).
func TestGather_DescriptionLength_Boundary(t *testing.T) {
	repo := t.TempDir()
	over := strings.Repeat("é", DescriptionLenWarnThreshold+1) // 501 runes (1002 bytes)
	atCap := strings.Repeat("a", DescriptionLenWarnThreshold)  // exactly 500 runes
	writeFile(t, repo, "docs/memory/big/over.md",
		"---\ndescription: \""+over+"\"\n---\n# Over\n")
	writeFile(t, repo, "docs/memory/big/atcap.md",
		"---\ndescription: \""+atCap+"\"\n---\n# AtCap\n")

	_, _, warnings, err := Gather(repo)
	if err != nil {
		t.Fatal(err)
	}
	lengthWarns := warningsByKind(warnings, KindDescriptionLength)
	if len(lengthWarns) != 1 {
		t.Fatalf("expected exactly one length warning (the 501-rune file), got %+v", lengthWarns)
	}
	if lengthWarns[0].Path != "docs/memory/big/over.md" {
		t.Errorf("length warning should name the over-length file, got %q", lengthWarns[0].Path)
	}
	if lengthWarns[0].Count != DescriptionLenWarnThreshold+1 {
		t.Errorf("length warning should carry the rune count %d, got %d", DescriptionLenWarnThreshold+1, lengthWarns[0].Count)
	}
}

// TestGather_CleanTree_NoMalformedOrLengthWarnings confirms a well-formed tree
// (the byte-stable born-FKF shape) emits no malformed/length warnings.
func TestGather_CleanTree_NoMalformedOrLengthWarnings(t *testing.T) {
	repo := t.TempDir()
	writeFile(t, repo, "docs/memory/auth/login.md",
		"---\ndescription: \"Login flow\"\n---\n# Login\n")
	writeFile(t, repo, "docs/memory/auth/index.md",
		"---\ndescription: \"Auth domain\"\n---\n# Auth Documentation\n")
	writeFile(t, repo, "docs/memory/index.md", "---\nfkf_version: \"0.1\"\n---\n# Memory Index\n")

	_, _, warnings, err := Gather(repo)
	if err != nil {
		t.Fatal(err)
	}
	for _, w := range warnings {
		if w.IsMalformed() || w.Kind == KindDescriptionLength {
			t.Errorf("clean tree must emit no malformed/length warning, got %+v", w)
		}
	}
}

// TestGather_WarningsDeterministicOrder confirms the sorted order (Path, then
// Kind) holds across the new warning kinds interleaved with width/depth.
func TestGather_WarningsDeterministicOrder(t *testing.T) {
	repo := t.TempDir()
	writeFile(t, repo, "docs/memory/aaa/topic.md", "---\ndescription: \"x\"---") // malformed
	writeFile(t, repo, "docs/memory/zzz/topic.md",
		"---\ndescription: \""+strings.Repeat("a", DescriptionLenWarnThreshold+1)+"\"\n---\n# T\n")

	_, _, warnings, err := Gather(repo)
	if err != nil {
		t.Fatal(err)
	}
	// Two runs must be byte-stable in order.
	_, _, warnings2, _ := Gather(repo)
	if len(warnings) != len(warnings2) {
		t.Fatalf("warning count not stable: %d vs %d", len(warnings), len(warnings2))
	}
	for i := range warnings {
		if warnings[i] != warnings2[i] {
			t.Errorf("warning order not stable at %d: %+v vs %+v", i, warnings[i], warnings2[i])
		}
	}
	// Sorted by Path ascending.
	for i := 1; i < len(warnings); i++ {
		if warnings[i-1].Path > warnings[i].Path {
			t.Errorf("warnings not sorted by path: %q before %q", warnings[i-1].Path, warnings[i].Path)
		}
	}
}

func TestGather_DeterministicOrdering(t *testing.T) {
	repo := t.TempDir()
	writeFile(t, repo, "docs/memory/zeta/c.md", "# C\n")
	writeFile(t, repo, "docs/memory/zeta/a.md", "# A\n")
	writeFile(t, repo, "docs/memory/alpha/b.md", "# B\n")

	_, domains, _, err := Gather(repo)
	if err != nil {
		t.Fatal(err)
	}
	if domains[0].Name != "alpha" || domains[1].Name != "zeta" {
		t.Errorf("domains should be lexicographic, got %s,%s", domains[0].Name, domains[1].Name)
	}
	zeta := domains[1]
	if zeta.Files[0].Base != "a" || zeta.Files[1].Base != "c" {
		t.Errorf("files should be lexicographic by base, got %+v", zeta.Files)
	}
}

func TestGather_MissingMemoryDirErrors(t *testing.T) {
	repo := t.TempDir() // no docs/memory/
	if _, _, _, err := Gather(repo); err == nil {
		t.Error("expected an error when docs/memory/ is absent")
	}
}

// TestGather_SelfHealsStaleRoster is the loom-derived regression scenario
// (intake Assumption #11): a domain folder whose actual file count differs
// from a stale hand-maintained roster. The generated index reflects the real
// on-disk count, by construction — there is no roster to drift.
func TestGather_SelfHealsStaleRoster(t *testing.T) {
	repo := t.TempDir()
	// Simulate loom's wd-web/canvas: roster once claimed "(12)" but 20 on disk.
	for i := 0; i < 20; i++ {
		writeFile(t, repo, "docs/memory/canvas/file"+string(rune('a'+i))+".md",
			"---\ndescription: \"d\"\n---\n# F\n")
	}
	_, domains, warnings, err := Gather(repo)
	if err != nil {
		t.Fatal(err)
	}
	if len(domains[0].Files) != 20 {
		t.Errorf("generated index must reflect the true 20-file count, got %d", len(domains[0].Files))
	}
	// And it should warn that 20 > 12.
	sawWidth := false
	for _, w := range warnings {
		if w.Kind == "width" && w.Count == 20 {
			sawWidth = true
		}
	}
	if !sawWidth {
		t.Error("expected a width warning for the 20-file canvas domain")
	}
}

// --- Sub-domain recursion (PR #377 Copilot finding: depth-3 topics) --------

func TestGather_RecursesIntoSubDomains(t *testing.T) {
	repo := t.TempDir()
	// A domain with a direct topic file AND a sub-domain holding depth-3 topics.
	writeFile(t, repo, "docs/memory/fab-workflow/context-loading.md",
		"---\ndescription: \"Loading convention\"\n---\n# Context Loading\n")
	writeFile(t, repo, "docs/memory/fab-workflow/index.md",
		"---\ndescription: \"Fab workflow\"\n---\n# Fab Workflow Documentation\n")
	writeFile(t, repo, "docs/memory/fab-workflow/runtime/runtime-agents.md",
		"---\ndescription: \"Agents\"\n---\n# Runtime Agents\n")
	writeFile(t, repo, "docs/memory/fab-workflow/runtime/runtime-skills.md",
		"---\ndescription: \"Skills\"\n---\n# Runtime Skills\n")
	writeFile(t, repo, "docs/memory/fab-workflow/runtime/index.md",
		"---\ndescription: \"Runtime tier\"\n---\n# Runtime Documentation\n")

	_, domains, _, err := Gather(repo)
	if err != nil {
		t.Fatal(err)
	}
	if len(domains) != 1 {
		t.Fatalf("expected one domain, got %d", len(domains))
	}
	d := domains[0]
	// Direct topic file (index.md excluded) is still gathered at the domain tier.
	if len(d.Files) != 1 || d.Files[0].Base != "context-loading" {
		t.Errorf("domain direct files mismatch: %+v", d.Files)
	}
	// The sub-domain is discovered with its two depth-3 topic files.
	if len(d.SubDomains) != 1 || d.SubDomains[0].Name != "runtime" {
		t.Fatalf("expected one 'runtime' sub-domain, got %+v", d.SubDomains)
	}
	sub := d.SubDomains[0]
	if len(sub.Files) != 2 || sub.Files[0].Base != "runtime-agents" || sub.Files[1].Base != "runtime-skills" {
		t.Errorf("sub-domain files mismatch (want lexicographic agents,skills): %+v", sub.Files)
	}
	if sub.Description != "Runtime tier" {
		t.Errorf("sub-domain description should come from its index.md frontmatter, got %q", sub.Description)
	}
	if sub.Title != "Runtime Documentation" {
		t.Errorf("sub-domain title should come from its index.md H1, got %q", sub.Title)
	}
	// One level only — the sub-domain has no further sub-domains.
	if len(sub.SubDomains) != 0 {
		t.Errorf("recursion must stop at one level, got nested sub-domains: %+v", sub.SubDomains)
	}
}

func TestGather_EmptySubDirIsNotASubDomain(t *testing.T) {
	repo := t.TempDir()
	writeFile(t, repo, "docs/memory/d/topic.md", "# T\n")
	// An empty child dir (no .md) must NOT become a sub-domain / spurious index.
	if err := os.MkdirAll(filepath.Join(repo, "docs", "memory", "d", "empty"), 0o755); err != nil {
		t.Fatal(err)
	}
	_, domains, _, err := Gather(repo)
	if err != nil {
		t.Fatal(err)
	}
	if len(domains[0].SubDomains) != 0 {
		t.Errorf("an empty sub-folder must not become a sub-domain, got %+v", domains[0].SubDomains)
	}
}

func TestGather_SubDomainsDeterministicOrder(t *testing.T) {
	repo := t.TempDir()
	writeFile(t, repo, "docs/memory/d/zeta/a.md", "# A\n")
	writeFile(t, repo, "docs/memory/d/alpha/b.md", "# B\n")
	_, domains, _, err := Gather(repo)
	if err != nil {
		t.Fatal(err)
	}
	subs := domains[0].SubDomains
	if len(subs) != 2 || subs[0].Name != "alpha" || subs[1].Name != "zeta" {
		t.Errorf("sub-domains should be lexicographic, got %+v", subs)
	}
}

func TestGather_OverWideSubDomainWarns(t *testing.T) {
	repo := t.TempDir()
	// A sub-domain with 13 files (> the 12 bound) must warn at the sub-domain path.
	for i := 0; i < WidthWarnThreshold+1; i++ {
		writeFile(t, repo, "docs/memory/d/wide/f"+string(rune('a'+i))+".md", "# F\n")
	}
	_, _, warnings, err := Gather(repo)
	if err != nil {
		t.Fatal(err)
	}
	found := false
	for _, w := range warnings {
		if w.Kind == "width" && w.Path == "docs/memory/d/wide" && w.Count == WidthWarnThreshold+1 {
			found = true
		}
	}
	if !found {
		t.Errorf("expected a width warning for the over-wide sub-domain, got %+v", warnings)
	}
}

func TestGather_DepthWarningStillFiresUnderRecursion(t *testing.T) {
	repo := t.TempDir()
	// depth-4 file under a sub-domain → still warns (recursion does not suppress it).
	writeFile(t, repo, "docs/memory/d/sub/deeper/topic.md", "# T\n")
	_, _, warnings, err := Gather(repo)
	if err != nil {
		t.Fatal(err)
	}
	found := false
	for _, w := range warnings {
		if w.Kind == "depth" {
			found = true
		}
	}
	if !found {
		t.Errorf("expected a depth warning for a depth-4 file under recursion, got %+v", warnings)
	}
}

func TestGather_SubDomainRenderIdempotent(t *testing.T) {
	repo := t.TempDir()
	writeFile(t, repo, "docs/memory/d/sub/a.md", "---\ndescription: \"d\"\n---\n# A\n")
	_, domains, _, err := Gather(repo)
	if err != nil {
		t.Fatal(err)
	}
	// Re-gathering the same tree must yield identical render output for both
	// the sub-domain and its parent — compare across two independent Gather
	// calls so the check can actually fail on a regression.
	_, domains2, _, err := Gather(repo)
	if err != nil {
		t.Fatal(err)
	}
	if RenderDomain(domains[0].SubDomains[0]) != RenderDomain(domains2[0].SubDomains[0]) {
		t.Error("sub-domain render is not byte-stable across re-gathers of identical input")
	}
	if RenderDomain(domains[0]) != RenderDomain(domains2[0]) {
		t.Error("re-gathering the same tree produced a different parent render")
	}
}

// --- Batched git-commit pass (F34; serves log.md only) ---------------------

func TestParseGitLog(t *testing.T) {
	// Batched format: a record line "<NUL><date><US><subject>", then
	// "<status>\t<path>" name-status rows. The pass now yields only the
	// per-path commit list (the index carries no dates).
	rec := func(date, subject string) string {
		return gitLogRecordSep + date + gitLogFieldSep + subject + "\n"
	}
	t.Run("commits captured per path, newest-first", func(t *testing.T) {
		out := rec("2026-06-10", "feat: thing (#420)") +
			"M\tdocs/memory/auth/x.md\nA\tdocs/memory/auth/y.md\n\n" +
			rec("2026-05-01", "Merge pull request #1 from o/260501-aaaa-slug") +
			"M\tdocs/memory/auth/x.md\nM\tdocs/memory/pay/z.md\n"
		commits := parseGitLog(out)

		// x.md was touched by both commits, newest-first; status + subject captured.
		xc := commits["docs/memory/auth/x.md"]
		if len(xc) != 2 {
			t.Fatalf("x.md should have 2 commits, got %d: %+v", len(xc), xc)
		}
		if xc[0].Date != "2026-06-10" || xc[0].Status != "M" || xc[0].Subject != "feat: thing (#420)" {
			t.Errorf("x.md newest commit mismatch: %+v", xc[0])
		}
		if xc[1].Date != "2026-05-01" || xc[1].Subject != "Merge pull request #1 from o/260501-aaaa-slug" {
			t.Errorf("x.md older commit mismatch: %+v", xc[1])
		}
		// y.md was an addition.
		if yc := commits["docs/memory/auth/y.md"]; len(yc) != 1 || yc[0].Status != "A" {
			t.Errorf("y.md should have 1 added commit, got %+v", yc)
		}
		// z.md touched once.
		if zc := commits["docs/memory/pay/z.md"]; len(zc) != 1 || zc[0].Date != "2026-05-01" {
			t.Errorf("z.md should have 1 commit dated 2026-05-01, got %+v", zc)
		}
	})

	t.Run("rename row uses the new (last) path", func(t *testing.T) {
		out := rec("2026-06-08", "docs: reorg (#381)") +
			"R099\tdocs/memory/old/foo.md\tdocs/memory/new/foo.md\n"
		commits := parseGitLog(out)
		if c := commits["docs/memory/new/foo.md"]; len(c) != 1 || c[0].Status != "R099" {
			t.Errorf("rename status should be preserved on the new path, got %+v", c)
		}
	})

	t.Run("empty input yields empty map", func(t *testing.T) {
		commits := parseGitLog("")
		if len(commits) != 0 {
			t.Errorf("parseGitLog(\"\") = %v, want empty", commits)
		}
	})
}

// gitDateRun runs a git command in dir with a deterministic identity,
// skipping the test when git is unavailable.
func gitDateRun(t *testing.T, dir string, args ...string) {
	t.Helper()
	cmd := exec.Command("git", append([]string{"-C", dir}, args...)...)
	cmd.Env = append(os.Environ(),
		"GIT_AUTHOR_NAME=test", "GIT_AUTHOR_EMAIL=t@example.com",
		"GIT_COMMITTER_NAME=test", "GIT_COMMITTER_EMAIL=t@example.com")
	if out, err := cmd.CombinedOutput(); err != nil {
		t.Skipf("git %v failed (git unavailable?): %v\n%s", args, err, out)
	}
}

// TestLoadGitDates_CapturesCommitsPerPath pins commits in a real git repo and
// asserts the batched pass records the per-path commit list (newest-first) that
// log.md consumes. The index itself no longer carries dates.
func TestLoadGitDates_CapturesCommitsPerPath(t *testing.T) {
	repo := t.TempDir()
	gitDateRun(t, repo, "init")
	writeFile(t, repo, "docs/memory/auth/x.md", "# X\n")
	gitDateRun(t, repo, "add", ".")
	gitDateRun(t, repo, "commit", "-m", "first", "--date", "2026-01-15T12:00:00 +0000")
	writeFile(t, repo, "docs/memory/auth/y.md", "# Y\n")
	gitDateRun(t, repo, "add", ".")
	gitDateRun(t, repo, "commit", "-m", "second", "--date", "2026-03-02T12:00:00 +0000")
	// x.md touched again later — newest commit must come first in the list.
	writeFile(t, repo, "docs/memory/auth/x.md", "# X updated\n")
	gitDateRun(t, repo, "add", ".")
	gitDateRun(t, repo, "commit", "-m", "third", "--date", "2026-04-20T12:00:00 +0000")

	dates := loadGitDates(repo)
	if dates == nil {
		t.Fatal("loadGitDates returned nil in a real git repo")
	}

	rel := func(p string) string { return filepath.ToSlash(filepath.Join("docs/memory/auth", p)) }
	xc := dates.commitsByPath[rel("x.md")]
	if len(xc) != 2 || xc[0].Date != "2026-04-20" || xc[1].Date != "2026-01-15" {
		t.Errorf("x.md commit list mismatch (want 2026-04-20 then 2026-01-15): %+v", xc)
	}
	yc := dates.commitsByPath[rel("y.md")]
	if len(yc) != 1 || yc[0].Date != "2026-03-02" {
		t.Errorf("y.md commit list mismatch (want one dated 2026-03-02): %+v", yc)
	}
}

// TestLoadGitDates_NilOutsideGitRepo verifies the batched pass returns nil when
// git is unavailable (non-git dir) — callers then emit no log.md.
func TestLoadGitDates_NilOutsideGitRepo(t *testing.T) {
	nonGit := t.TempDir()
	writeFile(t, nonGit, "docs/memory/auth/x.md", "# X\n")
	if loadGitDates(nonGit) != nil {
		t.Error("loadGitDates should return nil outside a git repo")
	}
}
