package memoryindex

import (
	"os"
	"os/exec"
	"path/filepath"
	"strings"
	"testing"
)

// --- Pure renderer fixtures (byte-for-byte) -------------------------------

func TestRenderRoot_DomainsOnly(t *testing.T) {
	got := RenderRoot(RootData{
		Domains: []DomainRow{
			{Name: "auth", Description: "Authentication and authorization"},
			{Name: "payments", Description: "Payment processing and billing"},
		},
	})

	// Domains-only table — no inlined per-file column.
	wantRows := "" +
		"| Domain | Description |\n" +
		"|--------|-------------|\n" +
		"| [auth](auth/index.md) | Authentication and authorization |\n" +
		"| [payments](payments/index.md) | Payment processing and billing |\n"
	if !strings.HasSuffix(got, wantRows) {
		t.Fatalf("RenderRoot table mismatch.\n--- got ---\n%s\n--- want suffix ---\n%s", got, wantRows)
	}
	if !strings.HasPrefix(got, "# Memory Index\n") {
		t.Errorf("RenderRoot should start with the Memory Index H1, got:\n%s", got)
	}
	if strings.Contains(got, "Memory Files") {
		t.Error("RenderRoot must NOT contain the legacy 'Memory Files' per-file column")
	}
}

func TestRenderRoot_MissingDescriptionDegrades(t *testing.T) {
	got := RenderRoot(RootData{Domains: []DomainRow{{Name: "auth", Description: ""}}})
	want := "| [auth](auth/index.md) | " + missingCell + " |\n"
	if !strings.HasSuffix(got, want) {
		t.Fatalf("missing description should degrade to %q.\ngot:\n%s", missingCell, got)
	}
}

func TestRenderDomain_FileRows(t *testing.T) {
	got := RenderDomain(DomainData{
		Name:  "auth",
		Title: "Auth Documentation",
		Files: []FileEntry{
			{Base: "authentication", Description: "Login & sessions", LastUpdated: "2026-05-08"},
			{Base: "authorization", Description: "Roles & permissions", LastUpdated: "2026-04-02"},
		},
	})
	wantRows := "" +
		"| File | Description | Last Updated |\n" +
		"|------|-------------|-------------|\n" +
		"| [authentication](authentication.md) | Login & sessions | 2026-05-08 |\n" +
		"| [authorization](authorization.md) | Roles & permissions | 2026-04-02 |\n"
	if !strings.HasSuffix(got, wantRows) {
		t.Fatalf("RenderDomain table mismatch.\n--- got ---\n%s\n--- want suffix ---\n%s", got, wantRows)
	}
	if !strings.HasPrefix(got, "# Auth Documentation\n") {
		t.Errorf("RenderDomain should start with the domain Title H1, got:\n%s", got)
	}
}

func TestRenderDomain_NoSubDomainsByteIdentical(t *testing.T) {
	// A flat domain (no sub-domains) must render byte-for-byte the same as
	// before recursion was added — no `## Sub-Domains` section.
	got := RenderDomain(DomainData{
		Name:  "auth",
		Title: "Auth Documentation",
		Files: []FileEntry{{Base: "authentication", Description: "Login & sessions", LastUpdated: "2026-05-08"}},
	})
	if strings.Contains(got, "Sub-Domains") {
		t.Errorf("a sub-domain-free domain must not emit a Sub-Domains section, got:\n%s", got)
	}
	want := "# Auth Documentation\n\n" +
		"> **Generated by `fab memory-index`** — do not hand-edit. Descriptions come from each file's `description:` frontmatter; dates from `git log`.\n\n" +
		"| File | Description | Last Updated |\n" +
		"|------|-------------|-------------|\n" +
		"| [authentication](authentication.md) | Login & sessions | 2026-05-08 |\n"
	if got != want {
		t.Fatalf("flat domain render drifted.\n--- got ---\n%q\n--- want ---\n%q", got, want)
	}
}

func TestRenderDomain_WithSubDomains(t *testing.T) {
	got := RenderDomain(DomainData{
		Name:  "fab-workflow",
		Title: "Fab Workflow Documentation",
		Files: []FileEntry{{Base: "context-loading", Description: "Loading convention", LastUpdated: "2026-06-07"}},
		SubDomains: []DomainData{
			{Name: "runtime", Description: "Runtime agents & skills"},
			{Name: "schemas", Description: ""}, // missing description → degrades
		},
	})
	wantSuffix := "" +
		"| [context-loading](context-loading.md) | Loading convention | 2026-06-07 |\n" +
		"\n## Sub-Domains\n\n" +
		"| Sub-Domain | Description |\n" +
		"|------------|-------------|\n" +
		"| [runtime](runtime/index.md) | Runtime agents & skills |\n" +
		"| [schemas](schemas/index.md) | " + missingCell + " |\n"
	if !strings.HasSuffix(got, wantSuffix) {
		t.Fatalf("RenderDomain with sub-domains mismatch.\n--- got ---\n%s\n--- want suffix ---\n%s", got, wantSuffix)
	}
}

func TestRenderDomain_MissingDescriptionAndDateDegrade(t *testing.T) {
	got := RenderDomain(DomainData{
		Name:  "auth",
		Title: "Auth Documentation",
		Files: []FileEntry{{Base: "orphan", Description: "", LastUpdated: ""}},
	})
	want := "| [orphan](orphan.md) | " + missingCell + " | " + missingCell + " |\n"
	if !strings.HasSuffix(got, want) {
		t.Fatalf("missing description+date should both degrade.\ngot:\n%s", got)
	}
}

func TestRender_Idempotent(t *testing.T) {
	root := RootData{Domains: []DomainRow{{Name: "auth", Description: "x"}}}
	if RenderRoot(root) != RenderRoot(root) {
		t.Error("RenderRoot is not byte-stable for identical input")
	}
	dom := DomainData{Name: "auth", Title: "Auth", Files: []FileEntry{{Base: "a", Description: "d", LastUpdated: "2026-01-01"}}}
	if RenderDomain(dom) != RenderDomain(dom) {
		t.Error("RenderDomain is not byte-stable for identical input")
	}
}

// --- Warning rendering -----------------------------------------------------

func TestWarning_String(t *testing.T) {
	w := Warning{Path: "docs/memory/fab-workflow", Kind: "width", Count: 20}
	got := w.String()
	if !strings.Contains(got, "20 topic files") || !strings.Contains(got, "~12") {
		t.Errorf("width warning should name count and bound, got: %q", got)
	}
	d := Warning{Path: "docs/memory/a/b/c", Kind: "depth", Depth: 4}
	if !strings.Contains(d.String(), "exceeds depth 3") {
		t.Errorf("depth warning should name max depth, got: %q", d.String())
	}
}

// --- Gather integration on a synthetic tree --------------------------------

// writeFile writes content to repoRoot/relpath, creating parent dirs.
func writeFile(t *testing.T, repoRoot, relpath, content string) {
	t.Helper()
	full := filepath.Join(repoRoot, filepath.FromSlash(relpath))
	if err := os.MkdirAll(filepath.Dir(full), 0o755); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(full, []byte(content), 0o644); err != nil {
		t.Fatal(err)
	}
}

func TestGather_ReadsFrontmatterAndH1(t *testing.T) {
	repo := t.TempDir()
	writeFile(t, repo, "docs/memory/auth/authentication.md",
		"---\ndescription: \"Login & sessions\"\n---\n# Authentication\n\n## Overview\n")
	writeFile(t, repo, "docs/memory/auth/index.md",
		"---\ndescription: \"Auth domain\"\n---\n# Auth Documentation\n")

	root, domains, _, err := Gather(repo)
	if err != nil {
		t.Fatal(err)
	}
	if len(domains) != 1 || domains[0].Name != "auth" {
		t.Fatalf("expected one auth domain, got %+v", domains)
	}
	if len(domains[0].Files) != 1 {
		t.Fatalf("expected one topic file (index.md excluded), got %d", len(domains[0].Files))
	}
	f := domains[0].Files[0]
	if f.Base != "authentication" || f.Description != "Login & sessions" || f.Title != "Authentication" {
		t.Errorf("file entry mismatch: %+v", f)
	}
	// Domain index.md H1 + description feed Title and root row.
	if domains[0].Title != "Auth Documentation" {
		t.Errorf("domain title should come from index.md H1, got %q", domains[0].Title)
	}
	if len(root.Domains) != 1 || root.Domains[0].Description != "Auth domain" {
		t.Errorf("root row should use domain index.md description, got %+v", root.Domains)
	}
}

func TestGather_UncommittedDateDegrades(t *testing.T) {
	// A temp dir is not a git repo → git log produces no output → "" date,
	// which the renderer degrades to the missing-cell fallback.
	repo := t.TempDir()
	writeFile(t, repo, "docs/memory/auth/x.md", "# X\n")
	_, domains, _, err := Gather(repo)
	if err != nil {
		t.Fatal(err)
	}
	if domains[0].Files[0].LastUpdated != "" {
		t.Errorf("uncommitted file should have empty LastUpdated, got %q", domains[0].Files[0].LastUpdated)
	}
	out := RenderDomain(domains[0])
	if !strings.Contains(out, "| "+missingCell+" |") {
		t.Errorf("uncommitted date should render as %q in domain index, got:\n%s", missingCell, out)
	}
}

func TestGather_WidthWarningAndReservedExemption(t *testing.T) {
	repo := t.TempDir()
	// fab-workflow: 13 files → over the 12 bound → warns.
	for i := 0; i < WidthWarnThreshold+1; i++ {
		writeFile(t, repo, "docs/memory/fab-workflow/f"+string(rune('a'+i))+".md", "# F\n")
	}
	// _unsorted: also over-wide, but reserved → exempt.
	for i := 0; i < WidthWarnThreshold+1; i++ {
		writeFile(t, repo, "docs/memory/_unsorted/g"+string(rune('a'+i))+".md", "# G\n")
	}
	// small domain: under bound → no warning.
	writeFile(t, repo, "docs/memory/small/a.md", "# A\n")

	_, _, warnings, err := Gather(repo)
	if err != nil {
		t.Fatal(err)
	}
	var widthPaths []string
	for _, w := range warnings {
		if w.Kind == "width" {
			widthPaths = append(widthPaths, w.Path)
		}
	}
	if len(widthPaths) != 1 || widthPaths[0] != "docs/memory/fab-workflow" {
		t.Fatalf("expected exactly one width warning for fab-workflow, got %v", widthPaths)
	}
}

func TestGather_DepthWarning(t *testing.T) {
	repo := t.TempDir()
	// docs/memory/d/sub/deep/topic.md = depth 4 under docs/memory/ → warns.
	writeFile(t, repo, "docs/memory/d/sub/deep/topic.md", "# T\n")
	_, _, warnings, err := Gather(repo)
	if err != nil {
		t.Fatal(err)
	}
	found := false
	for _, w := range warnings {
		if w.Kind == "depth" {
			found = true
		}
	}
	if !found {
		t.Errorf("expected a depth warning for a depth-4 file, got %+v", warnings)
	}
}

func TestGather_DeterministicOrdering(t *testing.T) {
	repo := t.TempDir()
	writeFile(t, repo, "docs/memory/zeta/c.md", "# C\n")
	writeFile(t, repo, "docs/memory/zeta/a.md", "# A\n")
	writeFile(t, repo, "docs/memory/alpha/b.md", "# B\n")

	_, domains, _, err := Gather(repo)
	if err != nil {
		t.Fatal(err)
	}
	if domains[0].Name != "alpha" || domains[1].Name != "zeta" {
		t.Errorf("domains should be lexicographic, got %s,%s", domains[0].Name, domains[1].Name)
	}
	zeta := domains[1]
	if zeta.Files[0].Base != "a" || zeta.Files[1].Base != "c" {
		t.Errorf("files should be lexicographic by base, got %+v", zeta.Files)
	}
}

func TestGather_MissingMemoryDirErrors(t *testing.T) {
	repo := t.TempDir() // no docs/memory/
	if _, _, _, err := Gather(repo); err == nil {
		t.Error("expected an error when docs/memory/ is absent")
	}
}

// TestGather_SelfHealsStaleRoster is the loom-derived regression scenario
// (intake Assumption #11): a domain folder whose actual file count differs
// from a stale hand-maintained roster. The generated index reflects the real
// on-disk count, by construction — there is no roster to drift.
func TestGather_SelfHealsStaleRoster(t *testing.T) {
	repo := t.TempDir()
	// Simulate loom's wd-web/canvas: roster once claimed "(12)" but 20 on disk.
	for i := 0; i < 20; i++ {
		writeFile(t, repo, "docs/memory/canvas/file"+string(rune('a'+i))+".md",
			"---\ndescription: \"d\"\n---\n# F\n")
	}
	_, domains, warnings, err := Gather(repo)
	if err != nil {
		t.Fatal(err)
	}
	if len(domains[0].Files) != 20 {
		t.Errorf("generated index must reflect the true 20-file count, got %d", len(domains[0].Files))
	}
	// And it should warn that 20 > 12.
	sawWidth := false
	for _, w := range warnings {
		if w.Kind == "width" && w.Count == 20 {
			sawWidth = true
		}
	}
	if !sawWidth {
		t.Error("expected a width warning for the 20-file canvas domain")
	}
}

// --- Sub-domain recursion (PR #377 Copilot finding: depth-3 topics) --------

func TestGather_RecursesIntoSubDomains(t *testing.T) {
	repo := t.TempDir()
	// A domain with a direct topic file AND a sub-domain holding depth-3 topics.
	writeFile(t, repo, "docs/memory/fab-workflow/context-loading.md",
		"---\ndescription: \"Loading convention\"\n---\n# Context Loading\n")
	writeFile(t, repo, "docs/memory/fab-workflow/index.md",
		"---\ndescription: \"Fab workflow\"\n---\n# Fab Workflow Documentation\n")
	writeFile(t, repo, "docs/memory/fab-workflow/runtime/runtime-agents.md",
		"---\ndescription: \"Agents\"\n---\n# Runtime Agents\n")
	writeFile(t, repo, "docs/memory/fab-workflow/runtime/runtime-skills.md",
		"---\ndescription: \"Skills\"\n---\n# Runtime Skills\n")
	writeFile(t, repo, "docs/memory/fab-workflow/runtime/index.md",
		"---\ndescription: \"Runtime tier\"\n---\n# Runtime Documentation\n")

	_, domains, _, err := Gather(repo)
	if err != nil {
		t.Fatal(err)
	}
	if len(domains) != 1 {
		t.Fatalf("expected one domain, got %d", len(domains))
	}
	d := domains[0]
	// Direct topic file (index.md excluded) is still gathered at the domain tier.
	if len(d.Files) != 1 || d.Files[0].Base != "context-loading" {
		t.Errorf("domain direct files mismatch: %+v", d.Files)
	}
	// The sub-domain is discovered with its two depth-3 topic files.
	if len(d.SubDomains) != 1 || d.SubDomains[0].Name != "runtime" {
		t.Fatalf("expected one 'runtime' sub-domain, got %+v", d.SubDomains)
	}
	sub := d.SubDomains[0]
	if len(sub.Files) != 2 || sub.Files[0].Base != "runtime-agents" || sub.Files[1].Base != "runtime-skills" {
		t.Errorf("sub-domain files mismatch (want lexicographic agents,skills): %+v", sub.Files)
	}
	if sub.Description != "Runtime tier" {
		t.Errorf("sub-domain description should come from its index.md frontmatter, got %q", sub.Description)
	}
	if sub.Title != "Runtime Documentation" {
		t.Errorf("sub-domain title should come from its index.md H1, got %q", sub.Title)
	}
	// One level only — the sub-domain has no further sub-domains.
	if len(sub.SubDomains) != 0 {
		t.Errorf("recursion must stop at one level, got nested sub-domains: %+v", sub.SubDomains)
	}
}

func TestGather_EmptySubDirIsNotASubDomain(t *testing.T) {
	repo := t.TempDir()
	writeFile(t, repo, "docs/memory/d/topic.md", "# T\n")
	// An empty child dir (no .md) must NOT become a sub-domain / spurious index.
	if err := os.MkdirAll(filepath.Join(repo, "docs", "memory", "d", "empty"), 0o755); err != nil {
		t.Fatal(err)
	}
	_, domains, _, err := Gather(repo)
	if err != nil {
		t.Fatal(err)
	}
	if len(domains[0].SubDomains) != 0 {
		t.Errorf("an empty sub-folder must not become a sub-domain, got %+v", domains[0].SubDomains)
	}
}

func TestGather_SubDomainsDeterministicOrder(t *testing.T) {
	repo := t.TempDir()
	writeFile(t, repo, "docs/memory/d/zeta/a.md", "# A\n")
	writeFile(t, repo, "docs/memory/d/alpha/b.md", "# B\n")
	_, domains, _, err := Gather(repo)
	if err != nil {
		t.Fatal(err)
	}
	subs := domains[0].SubDomains
	if len(subs) != 2 || subs[0].Name != "alpha" || subs[1].Name != "zeta" {
		t.Errorf("sub-domains should be lexicographic, got %+v", subs)
	}
}

func TestGather_OverWideSubDomainWarns(t *testing.T) {
	repo := t.TempDir()
	// A sub-domain with 13 files (> the 12 bound) must warn at the sub-domain path.
	for i := 0; i < WidthWarnThreshold+1; i++ {
		writeFile(t, repo, "docs/memory/d/wide/f"+string(rune('a'+i))+".md", "# F\n")
	}
	_, _, warnings, err := Gather(repo)
	if err != nil {
		t.Fatal(err)
	}
	found := false
	for _, w := range warnings {
		if w.Kind == "width" && w.Path == "docs/memory/d/wide" && w.Count == WidthWarnThreshold+1 {
			found = true
		}
	}
	if !found {
		t.Errorf("expected a width warning for the over-wide sub-domain, got %+v", warnings)
	}
}

func TestGather_DepthWarningStillFiresUnderRecursion(t *testing.T) {
	repo := t.TempDir()
	// depth-4 file under a sub-domain → still warns (recursion does not suppress it).
	writeFile(t, repo, "docs/memory/d/sub/deeper/topic.md", "# T\n")
	_, _, warnings, err := Gather(repo)
	if err != nil {
		t.Fatal(err)
	}
	found := false
	for _, w := range warnings {
		if w.Kind == "depth" {
			found = true
		}
	}
	if !found {
		t.Errorf("expected a depth warning for a depth-4 file under recursion, got %+v", warnings)
	}
}

func TestGather_SubDomainRenderIdempotent(t *testing.T) {
	repo := t.TempDir()
	writeFile(t, repo, "docs/memory/d/sub/a.md", "---\ndescription: \"d\"\n---\n# A\n")
	_, domains, _, err := Gather(repo)
	if err != nil {
		t.Fatal(err)
	}
	// Re-gathering the same tree must yield identical render output for both
	// the sub-domain and its parent — compare across two independent Gather
	// calls so the check can actually fail on a regression.
	_, domains2, _, err := Gather(repo)
	if err != nil {
		t.Fatal(err)
	}
	if RenderDomain(domains[0].SubDomains[0]) != RenderDomain(domains2[0].SubDomains[0]) {
		t.Error("sub-domain render is not byte-stable across re-gathers of identical input")
	}
	if RenderDomain(domains[0]) != RenderDomain(domains2[0]) {
		t.Error("re-gathering the same tree produced a different parent render")
	}
}

// --- Batched git-date pass (F34) -------------------------------------------

func TestParseGitDates(t *testing.T) {
	t.Run("first (most recent) date per path wins", func(t *testing.T) {
		out := "\x002026-06-10\n\ndocs/memory/auth/x.md\ndocs/memory/auth/y.md\n\n" +
			"\x002026-05-01\n\ndocs/memory/auth/x.md\ndocs/memory/pay/z.md\n"
		got := parseGitDates(out)
		want := map[string]string{
			"docs/memory/auth/x.md": "2026-06-10", // newest-first: first seen wins
			"docs/memory/auth/y.md": "2026-06-10",
			"docs/memory/pay/z.md":  "2026-05-01",
		}
		for path, date := range want {
			if got[path] != date {
				t.Errorf("parseGitDates[%q] = %q, want %q", path, got[path], date)
			}
		}
		if len(got) != len(want) {
			t.Errorf("parseGitDates returned %d entries, want %d: %v", len(got), len(want), got)
		}
	})

	t.Run("empty input yields empty map", func(t *testing.T) {
		if got := parseGitDates(""); len(got) != 0 {
			t.Errorf("parseGitDates(\"\") = %v, want empty", got)
		}
	})
}

// gitDateRun runs a git command in dir with a deterministic identity,
// skipping the test when git is unavailable.
func gitDateRun(t *testing.T, dir string, args ...string) {
	t.Helper()
	cmd := exec.Command("git", append([]string{"-C", dir}, args...)...)
	cmd.Env = append(os.Environ(),
		"GIT_AUTHOR_NAME=test", "GIT_AUTHOR_EMAIL=t@example.com",
		"GIT_COMMITTER_NAME=test", "GIT_COMMITTER_EMAIL=t@example.com")
	if out, err := cmd.CombinedOutput(); err != nil {
		t.Skipf("git %v failed (git unavailable?): %v\n%s", args, err, out)
	}
}

// TestLoadGitDates_BatchEqualsPerFile pins commit author dates in a real git
// repo and asserts the batched pass yields exactly the dates the per-file
// `git log -1` calls produce — the F34 equivalence contract.
func TestLoadGitDates_BatchEqualsPerFile(t *testing.T) {
	repo := t.TempDir()
	gitDateRun(t, repo, "init")
	writeFile(t, repo, "docs/memory/auth/x.md", "# X\n")
	gitDateRun(t, repo, "add", ".")
	gitDateRun(t, repo, "commit", "-m", "first", "--date", "2026-01-15T12:00:00 +0000")
	writeFile(t, repo, "docs/memory/auth/y.md", "# Y\n")
	gitDateRun(t, repo, "add", ".")
	gitDateRun(t, repo, "commit", "-m", "second", "--date", "2026-03-02T12:00:00 +0000")
	// x.md touched again later — most recent date must win.
	writeFile(t, repo, "docs/memory/auth/x.md", "# X updated\n")
	gitDateRun(t, repo, "add", ".")
	gitDateRun(t, repo, "commit", "-m", "third", "--date", "2026-04-20T12:00:00 +0000")
	// Uncommitted file: present on disk, absent from the batch map → "".
	writeFile(t, repo, "docs/memory/auth/uncommitted.md", "# U\n")

	dates := loadGitDates(repo)
	if dates == nil {
		t.Fatal("loadGitDates returned nil in a real git repo")
	}

	wantDates := map[string]string{
		filepath.Join(repo, "docs/memory/auth/x.md"):           "2026-04-20",
		filepath.Join(repo, "docs/memory/auth/y.md"):           "2026-03-02",
		filepath.Join(repo, "docs/memory/auth/uncommitted.md"): "",
	}
	for path, want := range wantDates {
		if got := dates.lookup(repo, path); got != want {
			t.Errorf("batched lookup(%q) = %q, want %q", path, got, want)
		}
		// Equivalence: the per-file fallback must agree.
		if perFile := gitLastUpdated(repo, path); perFile != want {
			t.Errorf("per-file gitLastUpdated(%q) = %q, want %q (fixture broken?)", path, perFile, want)
		}
	}

	// Gather threads the same dates into FileEntry.LastUpdated.
	_, domains, _, err := Gather(repo)
	if err != nil {
		t.Fatal(err)
	}
	byBase := map[string]string{}
	for _, f := range domains[0].Files {
		byBase[f.Base] = f.LastUpdated
	}
	if byBase["x"] != "2026-04-20" || byBase["y"] != "2026-03-02" || byBase["uncommitted"] != "" {
		t.Errorf("Gather dates mismatch: %v", byBase)
	}
}

// TestGitDatesLookup_NilReceiverFallsBack verifies the nil-receiver fallback
// path used when the batched git pass fails (non-git dir, git missing).
func TestGitDatesLookup_NilReceiverFallsBack(t *testing.T) {
	var d *gitDates
	nonGit := t.TempDir()
	writeFile(t, nonGit, "docs/memory/auth/x.md", "# X\n")
	// Non-git dir → per-file fallback also degrades to "".
	if got := d.lookup(nonGit, filepath.Join(nonGit, "docs/memory/auth/x.md")); got != "" {
		t.Errorf("nil-receiver lookup = %q, want \"\" via per-file fallback", got)
	}
	if loadGitDates(nonGit) != nil {
		t.Error("loadGitDates should return nil outside a git repo")
	}
}
