package internal

import (
	"errors"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
)

// Manifest constants. `fab sync` writes a generated `.gitignore` inside every
// fired deploy target listing exactly the entries it deployed there; that file
// is fab's whole-file-owned record of what it owns in the directory (the same
// "fab owns this file" model as the config.yaml reference fence). The next
// sync reads it back as the prune scope for cleanStaleSkills, so the ignore
// list and the prune list can never drift apart.
const (
	manifestFileName     = ".gitignore"
	manifestSelfEntry    = "/.gitignore"
	manifestHeaderSkills = "# Generated by `fab sync` — lists the skills fab-kit deployed here. Do not edit.\n# Everything else in this directory is yours and is NOT ignored.\n"
	manifestHeaderCmds   = "# Generated by `fab sync` — lists the commands fab-kit deployed here. Do not edit.\n# Everything else in this directory is yours and is NOT ignored.\n"
	noManifestNoteFormat = "Note: %s has no fab manifest yet — stale fab skills (if any) were not pruned this run; they will be from the next sync.\n"
)

// agentConfig describes how to deploy skills to a specific AI agent — or, for the
// generic `.agents/skills` directory, to the set of CLIs that read it.
type agentConfig struct {
	Label   string   // display name
	CLIs    []string // candidate commands; the target deploys when ANY is on PATH
	BaseDir string   // target directory relative to repo root
	Format  string   // "directory" or "flat"
	Mode    string   // "copy" or "symlink"
}

// deploySkills deploys skill files to agent-specific directories.
// Returns a non-nil error when any agent's deployment had write failures,
// so Sync exits non-zero instead of reporting stale skills as success.
func deploySkills(repoRoot, kitDir string) error {
	// Collect canonical skill list
	skillsDir := filepath.Join(kitDir, "skills")
	skills := listSkills(skillsDir)
	if len(skills) == 0 {
		return nil
	}

	// Define agent configurations. `.agents/skills` is the GENERIC workspace
	// directory: codex, agy and kimi all discover skills there natively, so it
	// deploys once when any of them is installed. Deploying a per-brand copy for
	// those CLIs as well is what produced duplicate-skill conflict warnings, so one
	// target per skill set is the invariant to keep.
	agents := []agentConfig{
		{Label: "Claude Code", CLIs: []string{"claude"}, BaseDir: filepath.Join(repoRoot, ".claude", "skills"), Format: "directory", Mode: "copy"},
		{Label: "OpenCode", CLIs: []string{"opencode"}, BaseDir: filepath.Join(repoRoot, ".opencode", "commands"), Format: "flat", Mode: "copy"},
		{Label: "Agents dir", CLIs: []string{"codex", "agy", "kimi"}, BaseDir: filepath.Join(repoRoot, ".agents", "skills"), Format: "directory", Mode: "copy"},
	}

	agentsFound := 0
	var errs []error
	for _, agent := range agents {
		if !agentAvailable(agent.CLIs...) {
			fmt.Printf("Skipping %s: %s\n", agent.Label, missingCLIs(agent.CLIs))
			continue
		}

		// Per-target ordering: read the previous manifest (fab's ownership
		// record) → deploy → prune only what the previous manifest recorded
		// → write the new manifest.
		prev, hadManifest := readSkillManifest(agent.BaseDir, agent.Format)
		deployed, err := syncAgentSkills(agent, skills, skillsDir)
		if err != nil {
			errs = append(errs, err)
		}
		cleanStaleSkills(agent.BaseDir, agent.Format, prev, skills, hadManifest, repoRoot)
		if err == nil {
			// Only a fully successful deploy rewrites the manifest — a partial
			// deploy must not record ownership of skills that never landed.
			if werr := writeSkillManifest(agent.BaseDir, agent.Format, deployed); werr != nil {
				errs = append(errs, werr)
			}
		}
		agentsFound++
	}

	if agentsFound == 0 {
		fmt.Println("Warning: No agent CLIs found in PATH. Skills were not deployed to any agent.")
	}

	return errors.Join(errs...)
}

// listSkills returns the base names (without .md) of all skill files.
func listSkills(skillsDir string) []string {
	entries, err := os.ReadDir(skillsDir)
	if err != nil {
		return nil
	}
	var skills []string
	for _, e := range entries {
		if e.IsDir() {
			continue
		}
		name := e.Name()
		if strings.HasSuffix(name, ".md") {
			skills = append(skills, strings.TrimSuffix(name, ".md"))
		}
	}
	return skills
}

// agentAvailable reports whether ANY of the candidate CLIs is available. A target
// with a single candidate is the common case; the generic `.agents/skills` target
// passes the several CLIs that read that directory, and one of them being present
// is enough to deploy it.
// Respects FAB_AGENTS env var override, which likewise matches any candidate.
func agentAvailable(clis ...string) bool {
	if fabAgents, ok := os.LookupEnv("FAB_AGENTS"); ok {
		declared := strings.Fields(fabAgents)
		for _, cli := range clis {
			for _, a := range declared {
				if a == cli {
					return true
				}
			}
		}
		return false
	}
	for _, cli := range clis {
		if _, err := exec.LookPath(cli); err == nil {
			return true
		}
	}
	return false
}

// missingCLIs renders the "why this target was skipped" clause, matching the
// phrasing to the number of candidates. Only the generic `.agents/skills` target
// is gated on more than one CLI, so "none of claude found in PATH" would be a
// grammatical wart on every single-candidate target — and the plural form still
// has to name every candidate, since that list IS the actionable part (a user
// with none installed learns what would enable the target).
func missingCLIs(clis []string) string {
	if len(clis) == 1 {
		return clis[0] + " not found in PATH"
	}
	return "none of " + strings.Join(clis, ", ") + " found in PATH"
}

// syncAgentSkills deploys skills to an agent's directory and returns the list
// of skills actually deployed (created, repaired, or already valid) in kit
// order — the caller writes exactly that list as the target's manifest, so the
// manifest never claims ownership of a skipped or failed skill.
// Write/symlink/read failures are counted per-skill (never as created/
// repaired), surfaced on stderr, and returned as a non-nil error so Sync
// exits non-zero — deployed skills are the instructions agents execute, and
// a silent deploy failure means agents run stale skill versions.
func syncAgentSkills(agent agentConfig, skills []string, skillsDir string) ([]string, error) {
	if err := os.MkdirAll(agent.BaseDir, 0755); err != nil {
		return nil, fmt.Errorf("%s: cannot create %s: %w", agent.Label, agent.BaseDir, err)
	}

	created, repaired, ok, failed := 0, 0, 0, 0
	notDeployed := make(map[string]bool)
	var firstErr error
	fail := func(skill string, err error) {
		failed++
		notDeployed[skill] = true
		if firstErr == nil {
			firstErr = err
		}
		fmt.Fprintf(os.Stderr, "WARN: %s: failed to deploy %s: %v\n", agent.Label, skill, err)
	}

	for _, skill := range skills {
		src := filepath.Join(skillsDir, skill+".md")
		if _, err := os.Stat(src); os.IsNotExist(err) {
			fmt.Printf("WARN: kit/skills/%s.md missing in cache — skipping\n", skill)
			notDeployed[skill] = true
			continue
		}

		var dest string
		if agent.Format == "directory" {
			if err := os.MkdirAll(filepath.Join(agent.BaseDir, skill), 0755); err != nil {
				fail(skill, err)
				continue
			}
			dest = filepath.Join(agent.BaseDir, skill, "SKILL.md")
		} else {
			dest = filepath.Join(agent.BaseDir, skill+".md")
		}

		if agent.Mode == "copy" {
			srcData, err := os.ReadFile(src)
			if err != nil {
				fail(skill, fmt.Errorf("cannot read source: %w", err))
				continue
			}

			if info, err := os.Lstat(dest); err == nil && info.Mode()&os.ModeSymlink == 0 {
				// File exists and is not a symlink — compare content
				destData, _ := os.ReadFile(dest)
				if string(srcData) == string(destData) {
					ok++
				} else if err := os.WriteFile(dest, srcData, 0644); err != nil {
					fail(skill, err)
				} else {
					repaired++
				}
			} else if _, err := os.Lstat(dest); err == nil {
				// Exists as symlink or something else — replace. A failed
				// remove must not fall through to WriteFile: writing through
				// a leftover symlink would modify its target (e.g. the kit
				// cache) instead of replacing the entry.
				if err := os.Remove(dest); err != nil {
					fail(skill, fmt.Errorf("cannot replace existing entry: %w", err))
				} else if err := os.WriteFile(dest, srcData, 0644); err != nil {
					fail(skill, err)
				} else {
					repaired++
				}
			} else if err := os.WriteFile(dest, srcData, 0644); err != nil {
				fail(skill, err)
			} else {
				created++
			}
		} else {
			// Symlink mode — target is the absolute path in the cache
			target := filepath.Join(skillsDir, skill+".md")
			if info, err := os.Lstat(dest); err == nil && info.Mode()&os.ModeSymlink != 0 {
				// Symlink exists — check if target resolves
				if _, err := os.Stat(dest); err == nil {
					ok++
				} else {
					os.Remove(dest)
					if err := os.Symlink(target, dest); err != nil {
						fail(skill, err)
					} else {
						repaired++
					}
				}
			} else if _, err := os.Lstat(dest); err == nil {
				os.Remove(dest)
				if err := os.Symlink(target, dest); err != nil {
					fail(skill, err)
				} else {
					repaired++
				}
			} else if err := os.Symlink(target, dest); err != nil {
				fail(skill, err)
			} else {
				created++
			}
		}
	}

	total := created + repaired + ok
	var deployed []string
	for _, skill := range skills {
		if !notDeployed[skill] {
			deployed = append(deployed, skill)
		}
	}
	if failed > 0 {
		fmt.Printf("%-12s %d/%d (created %d, repaired %d, already valid %d, failed %d)\n",
			agent.Label+":", total, len(skills), created, repaired, ok, failed)
		return deployed, fmt.Errorf("%s: %d skill deployment(s) failed (first: %w)", agent.Label, failed, firstErr)
	}
	fmt.Printf("%-12s %d/%d (created %d, repaired %d, already valid %d)\n",
		agent.Label+":", total, len(skills), created, repaired, ok)
	return deployed, nil
}

// manifestPath returns the generated-manifest path for a deploy target.
func manifestPath(baseDir string) string {
	return filepath.Join(baseDir, manifestFileName)
}

// manifestEntry renders one anchored manifest/gitignore entry for a deployed
// skill in the target's format: `/{name}/` for directory, `/{name}.md` for flat.
func manifestEntry(format, name string) string {
	if format == "directory" {
		return "/" + name + "/"
	}
	return "/" + name + ".md"
}

// parseManifestEntry reverses manifestEntry: it strips the leading anchor and
// the format-specific suffix, returning the skill name and whether the line
// was a well-formed anchored entry. Comment lines, blank lines, the self-entry
// and anything not matching the format's shape are skipped (ok == false) —
// a corrupt line must never be fatal.
func parseManifestEntry(format, line string) (string, bool) {
	if line == "" || strings.HasPrefix(line, "#") || line == manifestSelfEntry {
		return "", false
	}
	if !strings.HasPrefix(line, "/") {
		return "", false
	}
	body := strings.TrimPrefix(line, "/")
	if format == "directory" {
		name := strings.TrimSuffix(body, "/")
		return name, name != "" && name != body
	}
	name := strings.TrimSuffix(body, ".md")
	return name, name != "" && name != body
}

// readSkillManifest reads a target's generated manifest back into the set of
// skill names fab previously deployed there. The second return reports whether
// a manifest existed at all — its absence means fab has no ownership record
// for the directory and must prune nothing. A .gitignore counts as fab's
// manifest only when it carries the generated header for the target's format;
// a user's own pre-existing .gitignore is not an ownership record — treating
// it as one would scope pruning to the user's entries and delete their content.
func readSkillManifest(baseDir, format string) (map[string]bool, bool) {
	data, err := os.ReadFile(manifestPath(baseDir))
	if err != nil {
		return nil, false
	}
	header := manifestHeaderCmds
	if format == "directory" {
		header = manifestHeaderSkills
	}
	if !strings.HasPrefix(string(data), header) {
		return nil, false
	}
	owned := make(map[string]bool)
	for _, line := range strings.Split(string(data), "\n") {
		if name, ok := parseManifestEntry(format, strings.TrimSpace(line)); ok {
			owned[name] = true
		}
	}
	return owned, true
}

// writeSkillManifest writes the target's generated manifest as a
// whole-file-owned artifact (overwrite, byte-stable for the same deployed
// list): two header comment lines, the self-entry, then one anchored entry
// per deployed skill in the given (kit-list) order, with a trailing newline.
// A write failure propagates so Sync exits non-zero (jznd fail-loud contract).
func writeSkillManifest(baseDir, format string, deployed []string) error {
	header := manifestHeaderCmds
	if format == "directory" {
		header = manifestHeaderSkills
	}
	var b strings.Builder
	b.WriteString(header)
	b.WriteString(manifestSelfEntry + "\n")
	for _, name := range deployed {
		b.WriteString(manifestEntry(format, name) + "\n")
	}
	if err := os.WriteFile(manifestPath(baseDir), []byte(b.String()), 0644); err != nil {
		return fmt.Errorf("cannot write manifest %s: %w", manifestPath(baseDir), err)
	}
	return nil
}

// cleanStaleSkills removes skill entries fab previously deployed that are no
// longer in the canonical kit list. `prev` is the ownership record read from
// the target's manifest BEFORE this sync's deploy; an entry is pruned only
// when it is in `prev` and absent from `skills` — anything fab never recorded
// (user-added skills/commands) is never touched. When no manifest exists
// (first sync after the upgrade, or a fresh target), nothing is pruned; if
// the directory held a non-kit entry, one note is printed instead.
func cleanStaleSkills(baseDir, format string, prev map[string]bool, skills []string, hadManifest bool, repoRoot string) {
	if !dirExists(baseDir) {
		return
	}

	skillSet := make(map[string]bool)
	for _, s := range skills {
		skillSet[s] = true
	}

	entries, _ := os.ReadDir(baseDir)

	if !hadManifest {
		// No ownership record — pruning here would guess, and guessing wrong
		// deletes user skills. Warn once when there is anything worth warning
		// about: any entry that isn't a kit skill in this target's format
		// (a stray directory in a flat target, a stray file in a directory
		// target). A fresh, kit-only directory prints nothing.
		for _, e := range entries {
			if e.Name() == manifestFileName {
				continue
			}
			name := e.Name()
			kitEntry := false
			if format == "flat" {
				if !e.IsDir() && strings.HasSuffix(name, ".md") {
					kitEntry = skillSet[strings.TrimSuffix(name, ".md")]
				}
			} else if e.IsDir() {
				kitEntry = skillSet[name]
			}
			if !kitEntry {
				rel, _ := filepath.Rel(repoRoot, baseDir)
				fmt.Printf(noManifestNoteFormat, rel)
				return
			}
		}
		return
	}

	removed := 0
	for _, e := range entries {
		name := e.Name()
		if format == "directory" {
			if !e.IsDir() {
				continue
			}
		} else {
			if e.IsDir() || !strings.HasSuffix(name, ".md") {
				continue
			}
			name = strings.TrimSuffix(name, ".md")
		}
		if prev[name] && !skillSet[name] {
			os.RemoveAll(filepath.Join(baseDir, e.Name()))
			removed++
		}
	}

	if removed > 0 {
		rel, _ := filepath.Rel(repoRoot, baseDir)
		fmt.Printf("Cleaned: %d stale entries from %s\n", removed, rel)
	}
}

// cleanLegacyAgents removes .claude/agents/ files matching known skill names.
func cleanLegacyAgents(repoRoot, kitDir string) {
	agentsDir := filepath.Join(repoRoot, ".claude", "agents")
	if !dirExists(agentsDir) {
		return
	}

	skills := listSkills(filepath.Join(kitDir, "skills"))
	skillSet := make(map[string]bool)
	for _, s := range skills {
		skillSet[s] = true
	}

	staleAgents := 0
	entries, _ := os.ReadDir(agentsDir)
	for _, e := range entries {
		name := e.Name()
		if !strings.HasSuffix(name, ".md") {
			continue
		}
		stem := strings.TrimSuffix(name, ".md")
		if skillSet[stem] {
			os.Remove(filepath.Join(agentsDir, name))
			staleAgents++
		}
	}

	if staleAgents > 0 {
		fmt.Printf("Cleaned: %d stale agent files from .claude/agents/\n", staleAgents)
	}
}
