// Package configupgrade mechanically reconciles fab/project/config.yaml against
// the binary-owned field registry (internal/configref). It is the ONLY writer of
// config.yaml going forward (Change 3 of the config-upgrade effort): the
// comment-clobbering setFabVersion masher is deleted, so every config.yaml write
// flows through this comment-aware, byte-stable path.
//
// THE FIELD-CATEGORY MODEL (docs/specs/config.md § Advertise semantics). At upgrade
// time every registry field is one of:
//   - A) live (user-overridden)     → kept VERBATIM above the managed fence,
//     including the user's own comments. Presence = intent: a live field is an
//     override even when its value equals the default; NEVER auto-removed.
//   - B) not overridden              → absent (inherited from defaults).
//   - C) not overridden, advertise:true → regenerated as a fully-commented scaffold
//     INSIDE the managed fence, so the user can discover and opt in.
//
// THE MANAGED FENCE. A region delimited by byte-exact splice anchors:
//
//	# >>> fab reference (kit X.Y.Z) >>> ----…
//	…commented C-field scaffold…
//	# <<< end fab reference <<< ----…
//
// Upgrade rewrites ONLY the region between (and including) the two anchor lines;
// everything outside is the user's. A legacy file with no fence gets one appended
// at the bottom. The kit-version stamp in the BEGIN line makes staleness visible
// (it enables a later --check drift mode — NOT in this change). Every scaffolded
// block is fully commented INCLUDING parent keys (a live `agent:` key over
// comment-only children is exactly what the old masher collapsed to `agent: null`).
// The fence omits fields already overridden as live keys above it.
//
// PARKED REMOVALS. A live top-level key no longer in the registry is parked in a
//
//	# removed in X.Y.Z (parked by fab config upgrade — delete when done):
//	#   key: value
//
// block BELOW the fence, its value serialized in the comment — never silently
// deleted. Parkings are user territory: appended exactly once, never regenerated
// away on a later run.
//
// RENAMES. A live top-level key matching some registry row's renamed_from is
// carried to the new key mechanically (value verbatim), replacing the per-rename
// hand-written-migration pattern. renamed_from is "" on every row today, so this
// path fires only for a seeded rename.
//
// OUTPUT DISCIPLINE. Byte-stable and idempotent — running Upgrade twice yields a
// byte-identical file (the internal/memoryindex precedent: pure renders, golden +
// idempotence tests). The write goes through internal/atomicfile.WriteFile.
package configupgrade

import (
	"encoding/json"
	"fmt"
	"os"
	"regexp"
	"sort"
	"strings"

	"gopkg.in/yaml.v3"

	"github.com/sahil87/fab-kit/src/go/fab/internal/atomicfile"
	"github.com/sahil87/fab-kit/src/go/fab/internal/configref"
)

// fenceWidth is the total column width the anchor lines are dash-padded to, so the
// BEGIN and END rules line up as a visible box (matching the worked example in
// fab/plans/sahil/config-upgrade.md § The fence).
const fenceWidth = 76

// beginPrefix / endPrefix are the byte-exact splice-anchor prefixes. The full
// anchor line is the prefix followed by a run of `-` padding out to fenceWidth.
// beginPrefix carries a `%s` for the kit-version stamp.
const (
	beginPrefix = "# >>> fab reference (kit %s) >>> "
	endPrefix   = "# <<< end fab reference <<< "
)

// beginLineRe matches the fence BEGIN anchor regardless of the stamped version or
// the dash-pad width, so a re-run finds the existing fence even after a version
// bump changed the stamp. endLineRe matches the END anchor likewise.
var (
	beginLineRe = regexp.MustCompile(`^# >>> fab reference \(kit [^)]*\) >>> -*\s*$`)
	endLineRe   = regexp.MustCompile(`^# <<< end fab reference <<< -*\s*$`)
)

// parkedHeaderRe matches a parked-removal block header (any version phrasing), so
// a re-run recognizes an already-parked block and never re-parks the same key. The
// version portion may contain spaces ("an earlier release"), so match lazily up to
// the fixed "(parked by fab config upgrade" marker.
var parkedHeaderRe = regexp.MustCompile(`^# removed in .+ \(parked by fab config upgrade`)

// fenceHeaderComment is the fixed explanatory preamble emitted at the top of the
// fence body (between the BEGIN anchor and the commented C-field scaffold).
const fenceHeaderComment = `# Overridable fields you have NOT overridden, with current defaults.
# REGENERATED by ` + "`fab config upgrade`" + ` on every upgrade — edits inside this
# fence are overwritten. To override a field: move it ABOVE the fence and
# uncomment it.`

// Result reports what an Upgrade run did, for the command's advisory output.
type Result struct {
	// Changed is true when the on-disk file was rewritten (false = already
	// byte-identical, a no-op).
	Changed bool
	// Report holds advisory lines for the user (B-hygiene notes, parked-key
	// notices, rename carries). Never fatal — informational only.
	Report []string
}

// Upgrade reconciles the config.yaml at path against the registry, stamping the
// fence with kitVersion. It preserves live (A) fields verbatim, regenerates the
// managed fence of commented C fields, parks unknown live keys once below the
// fence, and carries renamed_from renames. The write is atomic and the output is
// byte-stable/idempotent. A missing file is treated as empty (a fresh fence-only
// file is written).
func Upgrade(path, kitVersion string) (Result, error) {
	fields, err := configref.Fields()
	if err != nil {
		return Result{}, err
	}

	original, existed, err := readFile(path)
	if err != nil {
		return Result{}, err
	}

	rendered, report := render(original, fields, kitVersion)

	// Refuse to write YAML that does not parse (SF-c defense-in-depth). The
	// comment-aware splice manipulates raw lines, so a pathological input (e.g. an
	// interior column-0 comment inside a live block) could in principle produce
	// malformed YAML; a config that fails to load bricks every fab command, so we
	// validate the rendered bytes and refuse — surfacing the parse error — rather
	// than overwrite the user's file with something unparseable. The original file
	// is left untouched.
	if err := validateYAML(rendered); err != nil {
		return Result{}, fmt.Errorf("configupgrade: refusing to write %s — the reconciled output does not parse as YAML (%w); the file was left unchanged", path, err)
	}

	if existed && rendered == original {
		return Result{Changed: false, Report: report}, nil
	}
	if err := atomicfile.WriteFile(path, []byte(rendered), 0o644); err != nil {
		return Result{}, fmt.Errorf("configupgrade: writing %s: %w", path, err)
	}
	return Result{Changed: true, Report: report}, nil
}

// validateYAML reports whether s parses as a YAML document (into a generic map),
// so Upgrade can refuse to write a file that would fail to load. Comments and the
// fully-commented fence are inert to the parser; only the live keys are validated.
func validateYAML(s string) error {
	var m map[string]any
	return yaml.Unmarshal([]byte(s), &m)
}

// InitSeed carries the A-class identity values `fab config init --project` writes
// LIVE above the managed fence on a fresh repo. Any field left empty is omitted
// from the live block (and, for test_paths, left to the fence to advertise). Every
// other config field is fence territory from day one — presence=intent means an
// init-pinned tier would be an accidental override.
type InitSeed struct {
	Name        string
	Description string
	SourcePaths []string
	TestPaths   []string
}

// RenderInitProject generates a fresh fab/project/config.yaml for `fab config init
// --project`: the seeded A-class identity block (name/description/source_paths, and
// test_paths when detected) written LIVE, followed by the managed fence of
// commented C fields. It shares the exact fence renderer Upgrade uses (renderFence),
// so a freshly-generated file and an upgraded one carry a byte-identical fence.
// agent.tiers is deliberately NOT pinned (presence=intent). The fence omits the
// seeded live keys.
func RenderInitProject(seed InitSeed, kitVersion string) (string, error) {
	fields, err := configref.Fields()
	if err != nil {
		return "", err
	}

	preamble := renderInitPreamble(seed)
	liveKeys := liveTopLevelKeys(preamble)
	fence := renderFence(fields, liveKeys, kitVersion)
	return assemble(preamble, fence, nil, nil), nil
}

// initHeader is the top-of-file banner the generated project config carries — it
// states the presence=override contract so a reader knows why a field being live
// is meaningful.
const initHeader = `# fab/project/config.yaml — project overrides.
# Presence = override: any live field here wins over ~/.fab-kit/config.yaml and
# built-in defaults, even if its value equals the default. Generated by
# ` + "`fab config init`" + `; reconciled on every upgrade by ` + "`fab config upgrade`" + `.`

// renderInitPreamble emits the seeded identity block: the header banner then the
// live A-class fields present in the seed. Absent seed values are omitted (their
// fields stay fence-advertised where advertise:true). Output is deterministic.
func renderInitPreamble(seed InitSeed) string {
	var b strings.Builder
	b.WriteString(initHeader)

	if seed.Name != "" || seed.Description != "" {
		b.WriteString("\n\nproject:")
		if seed.Name != "" {
			fmt.Fprintf(&b, "\n    name: %s", yamlScalar(seed.Name))
		}
		if seed.Description != "" {
			fmt.Fprintf(&b, "\n    description: %s", yamlScalar(seed.Description))
		}
	}

	if len(seed.SourcePaths) > 0 {
		b.WriteString("\n\nsource_paths:")
		for _, p := range seed.SourcePaths {
			fmt.Fprintf(&b, "\n    - %s", yamlScalar(p))
		}
	}

	if len(seed.TestPaths) > 0 {
		b.WriteString("\n\ntest_paths:")
		for _, p := range seed.TestPaths {
			fmt.Fprintf(&b, "\n    - %s", yamlScalar(p))
		}
	}

	return b.String()
}

// yamlScalar renders a string as a YAML scalar, quoting it when it contains a
// character that would need quoting (a glob `*`, a leading/trailing space, a colon,
// a `#`, a backslash, a control character, or another YAML-significant indicator).
// Config identity values are simple strings; the conservative quoting keeps glob
// test-path patterns (`**/*_test.go`) valid. When quoting, a backslash and an
// embedded double-quote are BOTH escaped (a raw `\` inside a double-quoted YAML
// scalar is itself an escape lead-in — leaving it unescaped would corrupt the value
// or produce invalid YAML), and control characters are escaped so the emitted line
// is always parseable.
func yamlScalar(s string) string {
	if s == "" {
		return `""`
	}
	if strings.ContainsAny(s, "*:#{}[]&!|>%@`\"'\\") || s != strings.TrimSpace(s) || hasControlChar(s) {
		var b strings.Builder
		b.WriteByte('"')
		for _, r := range s {
			switch r {
			case '\\':
				b.WriteString(`\\`)
			case '"':
				b.WriteString(`\"`)
			case '\n':
				b.WriteString(`\n`)
			case '\t':
				b.WriteString(`\t`)
			case '\r':
				b.WriteString(`\r`)
			default:
				if r < 0x20 {
					fmt.Fprintf(&b, `\x%02x`, r)
					continue
				}
				b.WriteRune(r)
			}
		}
		b.WriteByte('"')
		return b.String()
	}
	return s
}

// hasControlChar reports whether s contains an ASCII control character (< 0x20),
// which must be escaped inside a double-quoted YAML scalar.
func hasControlChar(s string) bool {
	for _, r := range s {
		if r < 0x20 {
			return true
		}
	}
	return false
}

// readFile reads path, returning ("", false, nil) when it does not exist.
func readFile(path string) (string, bool, error) {
	data, err := os.ReadFile(path)
	if err != nil {
		if os.IsNotExist(err) {
			return "", false, nil
		}
		return "", false, err
	}
	return string(data), true, nil
}

// render is the pure core: given the original file text, the registry fields, and
// the kit-version stamp, it returns the reconciled file text and the advisory
// report. Extracted from Upgrade (which owns file I/O) so it is directly
// unit-testable and provably deterministic.
func render(original string, fields []configref.Field, kitVersion string) (string, []string) {
	var report []string

	preamble, belowFence, existingParked := splitFence(original)

	// Everything outside the fence is the user's and is NEVER silently dropped.
	// Non-parked content the user placed BELOW the fence (e.g. a live override
	// appended after the END anchor) is hoisted ABOVE the fence into the preamble,
	// where it is classified exactly like any other live key (kept verbatim if
	// known, parked if unknown, carried if renamed). This makes the layout
	// self-healing: the next run re-parses it as an ordinary live A field. See R2.1.
	if strings.TrimSpace(belowFence) != "" {
		preamble = strings.TrimRight(preamble, "\n") + "\n" + strings.TrimLeft(belowFence, "\n")
	}

	// Live top-level keys the user has above the fence (the A set), plus their
	// verbatim source blocks for rename carry-forward.
	liveKeys := liveTopLevelKeys(preamble)

	// Carry renames: a live key matching some row's RenamedFrom is rewritten to the
	// new key in place (value verbatim). renamed_from is "" on every row today.
	preamble, liveKeys, renameReport := carryRenames(preamble, liveKeys, fields)
	report = append(report, renameReport...)

	// Park unknown live keys (live top-level keys not documented by any registry
	// row and not the fence/parked markers). Removed from the live preamble,
	// appended once below the fence.
	preamble, newlyParked := extractUnknownLiveKeys(preamble, fields)

	// Build the fence: the C fields (advertise:true) NOT already live above it.
	fence := renderFence(fields, liveKeys, kitVersion)

	// B-hygiene advisory (presence=intent — never a mutation): live fields whose
	// value equals the current default. Reported only, never removed.
	report = append(report, bHygieneReport(preamble, fields)...)

	out := assemble(preamble, fence, existingParked, newlyParked)
	for _, k := range sortedKeys(newlyParked) {
		report = append(report, fmt.Sprintf("parked removed field %q below the fence (delete when done)", k))
	}
	return out, report
}

// splitFence divides the original file into three parts:
//   - preamble: the content BEFORE the fence (the user's live A fields and comments).
//   - belowFence: NON-parked content found AFTER the END anchor — the user's, and
//     NEVER dropped. The caller hoists it above the regenerated fence so it is
//     classified like any other live key (R2.1). Empty in a well-formed fab-written
//     file; non-empty when the user appended an override below the fence.
//   - parked: the parked-removal comment blocks below the fence, preserved verbatim.
//
// The fence body itself is discarded (it is regenerated). When no fence exists,
// everything is preamble (parked blocks are only ever created by Upgrade, below a
// fence, so a fence-less file has neither parked blocks nor below-fence content).
func splitFence(original string) (preamble, belowFence string, parked []string) {
	if original == "" {
		return "", "", nil
	}
	lines := strings.Split(original, "\n")

	beginIdx, endIdx := -1, -1
	for i, ln := range lines {
		if beginIdx == -1 && beginLineRe.MatchString(ln) {
			beginIdx = i
			continue
		}
		if beginIdx != -1 && endLineRe.MatchString(ln) {
			endIdx = i
			break
		}
	}

	if beginIdx == -1 || endIdx == -1 {
		// No fence — the whole file is preamble (parked blocks never exist without
		// a fence, since only Upgrade writes them and it always writes a fence).
		return original, "", nil
	}

	pre := strings.Join(lines[:beginIdx], "\n")
	post := lines[endIdx+1:]
	parked, nonParked := extractParkedBlocks(post)
	return pre, strings.Join(nonParked, "\n"), parked
}

// extractParkedBlocks separates the post-fence lines into the parked-removal blocks
// (each `# removed in …` header plus the contiguous `#`-prefixed / blank lines up to
// the next parked header or live line) and the NON-parked remainder. A parked block
// stays below the fence verbatim; the non-parked remainder is the user's own content
// (a live override they appended below the fence) and is returned separately so the
// caller can hoist it above the fence rather than drop it (R2.1). Blank lines that
// sit between blocks are attributed to neither list (they are structural padding the
// assembler re-inserts), so a fab-written file round-trips with only its parked
// blocks preserved and no spurious blank-line churn.
func extractParkedBlocks(lines []string) (parked []string, nonParked []string) {
	for i := 0; i < len(lines); {
		if strings.TrimSpace(lines[i]) == "" {
			// Structural padding between blocks — belongs to neither list.
			i++
			continue
		}
		if parkedHeaderRe.MatchString(lines[i]) {
			start := i
			i++
			for i < len(lines) && (strings.HasPrefix(lines[i], "#") || strings.TrimSpace(lines[i]) == "") {
				// Stop at the next parked header — it starts its own block.
				if parkedHeaderRe.MatchString(lines[i]) {
					break
				}
				i++
			}
			// Trim trailing blank lines that trailed into this block's capture.
			block := strings.TrimRight(strings.Join(lines[start:i], "\n"), "\n")
			parked = append(parked, block)
			continue
		}
		// A non-parked, non-blank line: the user's own below-fence content. Preserve
		// it (and any following lines up to the next parked header) for hoisting.
		start := i
		i++
		for i < len(lines) && !parkedHeaderRe.MatchString(lines[i]) {
			i++
		}
		nonParked = append(nonParked, strings.TrimRight(strings.Join(lines[start:i], "\n"), "\n"))
	}
	return parked, nonParked
}

// topLevelKeyRe matches a live (non-commented, column-0) `key:` line, capturing the
// key. Indented lines and `#` comments are deliberately excluded — this collects
// exactly the top-level live keys (the A set / override units).
var topLevelKeyRe = regexp.MustCompile(`^([A-Za-z_][A-Za-z0-9_]*):(\s|$)`)

// liveTopLevelKeys returns the set of live top-level keys present in the preamble.
func liveTopLevelKeys(preamble string) map[string]bool {
	keys := map[string]bool{}
	for _, ln := range strings.Split(preamble, "\n") {
		if m := topLevelKeyRe.FindStringSubmatch(ln); m != nil {
			keys[m[1]] = true
		}
	}
	return keys
}

// registryTopLevelKeys returns the set of top-level keys the registry documents
// (the dotted keys collapsed to their first segment), plus the TOP-LEVEL rename map
// used by carryRenames.
//
// Rename carry is a TOP-LEVEL-key operation: the upgrader rewrites the column-0
// `key:` token and preserves the whole value block verbatim, so it can only carry a
// rename whose old and new keys are DIFFERENT top-level keys. Two registry shapes
// are therefore deliberately excluded from the rename map:
//   - a same-top-level rename (e.g. `a.x` → `a.y`, both under top-level `a`) —
//     collapsing to `a` → `a` is a no-op that would otherwise log a spurious
//     "carried rename" line on every run;
//   - a nested rename (a renamed_from whose top-level segment differs but which is
//     itself a nested key, e.g. `a.x` → `b.y`) — carrying it as a whole-`a:`-block
//     rename to `b:` would corrupt the value, so it is left for a future
//     nested-aware carry rather than mishandled here.
//
// Both are detected by comparing the FULL dotted keys, not just their first
// segments. renamed_from is "" on every shipped row today, so the map is empty in
// production; the guard matters for seeded-rename fixtures and future renames.
func registryTopLevelKeys(fields []configref.Field) (known map[string]bool, renames map[string]string) {
	known = map[string]bool{}
	renames = map[string]string{}
	for _, f := range fields {
		known[topLevel(f.Key)] = true
		if f.RenamedFrom == "" {
			continue
		}
		oldTop, newTop := topLevel(f.RenamedFrom), topLevel(f.Key)
		// Only a genuine top-level→top-level rename is carriable here: both the
		// old and new keys must be bare top-level keys (no dotted suffix) AND
		// distinct. A same-top-level or nested rename is skipped (see doc above).
		if oldTop == newTop || strings.Contains(f.RenamedFrom, ".") || strings.Contains(f.Key, ".") {
			continue
		}
		renames[oldTop] = newTop
	}
	return known, renames
}

// carryRenames rewrites a live top-level key that matches a registry row's
// renamed_from to the new key (value verbatim), updating the live-key set. Only the
// key token on the top-level line is rewritten; the value and any nested block are
// preserved byte-for-byte.
//
// It SKIPS a carry (and reports the skip) when the target key is already live: yaml
// v3 rejects a duplicate top-level key, so blindly renaming `old` → `new` when the
// user already has a live `new:` would produce a config that fails to load and
// bricks every fab command (violating fail-open). When both keys are present the
// user's explicit `new:` wins and `old` is left in place for the unknown-key parker
// to handle.
func carryRenames(preamble string, liveKeys map[string]bool, fields []configref.Field) (string, map[string]bool, []string) {
	_, renames := registryTopLevelKeys(fields)
	if len(renames) == 0 {
		return preamble, liveKeys, nil
	}
	var report []string
	lines := strings.Split(preamble, "\n")
	for i, ln := range lines {
		m := topLevelKeyRe.FindStringSubmatch(ln)
		if m == nil {
			continue
		}
		old := m[1]
		newKey, ok := renames[old]
		if !ok {
			continue
		}
		if liveKeys[newKey] {
			// Target already live — a carry would emit a duplicate top-level key
			// (yaml.v3 rejects it → LoadPath errors → every fab command bricks).
			// Leave `old` in place (the parker handles it) and note the skip.
			report = append(report, fmt.Sprintf("skipped rename %q → %q (target key already set; left %q in place)", old, newKey, old))
			continue
		}
		lines[i] = newKey + ln[len(old):]
		delete(liveKeys, old)
		liveKeys[newKey] = true
		report = append(report, fmt.Sprintf("carried rename %q → %q (value preserved)", old, newKey))
	}
	return strings.Join(lines, "\n"), liveKeys, report
}

// extractUnknownLiveKeys removes live top-level keys not documented by any registry
// row from the preamble and returns them as key→serialized-block for parking. The
// serialized block is the key's own top-level line and any following indented lines
// (its value), captured verbatim for the parked comment.
func extractUnknownLiveKeys(preamble string, fields []configref.Field) (string, map[string]string) {
	known, _ := registryTopLevelKeys(fields)
	lines := strings.Split(preamble, "\n")

	parked := map[string]string{}
	var kept []string
	for i := 0; i < len(lines); {
		m := topLevelKeyRe.FindStringSubmatch(lines[i])
		if m == nil {
			kept = append(kept, lines[i])
			i++
			continue
		}
		key := m[1]
		// Capture the block: the key line plus any following indented/blank lines
		// (and interior column-0 comments) that belong to its value, up to the next
		// top-level key or a column-0 line that starts fresh content.
		start := i
		i++
		i = advancePastBlock(lines, i)
		block := lines[start:i]
		if known[key] {
			kept = append(kept, block...)
			continue
		}
		parked[key] = strings.TrimRight(strings.Join(block, "\n"), "\n")
	}
	return strings.Join(kept, "\n"), parked
}

// advancePastBlock returns the index of the first line AFTER the value block that
// began before `start`. An indented line (space/tab lead) or a blank line is part of
// the block. A column-0 `#` comment is INTERIOR to the block — and thus part of it —
// only when indented block content resumes before the next top-level key; a trailing
// column-0 comment that is NOT followed by more indented content ends the block (it
// belongs to whatever comes next, typically the following key's own comment). This
// keeps a user's live block with an interior column-0 comment intact rather than
// splitting it and orphaning the indented lines below the comment (which would
// render unparseable YAML). See SF-c.
func advancePastBlock(lines []string, start int) int {
	i := start
	for i < len(lines) {
		ln := lines[i]
		if ln == "" || ln[0] == ' ' || ln[0] == '\t' {
			i++
			continue
		}
		if strings.HasPrefix(ln, "#") {
			// A column-0 comment continues the block only if indented content
			// resumes before the next top-level key. Look ahead.
			if commentPrecedesBlockContinuation(lines, i+1) {
				i++
				continue
			}
			return i
		}
		// A column-0 non-comment, non-blank line — a new top-level key or other
		// fresh content. The block ends here.
		return i
	}
	return i
}

// commentPrecedesBlockContinuation reports whether, scanning forward from idx over a
// run of column-0 comments and blank lines, the first non-comment/non-blank line is
// an INDENTED line (block continuation) rather than a fresh column-0 key. Used to
// decide whether a column-0 comment is interior to the current block.
func commentPrecedesBlockContinuation(lines []string, idx int) bool {
	for i := idx; i < len(lines); i++ {
		ln := lines[i]
		if ln == "" || strings.HasPrefix(ln, "#") {
			continue
		}
		return ln[0] == ' ' || ln[0] == '\t'
	}
	return false
}

// renderFence builds the managed fence: the BEGIN anchor (stamped with kitVersion),
// the fixed header comment, the fully-commented Segment of each advertise:true field
// NOT already live above the fence, then the END anchor. Fields are emitted in
// registry order for byte-stability.
func renderFence(fields []configref.Field, liveKeys map[string]bool, kitVersion string) string {
	var b strings.Builder
	b.WriteString(anchorLine(fmt.Sprintf(beginPrefix, kitVersion)))
	b.WriteString("\n")
	b.WriteString(fenceHeaderComment)

	for _, f := range fields {
		if !f.Advertise || f.Segment == "" {
			continue
		}
		if liveKeys[topLevel(f.Key)] {
			continue // already overridden above the fence — not re-advertised
		}
		b.WriteString("\n#\n")
		b.WriteString(CommentOutSegment(f.Segment))
	}

	b.WriteString("\n")
	b.WriteString(anchorLine(endPrefix))
	return b.String()
}

// anchorLine pads prefix with `-` out to fenceWidth (never truncating a longer
// prefix). Exactly one trailing space in the prefix separates the label from the
// dash rule, matching the worked example.
func anchorLine(prefix string) string {
	if len(prefix) >= fenceWidth {
		return prefix
	}
	return prefix + strings.Repeat("-", fenceWidth-len(prefix))
}

// CommentOutSegment ensures every non-blank line of a rendered reference Segment is
// a comment, so the scaffolded block is fully inert (including its parent keys —
// the exact thing the old masher collapsed to `agent: null`). A line already
// starting with `#` is left as-is; a live line gains a leading `# `; blank lines
// stay blank. It is the SINGLE comment-out helper shared by the managed fence
// (here) and `fab config init --system` (cmd/fab), which imports it — there is no
// second copy.
func CommentOutSegment(segment string) string {
	lines := strings.Split(segment, "\n")
	for i, ln := range lines {
		trimmed := strings.TrimSpace(ln)
		if trimmed == "" {
			continue
		}
		if strings.HasPrefix(trimmed, "#") {
			continue
		}
		lines[i] = "# " + ln
	}
	return strings.Join(lines, "\n")
}

// assemble stitches the final file: preamble, a blank separator, the fence, then the
// parked-removal blocks (existing first — preserved order — then newly parked, sorted
// for determinism). The result always ends in exactly one trailing newline.
func assemble(preamble, fence string, existingParked []string, newlyParked map[string]string) string {
	var b strings.Builder

	pre := strings.TrimRight(preamble, "\n")
	if pre != "" {
		b.WriteString(pre)
		b.WriteString("\n\n")
	}
	b.WriteString(fence)

	allParked := append([]string{}, existingParked...)
	for _, k := range sortedKeys(newlyParked) {
		allParked = append(allParked, renderParkedBlock(k, newlyParked[k]))
	}
	for _, blk := range allParked {
		b.WriteString("\n\n")
		b.WriteString(strings.TrimRight(blk, "\n"))
	}

	b.WriteString("\n")
	return b.String()
}

// renderParkedBlock formats one parked removal: the header line, then the removed
// key's serialized block indented under a `#   ` comment prefix.
func renderParkedBlock(key, block string) string {
	var b strings.Builder
	b.WriteString("# removed in " + parkedVersionPlaceholder + " (parked by fab config upgrade — delete when done):")
	for _, ln := range strings.Split(block, "\n") {
		b.WriteString("\n#   ")
		b.WriteString(ln)
	}
	return b.String()
}

// parkedVersionPlaceholder is the version stamped into a parked-removal header.
// The registry does not carry the release in which a field was removed (the row is
// simply gone), so the header uses a stable "an earlier release" phrasing rather
// than inventing a version. This keeps the block byte-stable across runs (a
// version-specific header would churn on every kit bump). The literal is a named
// constant so a future registry that DOES record removal versions can key on it.
const parkedVersionPlaceholder = "an earlier release"

// bHygieneReport is the presence=intent advisory (decision 2 / R2.1): it lists live
// top-level keys whose value equals the current built-in default — a field the user
// could remove and inherit the same value. It is ADVISORY ONLY: the upgrader never
// removes or mutates a live field, so a false positive here costs nothing. Only
// registry fields carrying a non-nil Default (today `providers` and `agent.tiers`)
// can match; every other field has no built-in default, so a live value there is
// always a genuine override and is never flagged.
//
// The comparison parses the live preamble into a generic map, normalizes each
// registry Default through the same JSON round-trip the origin listing uses (the
// default structs carry json: tags matching the config keys), and deep-compares the
// live subtree against it. A parse failure yields no findings (advisory — never
// fatal). Reports are stable-ordered by registry order.
func bHygieneReport(preamble string, fields []configref.Field) []string {
	var live map[string]any
	if err := yaml.Unmarshal([]byte(preamble), &live); err != nil || live == nil {
		return nil // can't parse (or nothing live) → no advisory (never fatal)
	}
	seen := map[string]bool{}
	var report []string
	for _, f := range fields {
		if f.Default == nil {
			continue // no built-in default → a live value is always a real override
		}
		top := topLevel(f.Key)
		if seen[top] {
			continue // one advisory per top-level key (agent.tiers → agent)
		}
		liveVal, ok := live[top]
		if !ok {
			continue // not a live key → nothing to compare
		}
		seen[top] = true
		def := defaultSubtreeFor(fields, top)
		if def == nil {
			continue
		}
		if genericEqual(normalizeToGeneric(liveVal), def) {
			report = append(report, fmt.Sprintf("field %q equals the current default — you can remove it to inherit (kept as-is: presence=intent)", top))
		}
	}
	return report
}

// defaultSubtreeFor builds the built-in default subtree for a top-level key from the
// registry, nesting the row's Default under the remaining dotted segments
// (agent.tiers → {tiers: <default>} under `agent`). Mirrors cmd/fab's
// defaultSubtree; kept here so the engine has no dependency on cmd/fab. Returns nil
// when no row carries a default for the key.
func defaultSubtreeFor(fields []configref.Field, top string) any {
	for _, f := range fields {
		if f.Default == nil {
			continue
		}
		segs := strings.Split(f.Key, ".")
		if segs[0] != top {
			continue
		}
		normalized := normalizeToGeneric(f.Default)
		for i := len(segs) - 1; i >= 1; i-- {
			normalized = map[string]any{segs[i]: normalized}
		}
		return normalized
	}
	return nil
}

// genericEqual deep-compares two decoded-YAML/JSON generic values (maps, slices,
// scalars) for structural equality, tolerating the map[string]any vs map[any]any
// shape difference yaml.v3 can produce. Scalars compare by their formatted string so
// an int from JSON and an int from YAML (or an untyped number) compare equal without
// per-numeric-type branching — config values are strings/lists/maps, so no precision
// concern applies.
func genericEqual(a, b any) bool {
	am, aok := asGenericMap(a)
	bm, bok := asGenericMap(b)
	if aok || bok {
		if !aok || !bok || len(am) != len(bm) {
			return false
		}
		for k, av := range am {
			bv, ok := bm[k]
			if !ok || !genericEqual(av, bv) {
				return false
			}
		}
		return true
	}
	as, aok := a.([]any)
	bs, bok := b.([]any)
	if aok || bok {
		if !aok || !bok || len(as) != len(bs) {
			return false
		}
		for i := range as {
			if !genericEqual(as[i], bs[i]) {
				return false
			}
		}
		return true
	}
	return fmt.Sprintf("%v", a) == fmt.Sprintf("%v", b)
}

// normalizeToGeneric round-trips a typed value (a registry Default struct/map) into
// the generic map[string]any/[]any/scalar shape decoded YAML uses, so the two sides
// of a B-hygiene comparison are the same shape. It marshals via JSON, NOT YAML: the
// registry default structs (providerDefault, tierProfileDefault) carry json: tags
// whose names match the real config keys (session_command, provider, model, effort)
// and no yaml: tags — a YAML marshal would emit lowercased Go field names that would
// not line up. Mirrors cmd/fab's normalizeToGeneric.
func normalizeToGeneric(v any) any {
	data, err := json.Marshal(v)
	if err != nil {
		return v
	}
	var out any
	if err := json.Unmarshal(data, &out); err != nil {
		return v
	}
	return out
}

// asGenericMap coerces a decoded YAML/JSON value to map[string]any when it is a
// mapping (handling both map[string]any and map[any]any).
func asGenericMap(v any) (map[string]any, bool) {
	switch m := v.(type) {
	case map[string]any:
		return m, true
	case map[any]any:
		out := make(map[string]any, len(m))
		for k, val := range m {
			ks, ok := k.(string)
			if !ok {
				return nil, false
			}
			out[ks] = val
		}
		return out, true
	default:
		return nil, false
	}
}

// topLevel collapses a dotted registry key to its top-level YAML key
// ("agent.tiers" → "agent", "project.name" → "project", "source_paths" →
// "source_paths").
func topLevel(key string) string {
	if i := strings.IndexByte(key, '.'); i >= 0 {
		return key[:i]
	}
	return key
}

// sortedKeys returns the map's keys in sorted order (deterministic output).
func sortedKeys(m map[string]string) []string {
	out := make([]string, 0, len(m))
	for k := range m {
		out = append(out, k)
	}
	sort.Strings(out)
	return out
}
