package configupgrade

import (
	"fmt"
	"os"
	"path/filepath"
	"regexp"
	"strings"

	"gopkg.in/yaml.v3"

	"github.com/sahil87/fab-kit/src/go/fab/internal/atomicfile"
	"github.com/sahil87/fab-kit/src/go/fab/internal/configref"
	"github.com/sahil87/fab-kit/src/go/fab/internal/configscope"
	"github.com/sahil87/fab-kit/src/go/fab/internal/configvalue"
)

var liveKeyLineRe = regexp.MustCompile(`^( *)([A-Za-z_][A-Za-z0-9_-]*):(.*)$`)

// SystemScaffoldHeader is the canonical preamble for ~/.fab-kit/config.yaml.
// Both init and a first `set --system` use this exact text.
const SystemScaffoldHeader = `# ~/.fab-kit/config.yaml — system-level fab config (all repos on this machine).
# Resolves BELOW any project's fab/project/config.yaml and ABOVE built-in
# defaults. Only preference-class fields (scope: system/both) are honored here;
# a project-scoped field placed in this file is ignored with a warning.
#
# This scaffold is generated by ` + "`fab config init --system`" + ` from the same
# per-field metadata table as ` + "`fab config explain`" + `, so it cannot drift from
# the schema. Every block below is COMMENTED — uncomment and edit a block to set
# a system-level override.`

// Set writes one validated project override through the managed-fence engine.
// It edits only the requested live YAML path, then regenerates the fence through
// renderMutation; it never marshals the whole document or performs Upgrade-only
// reconciliation of unrelated keys.
func Set(path, key, rawValue, kitVersion string) (Result, error) {
	match, ok, err := configref.ResolveKey(key)
	if err != nil {
		return Result{}, err
	}
	if !ok {
		return Result{}, fmt.Errorf("unknown config key %q — run `fab config explain %s` to inspect valid keys", key, key)
	}
	value, err := configvalue.Parse(rawValue)
	if err != nil {
		return Result{}, fmt.Errorf("invalid value for %q: %w", key, err)
	}
	if value.Kind != match.Kind {
		return Result{}, fmt.Errorf("config key %q expects a YAML %s, got %s", key, match.Kind, value.Kind)
	}

	fields, err := configref.Fields()
	if err != nil {
		return Result{}, err
	}
	original, _, err := readFile(path)
	if err != nil {
		return Result{}, err
	}
	live, parked := mutationLiveArea(original)
	if strings.TrimSpace(live) != "" {
		if err := validateYAML(live); err != nil {
			return Result{}, fmt.Errorf("configupgrade: refusing to set %q in %s — existing live config does not parse as YAML: %w", key, path, err)
		}
	}
	live = ensureRegistryMaterialization(live, key, match.Owner)
	mutated, _, err := setLivePath(live, key, value)
	if err != nil {
		return Result{}, fmt.Errorf("setting config key %q: %w", key, err)
	}
	rendered, report := renderMutation(mutated, parked, fields, kitVersion)
	if err := validateYAML(rendered); err != nil {
		return Result{}, fmt.Errorf("configupgrade: refusing to write %s — setting %q produced invalid YAML (%w); the file was left unchanged", path, key, err)
	}
	return writeMutation(path, original, rendered, report)
}

// Unset removes one known project override without inspecting its live value.
// That deliberate asymmetry makes unset the repair path for a malformed or
// wrong-kind override. An absent known path is an exit-zero byte-preserving no-op.
func Unset(path, key, kitVersion string) (Result, error) {
	if _, ok, err := configref.ResolveKey(key); err != nil {
		return Result{}, err
	} else if !ok {
		return Result{}, fmt.Errorf("unknown config key %q — run `fab config explain %s` to inspect valid keys", key, key)
	}

	fields, err := configref.Fields()
	if err != nil {
		return Result{}, err
	}
	original, _, err := readFile(path)
	if err != nil {
		return Result{}, err
	}
	live, parked := mutationLiveArea(original)
	mutated, changed, err := unsetLivePath(live, key)
	if err != nil {
		return Result{}, fmt.Errorf("unsetting config key %q: %w", key, err)
	}
	if !changed {
		return Result{Changed: false, Report: []string{fmt.Sprintf("%s is not set; nothing to unset", key)}}, nil
	}
	rendered, report := renderMutation(mutated, parked, fields, kitVersion)
	if err := validateYAML(rendered); err != nil {
		return Result{}, fmt.Errorf("configupgrade: refusing to write %s — unsetting %q did not repair the YAML (%w); the file was left unchanged", path, key, err)
	}
	return writeMutation(path, original, rendered, report)
}

// SetSystem writes one system-visible override without introducing a project
// reference fence. A missing file is created with the canonical system header.
func SetSystem(path, key, rawValue string) (Result, error) {
	match, ok, err := configref.ResolveKey(key)
	if err != nil {
		return Result{}, err
	}
	if !ok {
		return Result{}, fmt.Errorf("unknown config key %q — run `fab config explain %s` to inspect valid keys", key, key)
	}
	if match.Field.Scope != configscope.ScopeSystem && match.Field.Scope != configscope.ScopeBoth {
		return Result{}, fmt.Errorf("config key %q has project scope and cannot be set in ~/.fab-kit/config.yaml", key)
	}
	value, err := configvalue.Parse(rawValue)
	if err != nil {
		return Result{}, fmt.Errorf("invalid value for %q: %w", key, err)
	}
	if value.Kind != match.Kind {
		return Result{}, fmt.Errorf("config key %q expects a YAML %s, got %s", key, match.Kind, value.Kind)
	}

	original, exists, err := readFile(path)
	if err != nil {
		return Result{}, err
	}
	live := original
	if !exists {
		live = SystemScaffoldHeader
	}
	if strings.TrimSpace(live) != "" {
		if err := validateYAML(live); err != nil {
			return Result{}, fmt.Errorf("configupgrade: refusing to set %q in %s — existing system config does not parse as YAML: %w", key, path, err)
		}
	}
	live = ensureRegistryMaterialization(live, key, match.Owner)
	mutated, _, err := setLivePath(live, key, value)
	if err != nil {
		return Result{}, fmt.Errorf("setting system config key %q: %w", key, err)
	}
	mutated += "\n"
	if err := validateYAML(mutated); err != nil {
		return Result{}, fmt.Errorf("configupgrade: refusing to write %s — setting %q produced invalid YAML (%w); the file was left unchanged", path, key, err)
	}
	if mutated == original {
		return Result{Changed: false}, nil
	}
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		return Result{}, fmt.Errorf("creating system config directory: %w", err)
	}
	if err := atomicfile.WriteFile(path, []byte(mutated), 0o644); err != nil {
		return Result{}, fmt.Errorf("configupgrade: writing %s: %w", path, err)
	}
	return Result{Changed: true}, nil
}

// UnsetSystem removes one system-visible override. Like project Unset it does
// not parse the current value first, so it can repair a malformed override.
func UnsetSystem(path, key string) (Result, error) {
	match, ok, err := configref.ResolveKey(key)
	if err != nil {
		return Result{}, err
	}
	if !ok {
		return Result{}, fmt.Errorf("unknown config key %q — run `fab config explain %s` to inspect valid keys", key, key)
	}
	if match.Field.Scope != configscope.ScopeSystem && match.Field.Scope != configscope.ScopeBoth {
		return Result{}, fmt.Errorf("config key %q has project scope and cannot be unset in ~/.fab-kit/config.yaml", key)
	}
	original, exists, err := readFile(path)
	if err != nil {
		return Result{}, err
	}
	if !exists {
		return Result{Changed: false, Report: []string{fmt.Sprintf("%s is not set; nothing to unset", key)}}, nil
	}
	mutated, changed, err := unsetLivePath(original, key)
	if err != nil {
		return Result{}, fmt.Errorf("unsetting system config key %q: %w", key, err)
	}
	if !changed {
		return Result{Changed: false, Report: []string{fmt.Sprintf("%s is not set; nothing to unset", key)}}, nil
	}
	mutated += "\n"
	if err := validateYAML(mutated); err != nil {
		return Result{}, fmt.Errorf("configupgrade: refusing to write %s — unsetting %q did not repair the YAML (%w); the file was left unchanged", path, key, err)
	}
	if err := atomicfile.WriteFile(path, []byte(mutated), 0o644); err != nil {
		return Result{}, fmt.Errorf("configupgrade: writing %s: %w", path, err)
	}
	return Result{Changed: true}, nil
}

func mutationLiveArea(original string) (string, []string) {
	preamble, belowFence, parked := splitFence(original)
	if strings.TrimSpace(belowFence) != "" {
		preamble = strings.TrimRight(preamble, "\n") + "\n" + strings.TrimLeft(belowFence, "\n")
	}
	return preamble, parked
}

func writeMutation(path, original, rendered string, report []string) (Result, error) {
	if rendered == original {
		return Result{Changed: false, Report: report}, nil
	}
	if err := atomicfile.WriteFile(path, []byte(rendered), 0o644); err != nil {
		return Result{}, fmt.Errorf("configupgrade: writing %s: %w", path, err)
	}
	return Result{Changed: true, Report: report}, nil
}

type liveKeyLine struct {
	line       int
	indent     int
	key        string
	path       string
	colon      int
	value      string
	commentPos int
}

// ensureRegistryMaterialization turns the owning registry Segment into the live
// path skeleton for a top-level key that exists only in the managed fence. It
// extracts the parent/requested key lines from CommentOutSegment — the exact
// renderer used by renderFence — but omits prose, sibling examples, and example
// values. setLivePath then fills only the requested value, so a later unset can
// remove the path cleanly without leaving generated comments outside the fence.
func ensureRegistryMaterialization(document, key string, owner configref.Field) string {
	top := strings.SplitN(key, ".", 2)[0]
	if _, ok := findLiveEntry(scanLiveKeyLines(splitMutationLines(document)), top); ok || owner.Segment == "" {
		return document
	}

	skeleton, ok := registryMaterializationSkeleton(owner, key)
	if !ok {
		return document
	}
	if strings.TrimSpace(document) == "" {
		return skeleton
	}
	return strings.TrimRight(document, "\n") + "\n\n" + skeleton
}

func registryMaterializationSkeleton(owner configref.Field, key string) (string, bool) {
	lines := strings.Split(CommentOutSegment(owner.Segment), "\n")
	virtual := append([]string{}, lines...)
	for i, line := range virtual {
		if strings.HasPrefix(line, "# ") {
			virtual[i] = strings.TrimPrefix(line, "# ")
		}
	}
	top := strings.SplitN(key, ".", 2)[0]
	var root, target liveKeyLine
	rootFound, targetFound := false, false
	for _, entry := range scanLiveKeyLines(virtual) {
		switch entry.path {
		case top:
			root, rootFound = entry, true
		case key:
			target, targetFound = entry, true
		}
	}
	if !rootFound {
		return "", false
	}

	out := []string{virtual[root.line][:root.colon+1]}
	if targetFound && target.path != root.path {
		out = append(out, virtual[target.line][:target.colon+1])
	}
	return strings.Join(out, "\n"), true
}

func scanLiveKeyLines(lines []string) []liveKeyLine {
	type parent struct {
		indent int
		path   string
	}
	var stack []parent
	var out []liveKeyLine
	for i := 0; i < len(lines); i++ {
		line := lines[i]
		m := liveKeyLineRe.FindStringSubmatch(line)
		if m == nil {
			continue
		}
		indent := len(m[1])
		for len(stack) > 0 && indent <= stack[len(stack)-1].indent {
			stack = stack[:len(stack)-1]
		}
		path := m[2]
		if len(stack) > 0 {
			path = stack[len(stack)-1].path + "." + path
		}
		colon := indent + len(m[2])
		rest := line[colon+1:]
		comment := inlineCommentIndex(rest)
		valuePart := rest
		if comment >= 0 {
			valuePart = rest[:comment]
		}
		out = append(out, liveKeyLine{
			line:       i,
			indent:     indent,
			key:        m[2],
			path:       path,
			colon:      colon,
			value:      strings.TrimSpace(valuePart),
			commentPos: comment,
		})
		stack = append(stack, parent{indent: indent, path: path})
		if isBlockScalarIndicator(strings.TrimSpace(valuePart)) {
			i = blockScalarEnd(lines, i, indent) - 1
		}
	}
	return out
}

func setLivePath(document, key string, value configvalue.Parsed) (string, bool, error) {
	lines := splitMutationLines(document)
	entries := scanLiveKeyLines(lines)
	if entry, ok := findLiveEntry(entries, key); ok {
		end := liveEntryEnd(lines, entry)
		lines[entry.line] = replaceLiveValue(lines[entry.line], entry, value.Text)
		if end > entry.line+1 {
			if isBlockScalarIndicator(entry.value) {
				// A block scalar's indented body is value data, including lines that
				// begin with '#'. Replacing the scalar drops the whole body verbatim.
				lines = dropMutationRange(lines, entry.line+1, end)
			} else {
				// Replacing a whole block-valued path removes its former descendants,
				// but promotes their user comments instead of silently discarding them.
				lines = removeMutationRange(lines, entry.line+1, end)
			}
		}
		return joinMutationLines(lines), true, nil
	}

	parts := strings.Split(key, ".")
	for n := len(parts) - 1; n >= 1; n-- {
		prefix := strings.Join(parts[:n], ".")
		entry, ok := findLiveEntry(entries, prefix)
		if !ok {
			continue
		}
		if entry.value != "" {
			parsed, err := configvalue.Parse(entry.value)
			if err != nil || parsed.Kind != configvalue.KindMapping {
				return "", false, fmt.Errorf("live ancestor %q is not a mapping", prefix)
			}
			rendered, err := setFlowMappingText(entry.value, parts[n:], value.Text)
			if err != nil {
				return "", false, err
			}
			lines[entry.line] = replaceLiveValue(lines[entry.line], entry, rendered)
			return joinMutationLines(lines), true, nil
		}

		step := childIndentStep(entries, entry)
		insertAt := liveBlockEnd(entries, entry, len(lines))
		addition := make([]string, 0, len(parts)-n)
		indent := entry.indent + step
		for i := n; i < len(parts); i++ {
			line := strings.Repeat(" ", indent) + parts[i] + ":"
			if i == len(parts)-1 {
				line += " " + value.Text
			}
			addition = append(addition, line)
			indent += step
		}
		lines = insertMutationLines(lines, insertAt, addition)
		return joinMutationLines(lines), true, nil
	}

	addition := make([]string, 0, len(parts)+1)
	if len(lines) > 0 && strings.TrimSpace(lines[len(lines)-1]) != "" {
		addition = append(addition, "")
	}
	for i, part := range parts {
		line := strings.Repeat(" ", i*4) + part + ":"
		if i == len(parts)-1 {
			line += " " + value.Text
		}
		addition = append(addition, line)
	}
	lines = append(lines, addition...)
	return joinMutationLines(lines), true, nil
}

func unsetLivePath(document, key string) (string, bool, error) {
	lines := splitMutationLines(document)
	entries := scanLiveKeyLines(lines)
	if entry, ok := findLiveEntry(entries, key); ok {
		end := liveEntryEnd(lines, entry)
		if isBlockScalarIndicator(entry.value) {
			lines = removeBlockScalarEntry(lines, entry, end)
		} else {
			lines = removeMutationRange(lines, entry.line, end)
		}
		lines = pruneEmptyParents(lines, strings.Split(key, ".")[:len(strings.Split(key, "."))-1])
		return joinMutationLines(lines), true, nil
	}

	parts := strings.Split(key, ".")
	for n := len(parts) - 1; n >= 1; n-- {
		prefix := strings.Join(parts[:n], ".")
		entry, ok := findLiveEntry(entries, prefix)
		if !ok || entry.value == "" {
			continue
		}
		parsed, err := configvalue.Parse(entry.value)
		if err != nil || parsed.Kind != configvalue.KindMapping {
			return document, false, nil
		}
		rendered, removed, empty, err := unsetFlowMappingText(entry.value, parts[n:])
		if err != nil {
			return "", false, err
		}
		if !removed {
			return document, false, nil
		}
		if empty {
			lines = removeMutationRange(lines, entry.line, entry.line+1)
			lines = pruneEmptyParents(lines, parts[:n])
			return joinMutationLines(lines), true, nil
		}
		lines[entry.line] = replaceLiveValue(lines[entry.line], entry, rendered)
		return joinMutationLines(lines), true, nil
	}
	return document, false, nil
}

func findLiveEntry(entries []liveKeyLine, path string) (liveKeyLine, bool) {
	for _, entry := range entries {
		if entry.path == path {
			return entry, true
		}
	}
	return liveKeyLine{}, false
}

func replaceLiveValue(line string, entry liveKeyLine, value string) string {
	rest := line[entry.colon+1:]
	comment := ""
	if entry.commentPos >= 0 {
		comment = strings.TrimSpace(rest[entry.commentPos:])
	}
	out := line[:entry.colon+1] + " " + value
	if comment != "" {
		out += " " + comment
	}
	return out
}

func childIndentStep(entries []liveKeyLine, parent liveKeyLine) int {
	for _, entry := range entries {
		if entry.line > parent.line && entry.indent > parent.indent && strings.HasPrefix(entry.path, parent.path+".") {
			return entry.indent - parent.indent
		}
	}
	return 4
}

func liveBlockEnd(entries []liveKeyLine, parent liveKeyLine, lineCount int) int {
	for _, entry := range entries {
		if entry.line > parent.line && entry.indent <= parent.indent {
			return entry.line
		}
	}
	return lineCount
}

func liveEntryEnd(lines []string, current liveKeyLine) int {
	if isBlockScalarIndicator(current.value) {
		return blockScalarEnd(lines, current.line, current.indent)
	}
	if current.value != "" {
		return current.line + 1
	}
	for i := current.line + 1; i < len(lines); i++ {
		line := lines[i]
		if strings.TrimSpace(line) == "" {
			continue
		}
		indent := len(line) - len(strings.TrimLeft(line, " "))
		if indent > current.indent {
			continue
		}
		if strings.HasPrefix(strings.TrimSpace(line), "#") && mutationCommentContinuesBlock(lines, i+1, current.indent) {
			continue
		}
		return i
	}
	return len(lines)
}

func isBlockScalarIndicator(value string) bool {
	if value == "" || value[0] != '|' && value[0] != '>' {
		return false
	}
	seenDigit, seenChomp := false, false
	for i := 1; i < len(value); i++ {
		switch c := value[i]; {
		case c >= '1' && c <= '9' && !seenDigit:
			seenDigit = true
		case (c == '+' || c == '-') && !seenChomp:
			seenChomp = true
		default:
			return false
		}
	}
	return true
}

func blockScalarEnd(lines []string, line, parentIndent int) int {
	for i := line + 1; i < len(lines); i++ {
		if strings.TrimSpace(lines[i]) == "" {
			continue
		}
		indent := len(lines[i]) - len(strings.TrimLeft(lines[i], " "))
		if indent <= parentIndent {
			return i
		}
	}
	return len(lines)
}

func mutationCommentContinuesBlock(lines []string, start, parentIndent int) bool {
	for i := start; i < len(lines); i++ {
		line := lines[i]
		if strings.TrimSpace(line) == "" || strings.HasPrefix(strings.TrimSpace(line), "#") {
			continue
		}
		indent := len(line) - len(strings.TrimLeft(line, " "))
		return indent > parentIndent
	}
	return false
}

func pruneEmptyParents(lines []string, parentParts []string) []string {
	for len(parentParts) > 0 {
		entries := scanLiveKeyLines(lines)
		path := strings.Join(parentParts, ".")
		parent, ok := findLiveEntry(entries, path)
		if !ok || parent.value != "" {
			parentParts = parentParts[:len(parentParts)-1]
			continue
		}
		hasChild := false
		for _, entry := range entries {
			if entry.line > parent.line && strings.HasPrefix(entry.path, path+".") {
				hasChild = true
				break
			}
		}
		if hasChild {
			break
		}
		lines = removeMutationRange(lines, parent.line, parent.line+1)
		parentParts = parentParts[:len(parentParts)-1]
	}
	return lines
}

func removeMutationRange(lines []string, start, end int) []string {
	var kept []string
	for _, line := range lines[start:end] {
		trimmed := strings.TrimSpace(line)
		if strings.HasPrefix(trimmed, "#") {
			kept = append(kept, line)
			continue
		}
		if m := liveKeyLineRe.FindStringSubmatch(line); m != nil {
			rest := m[3]
			if pos := inlineCommentIndex(rest); pos >= 0 {
				kept = append(kept, m[1]+strings.TrimSpace(rest[pos:]))
			}
			continue
		}
		if pos := inlineCommentIndex(line); pos >= 0 {
			indent := line[:len(line)-len(strings.TrimLeft(line, " "))]
			kept = append(kept, indent+strings.TrimSpace(line[pos:]))
		}
	}
	out := append([]string{}, lines[:start]...)
	out = append(out, kept...)
	out = append(out, lines[end:]...)
	return out
}

func dropMutationRange(lines []string, start, end int) []string {
	out := append([]string{}, lines[:start]...)
	return append(out, lines[end:]...)
}

func removeBlockScalarEntry(lines []string, entry liveKeyLine, end int) []string {
	// Preserve only a comment attached to the key line. Indented scalar-body
	// lines are data, even when their first non-space byte is '#'.
	kept := removeMutationRange(lines[entry.line:entry.line+1], 0, 1)
	out := append([]string{}, lines[:entry.line]...)
	out = append(out, kept...)
	out = append(out, lines[end:]...)
	return out
}

func insertMutationLines(lines []string, index int, addition []string) []string {
	out := make([]string, 0, len(lines)+len(addition))
	out = append(out, lines[:index]...)
	out = append(out, addition...)
	out = append(out, lines[index:]...)
	return out
}

func splitMutationLines(document string) []string {
	if document == "" {
		return nil
	}
	return strings.Split(strings.TrimRight(document, "\n"), "\n")
}

func joinMutationLines(lines []string) string {
	return strings.TrimRight(strings.Join(lines, "\n"), "\n")
}

func inlineCommentIndex(s string) int {
	inSingle, inDouble, escaped := false, false, false
	for i, r := range s {
		if escaped {
			escaped = false
			continue
		}
		if inDouble && r == '\\' {
			escaped = true
			continue
		}
		switch r {
		case '\'':
			if !inDouble {
				inSingle = !inSingle
			}
		case '"':
			if !inSingle {
				inDouble = !inDouble
			}
		case '#':
			if !inSingle && !inDouble && (i == 0 || s[i-1] == ' ' || s[i-1] == '\t') {
				return i
			}
		}
	}
	return -1
}

type flowPairSpan struct {
	key                  string
	start, end           int
	valueStart, valueEnd int
}

// setFlowMappingText edits a one-line flow mapping by byte span. yaml.v3 is
// still used by configvalue.Parse to validate shape, but the write path never
// serializes the parsed node: every byte outside the requested value or inserted
// pair survives verbatim.
func setFlowMappingText(mapping string, parts []string, value string) (string, error) {
	pairs, err := parseFlowMappingSpans(mapping)
	if err != nil {
		return "", err
	}
	for _, pair := range pairs {
		if pair.key != parts[0] {
			continue
		}
		if len(parts) == 1 {
			return mapping[:pair.valueStart] + value + mapping[pair.valueEnd:], nil
		}
		child := mapping[pair.valueStart:pair.valueEnd]
		parsed, parseErr := configvalue.Parse(child)
		if parseErr != nil || parsed.Kind != configvalue.KindMapping {
			return "", fmt.Errorf("live ancestor %q is not a mapping", parts[0])
		}
		mutated, err := setFlowMappingText(child, parts[1:], value)
		if err != nil {
			return "", err
		}
		return mapping[:pair.valueStart] + mutated + mapping[pair.valueEnd:], nil
	}

	insert := flowPathText(parts, value)
	if len(pairs) == 0 {
		close := strings.LastIndex(mapping, "}")
		if close < 0 {
			return "", fmt.Errorf("flow mapping is missing a closing brace")
		}
		pos := 1
		for pos < close && (mapping[pos] == ' ' || mapping[pos] == '\t') {
			pos++
		}
		return mapping[:pos] + insert + mapping[pos:], nil
	}
	pos := pairs[len(pairs)-1].end
	return mapping[:pos] + ", " + insert + mapping[pos:], nil
}

func flowPathText(parts []string, value string) string {
	if len(parts) == 1 {
		return parts[0] + ": " + value
	}
	return parts[0] + ": {" + flowPathText(parts[1:], value) + "}"
}

func unsetFlowMappingText(mapping string, parts []string) (mutated string, removed, empty bool, err error) {
	pairs, err := parseFlowMappingSpans(mapping)
	if err != nil {
		return "", false, false, err
	}
	for i, pair := range pairs {
		if pair.key != parts[0] {
			continue
		}
		if len(parts) > 1 {
			child := mapping[pair.valueStart:pair.valueEnd]
			parsed, parseErr := configvalue.Parse(child)
			if parseErr != nil || parsed.Kind != configvalue.KindMapping {
				return mapping, false, len(pairs) == 0, nil
			}
			childText, childRemoved, childEmpty, childErr := unsetFlowMappingText(child, parts[1:])
			if childErr != nil || !childRemoved {
				return mapping, childRemoved, len(pairs) == 0, childErr
			}
			if !childEmpty {
				out := mapping[:pair.valueStart] + childText + mapping[pair.valueEnd:]
				return out, true, false, nil
			}
		}

		out := removeFlowPair(mapping, pairs, i)
		remaining, parseErr := parseFlowMappingSpans(out)
		if parseErr != nil {
			return "", false, false, parseErr
		}
		return out, true, len(remaining) == 0, nil
	}
	return mapping, false, len(pairs) == 0, nil
}

func removeFlowPair(mapping string, pairs []flowPairSpan, index int) string {
	pair := pairs[index]
	switch {
	case len(pairs) == 1:
		return mapping[:pair.start] + mapping[pair.end:]
	case index < len(pairs)-1:
		return mapping[:pair.start] + mapping[pairs[index+1].start:]
	default:
		return mapping[:pairs[index-1].end] + mapping[pair.end:]
	}
}

func parseFlowMappingSpans(mapping string) ([]flowPairSpan, error) {
	if len(mapping) < 2 || mapping[0] != '{' || mapping[len(mapping)-1] != '}' {
		return nil, fmt.Errorf("expected a one-line flow mapping")
	}
	ranges, err := splitFlowRanges(mapping, 1, len(mapping)-1, ',')
	if err != nil {
		return nil, err
	}
	var pairs []flowPairSpan
	for _, span := range ranges {
		start, end := trimFlowSpace(mapping, span[0], span[1])
		if start == end {
			continue
		}
		colon, err := firstFlowDelimiter(mapping, start, end, ':')
		if err != nil || colon < 0 {
			return nil, fmt.Errorf("flow mapping entry %q has no key separator", mapping[start:end])
		}
		keyStart, keyEnd := trimFlowSpace(mapping, start, colon)
		valueStart, valueEnd := trimFlowSpace(mapping, colon+1, end)
		if keyStart == keyEnd || valueStart == valueEnd {
			return nil, fmt.Errorf("flow mapping entry %q has an empty key or value", mapping[start:end])
		}
		key, err := decodeFlowKey(mapping[keyStart:keyEnd])
		if err != nil {
			return nil, err
		}
		pairs = append(pairs, flowPairSpan{key: key, start: start, end: end, valueStart: valueStart, valueEnd: valueEnd})
	}
	return pairs, nil
}

func decodeFlowKey(raw string) (string, error) {
	var key string
	if err := yaml.Unmarshal([]byte(raw), &key); err != nil {
		return "", fmt.Errorf("parsing flow mapping key %q: %w", raw, err)
	}
	return key, nil
}

func splitFlowRanges(text string, start, end int, delimiter byte) ([][2]int, error) {
	var out [][2]int
	segmentStart := start
	err := walkFlowText(text, start, end, func(i int, c byte, depth int) bool {
		if c == delimiter && depth == 0 {
			out = append(out, [2]int{segmentStart, i})
			segmentStart = i + 1
		}
		return false
	})
	if err != nil {
		return nil, err
	}
	out = append(out, [2]int{segmentStart, end})
	return out, nil
}

func firstFlowDelimiter(text string, start, end int, delimiter byte) (int, error) {
	found := -1
	err := walkFlowText(text, start, end, func(i int, c byte, depth int) bool {
		if c == delimiter && depth == 0 {
			found = i
			return true
		}
		return false
	})
	return found, err
}

func walkFlowText(text string, start, end int, visit func(i int, c byte, depth int) bool) error {
	depth := 0
	var quote byte
	escaped := false
	for i := start; i < end; i++ {
		c := text[i]
		if quote != 0 {
			if quote == '"' && escaped {
				escaped = false
				continue
			}
			if quote == '"' && c == '\\' {
				escaped = true
				continue
			}
			if c == quote {
				if quote == '\'' && i+1 < end && text[i+1] == '\'' {
					i++
					continue
				}
				quote = 0
			}
			continue
		}
		switch c {
		case '\'', '"':
			quote = c
		case '{', '[':
			depth++
		case '}', ']':
			if depth == 0 {
				return fmt.Errorf("unbalanced flow collection")
			}
			depth--
		default:
			if visit(i, c, depth) {
				return nil
			}
		}
	}
	if quote != 0 || depth != 0 {
		return fmt.Errorf("unterminated flow collection or quote")
	}
	return nil
}

func trimFlowSpace(text string, start, end int) (int, int) {
	for start < end && (text[start] == ' ' || text[start] == '\t') {
		start++
	}
	for end > start && (text[end-1] == ' ' || text[end-1] == '\t') {
		end--
	}
	return start, end
}
